### ISSUE TITLE
Nothing works as previously in Windows 10

### ISSUE THREAD

**Issue by MagdaKi** [randyrants/sharpkeys#10]
I have a macbook. A couple of years ago I remapped my keyboard using SharpKeys and replaced mac command keys with alt keys in windows. It was installed in BootCamp. When I upgraded to Windows10 all remapping was gone. I don't see any changes in SharpKeys. I tried to restore my changes but now SharpKeys doesn't recognize my left command-turned-to-alt key at all. My right key is not affected and works as intended. Is there any solution to restore my keyboard to its default settings?  I would appreciate any help, I'm not tech savvy enough to solve this issue myself. There are no scancode map entries in the Registry.

**Comment by randyrants** [comment]
If there is no Scancode Map entry in the Registry, then nothing is being remapped.  SharpKeys simply exposes that key and does no remapping on it's own.  It sounds like something went off the rails when Windows got updated and/or Boot Camp's drivers have changed maybe?

**Comment by MagdaKi** [comment]
Thanks for the response. I wonder if it is possible that I wrote changes to the Registry and then somehow deleted entries from SharpKeys in a way that the keys remain remapped but SharpKeys doesn't see them? Is it any way to restore my keyboard to default settings? How can I check a key if SharpKeys doesn't recognize it?

**Comment by randyrants** [comment]
In a short answer, it's not possible.  SharpKeys does nothing but read from the Scancode Map value and Windows only remaps keys found in the Scancode Map value.  If there's no Scancode Map value then nothing is being remapped and nothing will show up in SharpKeys.
