### ISSUE TITLE
A couple of missing keys in a German HP keyboard.

### ISSUE THREAD

**Issue by jrmoore** [randyrants/sharpkeys#101]
Hi, it's a G1K29AA#ABD keyboard and mouse combo that came without a Windows key. In its place there's a key that opens up the default Internet browser, so my idea was to remap it to the usual Win key to be able to open up the Win+X menu in Windows 10.

So at first I thought about reporting it just as it was, the ID of that key seems to be 00_100. But then I went on and started trying other keys, and the same ID seems to be reported for some multimedia keys (mute, vol+ and vol-), and they do work fine with Windows.

Even weirder is that the browser key (or what I'd understand by the globe design) seems to be acting as the Windows key... and it's way up, just over the backspace one; which leads me to believe there could be drivers or something for this model but I couldn't find anything.

Any ideas? Or how to get around this?

Thanks.

PS. I don't know if it's important but virtually (i.e. selected in Windows) I have the Spanish layout over this keyboard. It's a German keyboard using a Spanish layout.

**Comment by randyrants** [comment]
Not sure how to get around this because 00_100 is the catch all that Windows reports when the key is trapped at a higher level in the driver, which means that if you remapped that code it would impact a lot of keys.  You might want to explore a more active remapper like AutoHotKeys.
