### ISSUE TITLE
A key that sharpkeys doesn't know about

### ISSUE THREAD

**Issue by sh5525** [randyrants/sharpkeys#106]
Hi,
I have a keyboard that replaces the function keys (F1, F2...) with some special keys. For F1's position particularly, it's a hot key to start web browser and open new page. When I input that key in sharpkeys, here comes the issure.
![image](https://user-images.githubusercontent.com/11629684/41632504-4db732f8-7408-11e8-9d8b-a53025763f90.png)
![image](https://user-images.githubusercontent.com/11629684/41632514-57a1d0ac-7408-11e8-8906-1426b3f327d3.png)
Is there anything I can do? Thank you.

**Comment by akai1831** [comment]
I've encountered this issue as well, by pressing Calculator button in a Numeric Keypad. We would need to remap the calculator button to different key. @randyrants

**Comment by randyrants** [comment]
Nothing to be done here: 00_100 is a common keycode that comes back from Windows when Windows doesn't know what key it is.  It often means that the key is being interpretted by hardware, driver software, or some other intercepting code that prevents Windows from seeing the key pressed.

**Comment by sh5525** [comment]
@randyrants So is there any work around? Because as I checked in the device manager in Windows, that bluetooth keyboard doesn't have its own driver software, still it can do the job mentioned before. That means at least my computer knows what's going on without any external help.

**Comment by randyrants** [comment]
Not that I know of: if an app on Windows can't get the scancode because it's transformed higher up, then there's nothing SharpKeys can do.  You might want to try a more active remapper like AutoHotKeys .

**Comment by sh5525** [comment]
@randyrants Thank you for recommendation

**Comment by D-Hoff-DK** [comment]
Hi guys, just wanted to bring this subject back up.. I was playing around with an Android BT keyboard on my Windows 10 tablet. All keys and the trackpad on the keyboard corresponded to the windows features except for "home" and "search" keys. When I press "home" on the Android keyboard my Win tablet opens the internet browser. The "search" key on the keyboard opens any search field available (on the desktop it opens a search in the start menu and in the browser it jumps to the search field at the top).
When I try to remap the keys I get the (00_100) error.

My question is, how come the keys have a function but cannot be registered by SharpKeys/Windows?

Is there any program that can scan what code is sent by the input device?

I am thinking that since the buttons do work, they must be sending something that Windows understands. If that is true, I should be able to remap them as well 8-)

I would love to hear your comments on this.

**Comment by randyrants** [comment]
Same response as before: "00_100 is a common keycode that comes back from Windows when Windows doesn't know what key it is. It often means that the key is being interpretted by hardware, driver software, or some other intercepting code that prevents Windows from seeing the key pressed."

**Comment by PioruneX** [comment]
I have question... Whats escape key code?
(Windows 10)

**Comment by randyrants** [comment]
You mean the scan code for Esc?  00_01

**Comment by nasusonetrick** [comment]
autohotkey says the scan code of "browers_home" is  SC132 
so how can we translate that to the Regedit key instead , i tried "32 e0" AKA ( E0_32 )
but it didn't do anything !

**Comment by randyrants** [comment]
I have no idea what SC132 is.

**Comment by DreymaR** [comment]
AutoHotKey operates with its own list of key names. For Scan Codes, it uses a shorthand where a key with a E0_## SC gets the AHK code SC1## (for any ## hex number).
https://www.autohotkey.com/docs/v1/KeyList.htm

So AHK's SC132 is the SC E0_32 key, named Browser/Home.
https://deskthority.net/wiki/Scancode

**Comment by randyrants** [comment]
Good, because that's the same value SharpKey uses:
`m_hashKeys.Add("E0_32", "Web: Home");`

But, as DreymaR calls out, not every keyboard implements their "extra" keys the same way.

**Comment by DreymaR** [comment]
Their reason for it is probably just to keep things short and sweet. A typical AHK hotkey may look like this:
`#n::Run Notepad`
(Runs Notepad when you press Win+N)
Whenever a key name is unclear or unavailable, its SC value may be substituted:
`SC149::MsgBox, You just pressed PgUp`

**Comment by randyrants** [comment]
I guess?  I mean, I don't know why you'd obsfucate it for the sake of... obsfucation?  Like in this instance, SC149 tells you nothing - it's like you they made it SC-PGUP or something.  I would have assumed this would be just as easy:
`E0_49::MsgBox, You just pressed PgUp.`

Not my app. and they have active remapping technology, so they should keep doing whatever it is they are doing!

**Comment by DreymaR** [comment]
We who have used AHK for a while have gotten so used to it, we'd never see the problem I guess. To me SC1## looks every bit as logical as SCE0_##, and it's a bit easier on the eyes and the keyboard. As long as it's a 1 for E0 and a 0 for 00 and everybody knows that, it isn't really an obfuscation. Just a convention that many find handy.

I see your quarrel with it, but it's easy to get used to and I never saw it as a problem myself.

**Comment by manasvchhabra** [comment]
If anyone is looking for a "workaround", you can use sharpkeys to map f1-f12 to your special keys (media icons, browser, calculator, etc.), then use AHK to create a script that allows you to use 1,2,3..9,0,-,= as f1-f12 and you can toggle this on and off when your function keys are needed.

**Comment by DreymaR** [comment]
Well, if I wanted to do that I'd just skip SharpKeys altogether and have the AutoHotKey script handle both cases.

**Comment by manasvchhabra** [comment]
That is the best way, but if someone doesn't wanna write the script themselves coz they're lazy then yeah.

For me I tried doing both with sharpkeys but then had to use ahk coz sharpkeys couldn't deal with it

**Comment by DreymaR** [comment]
It's actually a bit unfair to say Sharpkeys can't deal with it. It's Windows itself that limits the options.

But from an end-user viewpoint, sure. I just want to point out that this is in no way anything Randy could've fixed for us.
