### ISSUE TITLE
Sharpkeys does not recognize a keypress

### ISSUE THREAD

**Issue by pibebtol** [randyrants/sharpkeys#110]
On my Lenovo T480s, I have this weirdplaced 'print' key between the right control and right alt.

I tried remapping it with Sharpkeys, but sharpkeys couldn't recognize the key (using the 'type key'-function, it doesn't show anything when I press the key). Every other key was recognized correctly.

Is there any other way to identify such keys in a different way?

EDIT: Ok, I guess the FAQ thingy about the keys not detected by windows comes into effect for my problem, correct?

**Comment by randyrants** [comment]
See if you can select the Special: PrtSc from the “from” list.

**Comment by pibebtol** [comment]
> See if you can select the Special: PrtSc from the “from” list.

I didn't find this when I was scrolling through the list. **Works like a charm!**

Thank you for the help!
