### ISSUE TITLE
Swapping keys DOES work

### ISSUE THREAD

**Issue by NoPinky** [randyrants/sharpkeys#111]
Hello,
I've been using ShapKeys for 4 years on 4 Laptops (Thinkpads and 1 HP ZBook) with Windows 7 and 10. Even if it is clearly stated that:

> Things that SharpKeys will not do:
Allow you to swap two keys with each other - e.g. you can’t have Q and Z swap places because the remapping code would get confused

I tried it anyway (swapped z and y) from the beginning and it works flawlessly. I have never ran into any issues, glitches or whatever regarding my swapped keys. @randyrants : have you ever tried this case on your machine? I don't think this only works for me. 

Anyway, great tool, thank you for creating it.

**Comment by randyrants** [comment]
I've gotten reports where it's been a problem but without knowing exactly what was happening, I thought to call it out as a possible limitation.  People often leave a comment on my blog or email yelling at me that the remap didn't work and then never reply with data to troubleshoot - couldn't tell if it was a product error or user error, so I was uncharacteristically cautious :)

Thanks!
