### ISSUE TITLE
Mac like special left keys

### ISSUE THREAD

**Issue by thenikso** [randyrants/sharpkeys#112]
Hello here,

Sorry for this not being a proper issue. I am trying to have a mac like keyboard. I could replicate the layout (with all the accent keys goodies) using https://github.com/adunning/Mac-Keyboard-Layouts-for-Windows

However I would like to remap left special keys from:

```
Ctrl   Win   Alt
```

To (having the right AltGr become Alt):
```
Win   AltGr  Ctrl
```

Is this possible and how?

Thanks!

**Comment by thenikso** [comment]
Well I managed to do this quite easily! One should first try it before opening an issue I suppose, but I hope this will help anyone passing by for something similar.

I simply used SharpKeys to remap the following:

```
From:                                          To:
Special: Left Alt (00_38)              Special: Left Ctrl (00_1D)
Special: Left Ctrl (00_1D)            Special: Left Windows (E0_5B)
Special: Left Windows (E0_5B)   Special: Right Alt (E0_38)
Special: Right Alt (E0_38)           Special: Left Alt (00_38)
```

**Comment by game-libgdx-unity** [comment]
> Well I managed to do this quite easily! One should first try it before opening an issue I suppose, but I hope this will help anyone passing by for something similar.
> I simply used SharpKeys to remap the following:
> From:                              To:
> Special: Left Alt (00_38)          Special: Left Ctrl (00_1D)
> Special: Left Ctrl (00_1D)         Special: Left Windows (E0_5B)
> Special: Left Windows (E0_5B)      Special: Right Alt (E0_38)
> Special: Right Alt (E0_38)         Special: Left Alt (00_38)

please send me save keys file... I cant type left alt key. ty!
