### ISSUE TITLE
Missing keymap buttons

### ISSUE THREAD

**Issue by bgmastermind** [randyrants/sharpkeys#113]
I got my hands on a PC remote. IT works great on my windows 10, all buttons work exactly as shown on the picture, and i want to remap two of them, but the codes seems to be missing in your app.
![image](https://user-images.githubusercontent.com/24807093/43212523-d8615cbc-903c-11e8-9370-b0760e26615c.png)
This is the email button.
Then when pressing the www button, default browser opens, but keycode is still the same. 
That is the remote https://i.ebayimg.com/images/g/ZWIAAOSwOVpXYmKp/s-l1600.jpg
I could remap the music and video buttons, but their keycodes are also missing.

**Comment by randyrants** [comment]
Nothing can be done for this as 00_100 is a catch all for unknown keys.  Plz see https://github.com/randyrants/sharpkeys/blob/master/README.md#additional-faq-and-answers for more.
