### ISSUE TITLE
Key E0_78 is laptop function key

### ISSUE THREAD

**Issue by Goodlookinguy** [randyrants/sharpkeys#116]
Key E0_78 is laptop FN key.

**Comment by randyrants** [comment]
For you laptop, yes but sadly there is no fixed value for other FN keys - other keyboards report E0_63.

Remapping should still work fine.

**Comment by Goodlookinguy** [comment]
But it doesn't. It tells me to update the software.

**Comment by randyrants** [comment]
Oops.  Looks like keys stopped at E0_6F.  I'll leave this open so someone can pick it up for a future release.

**Comment by randyrants** [comment]
Checked into source.  I'll build an install eventually.
