### ISSUE TITLE
remapping reverts on reboot

### ISSUE THREAD

**Issue by jimluckett** [randyrants/sharpkeys#12]
New Lenovo laptop with Windows 10.
Remapped up arrow to right shift, rebooted, worked fine.
Next day, booted up and remapping had reverted to original (up arrow is up arrow).

**Comment by randyrants** [comment]
Which build of Windows 10?  There is another thread on the issues calling out that Creator Edition is flipping the order, an issue I haven't been able to reproduce :(

**Comment by jimluckett** [comment]
Home Edition



Jim Luckett
(co-owner)
SailboatsToGo, LLC
23 Pine Vale Rd
Waltham, MA 02451

978 263 7598
www.sailboatsToGo.com
fax 206 339 7528
cell 617 645 1605

*Non-U.S. orders:  Foreign tax not included in price nor shipping.

Like us on: www.Facebook.com/SailboatsToGo

Shop SeaEagle.com:  http://www.dpbolvw.net/click-4273968-531689

Paypal us:  https://www.paypal.me/SailboatsToGo
l

**Comment by randyrants** [comment]
Sorry, I meant which build: ver from a command prompt.

**Comment by jimluckett** [comment]
​



Jim Luckett
(co-owner)
SailboatsToGo, LLC
23 Pine Vale Rd
Waltham, MA 02451

978 263 7598
www.sailboatsToGo.com
fax 206 339 7528
cell 617 645 1605

*Non-U.S. orders:  Foreign tax not included in price nor shipping.

Like us on: www.Facebook.com/SailboatsToGo

Shop SeaEagle.com:  http://www.dpbolvw.net/click-4273968-531689

Paypal us:  https://www.paypal.me/SailboatsToGo
l
