### ISSUE TITLE
E_20 (Media mute) Is assigned to multiple keys

### ISSUE THREAD

**Issue by anthr0p** [randyrants/sharpkeys#123]
Hey,
I am not quite sure if this is the right place to ask. After I have been deleting an entry in SharpKeys I was not able to use Volume Up/Down. Instead my volume was muted. In other words Vol Up/Down has been assigned the mute Key.
Is there a solution to this problem?

Regards

**Comment by randyrants** [comment]
You can always remove all of the remappings, save them to the registry, and reboot.  SharpKeys doesn't actually run any remapping code on your PC: SharpKeys is simply editing a Registry key that allows the remapping to be done by Windows.
