### ISSUE TITLE
Unknown keys: pipe "|" and broken bar "¦"

### ISSUE THREAD

**Issue by OverdueFashion** [randyrants/sharpkeys#126]
Hi, I would like to reverse these two keys on my Swiss-German keyboard however they are not yet recognized by SharpKeys. When I use the TypeKey function in your software I get the following results:

Pipe = | = E0_1F08
Broken bar = ¦ = E0_1F02
And that these keys are unknown. Could you add these?
Thanks for the nice work.

**Comment by randyrants** [comment]
Are these keys the whole key or do they share function with something else?  Like does pressing Shift + Pipe show up as a > or a [ maybe?
