### ISSUE TITLE
Music application and Computer Explorer

### ISSUE THREAD

**Issue by dpeteual** [randyrants/sharpkeys#129]
I have a keyboard with a Music key that opens the default Windows 10 Music Player app. Also a Computer key that open the PC explorer window..
Both are just about the backspace key and I keep pressing them by accident. 
Neither key is recognized by Sharpkeys

**Comment by randyrants** [comment]
Likely because there's no code coming back through Windows so Windows can't remap it.  I've see this on earlier Microsoft Keyboard that had active drivers that handled these extra buttons; you might want to see if there is a driver for your keyboard.
