### ISSUE TITLE
Remapping FN key

### ISSUE THREAD

**Issue by Kynisen** [randyrants/sharpkeys#13]
Hey there, I don't know if I am in the right spot, but I am trying to remap my FN key to function as a CTRL key. I was hoping to be able to just switch the two but I saw that Sharpkeys doesn't really "swap" so I am just fine with changing the FN key. I went to set it up and I tried the "type key" option... pressed my FN key and nothing happened. So I selected "Special (Wake or FN) (E0_63) Since that was the closest match. And in the second column the "press key" option worked for my left CTRL so I set it, pressed Write to Registry, restarted, but the FN key wasn't affected. Let me know what I am doing wrong? Thank you

**Comment by llinfeng** [comment]
@Kynisen Have you found a way to "identify" the FN key? Or, have you found other ways to remap the FN key? I am having the same trouble.

**Comment by Kynisen** [comment]
I actually ended up getting a different keyboard, so I didn't look further into it. Sorry! Good luck.

**Comment by younes0** [comment]
@llinfeng did you find a solution?

**Comment by llinfeng** [comment]
@younes0 I too have ended up with another keyboard. Apologize for not being more helpful :) Here is what I know about `Fn` keys per my own setup. 

----

<https://uhk.io> offers mechanical keyboards with programmable "layers", where each key can be remapped using their open-source [UHK agent](https://github.com/UltimateHackingKeyboard/agent). Their [firmware](https://github.com/UltimateHackingKeyboard/firmware) is also an open-source project.

I do use Thinkpad keyboards, where the manufacturer provides a driver/utility software that can swap Fn and L-Ctrl. Here is a screenshot taken from the Lenovo Vantage app on Windows 10, under My Device Settings \ Input & Accessories.
![image](https://user-images.githubusercontent.com/5890407/96622110-85621b80-12d7-11eb-8d29-67a2538e6ee4.png)
Though, this only applies to the keyboards that are integrated into a Thinkpad laptop and does not cover those [external keyboards](https://www.lenovo.com/us/en/accessories-and-monitors/keyboards-and-mice/keyboards/kbd-bo-trackpoint-kbd-us-english/p/4Y40X49493) with exactly the same layout.

----

In general, `Fn` key is notorious for users to remap. There is also a large community of users who use AutoHotKey as their daily drivers. You may have a chance to remap the `Fn` key on your keyboard by looking further in [the community forum for AHK](https://www.autohotkey.com/boards/).

**Comment by younes0** [comment]
@llinfeng wow, thanks for all the informations. 
My laptop is Lenovo Thinkpad and I don't have the Lenovo Vantage App.
But I easily managed to do the same (FN and CTRL swap) via the BIOS
