### ISSUE TITLE
Altgr is not the same as right alt.

### ISSUE THREAD

**Issue by acautin** [randyrants/sharpkeys#131]
I was trying to map left alt into altGr(``E0_2038``) and key is successfully detected, but once it is saved it gets converted into right alt (``E0_38``) which for me is not working properly. I am using windows 10 via rdp from Os X. Spanish keyboard.

**Comment by limeb** [comment]
I having this same issue.  Right now I am using autohotkey to get around this issue.

**Comment by CodemanV** [comment]
Confirmed.    Having exact same issue as AndrewSavill trying to map AltGr to Right Alt.   I'm using a a Logitech G510s UK layout keyboard.

**Comment by SteveCTOS** [comment]
I was trying to map the right Alt key to the Left Alt key for use in a puTTY  application.  This worked but now the F3 and F5 keys don't work.  F3 and F5 on this laptop have a fn function too...
I am using a Dell e6520 laptop with the US ps/2 kbd.
Please advise how to fix this.....

**Comment by randyrants** [comment]
For the OP, I suggest selecting the characters from the list as ALT after gets intercepted by Windows and as I've mentioned in several Alt+Gr posts, I do not have hardware or language skills to support testing it.
