### ISSUE TITLE
Distinguish with software between 2 keys

### ISSUE THREAD

**Issue by limeb** [randyrants/sharpkeys#132]
I type on a JIS keyboard layout with the thumb modifiers keys set to ctrl.

There are a couple other minor modifications, like making the backspace 2 keys and shift 2 keys more like a United States ANSI keyboard layout and lastly changing the Caps Lock key.

Any ways let's say I assign the 0070 key on the JIS keyboard layout to be another control key, is there a way to distinguish in software(autohotkey would be ideal) between the original ctrl key and the newly assigned one.

It would be a big help.

**Comment by randyrants** [comment]
Nope.  Windows only sees the whole key and it remaps the whole key - it has no way of knowing if it's a remapped key or a hardware physical key.  Might want to try AutoHotKeys which is a more active remapper.

**Comment by limeb** [comment]
If anyone is curious I did find a solution for this issue and that is using the left and right control to distinguish between them using autohotkey.
