### ISSUE TITLE
Export as Registry File

### ISSUE THREAD

**Issue by limeb** [randyrants/sharpkeys#133]
Is there a way to export the registry modifications to a registry file?

I'm not allowed to run 3rd party software on my work computer but registry tweaks are permitted.

**Comment by randyrants** [comment]
Yes: use RegEdit to export the Scancode Map value from HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Keyboard Layout but two things: 
1. If your work PC doesn't allow third party software but you can still edit the registry by hand, someone in IT should be fired.
2. I'm not responsible for anything you do while in the Registry.
