### ISSUE TITLE
Remap pressed keys

### ISSUE THREAD

**Issue by IvanGalban** [randyrants/sharpkeys#134]
I would like to remap pressed keys. For example:

Caps Lock (pressed) --> Ctrl (pressed)

**Comment by randyrants** [comment]
Remap Caps Lock to Left or Right Ctrl, save, and reboot.

**Comment by IvanGalban** [comment]
Sorry, maybe I do not explain well what I wanted.

I have remapped Caps Lock to Escape, but I also to remap pressed Caps (key under pressure) Lock to Left Ctrl.

This could be possible ?

**Comment by randyrants** [comment]
You cannot.  I mean, you can map Caps Lock to be Escape but that's it: there's no way to have a long press be something different.  The whole key is remapped.
