### ISSUE TITLE
R-Alt to L-Alt Mapping leaves F1 - F5 not working 

### ISSUE THREAD

**Issue by SteveCTOS** [randyrants/sharpkeys#138]
I was trying to map the right Alt key to the Left Alt key for use in a puTTY application. This worked but now the F1 through F5 keys don't work. F1, F3 and F5 on this laptop have a fn function too...
I am using a Dell e6520 laptop with the US ps/2 kbd.
Please advise how to fix this.....

**Comment by randyrants** [comment]
I have no idea what the app is doing but remapping the keys is done at the Windows level and not by my app.  It could be that puTTY is not getting input from the Windows drive and maybe has a hook at a lower level?  My app just exposes a Registry key and doesn't remap anything.  You might want to try AutoHotKeys.
