### ISSUE TITLE
You pressed 00_100 (you entered a key sharpkeys doesn't know about)

### ISSUE THREAD

**Issue by alexwh** [randyrants/sharpkeys#14]
I'm trying to rebind my mute, volume up and volume down buttons on my Ducky Zero (DK2108SZ) to play/pause, next and previous, but sharpkeys says it doesn't recognise the key typed. This also happens with the calculator button, and manually binding the vol up/down/mute to the specified keys also does not work.
Happy to provide more information or test debug builds etc.
Using version 3.5.

**Comment by seanspotatobusiness** [comment]
I have the same response to the extra keys on my Zalman ZM-K350M keyboard.

**Comment by seanspotatobusiness** [comment]
Hey bit from the Readme this seems relevant:

Things SharpKeys will not do:
_Support certain hardware keys that never make it to Windows - e.g. Logitech’s volume buttons or most Fn keys_

I don't know why hardware keys don't make it to Windows but I guess this is something to do with that.

**Comment by randyrants** [comment]
That would be my expectation as well: some key strokes get intercepted by hardware or drivers and never get to Windows, which means they cannot be remapped by Windows.
