### ISSUE TITLE
 I think ñ has it's own key on a keyboard?

### ISSUE THREAD

**Issue by gitut2007** [randyrants/sharpkeys#141]
From https://github.com/randyrants/sharpkeys/issues/136 Add the Spanish letter 'ñ' 
Hi, I think ñ has it's own key on a keyboard, on all the 'Spanish layouts'; I don't know where to look for its code, I found Alt and ASCII codes, 
Thanks.
(I found this, I guess maybe is of no use here)
U+00F1 UTF-8 (hex) 	0xC3 0xB1 (c3b1) 
UTF-8 (binary) 	11000011:10110001
UTF-16 (hex) 	0x00F1 (00f1)
UTF-16 (decimal) 	241
UTF-32 (hex) 	0x000000F1 (f1)
UTF-32 (decimal) 	241
C/C++/Java source code 	"\u00F1"
Python source code 	u"\u00F1"
ALT+165 Alt+0241

**Comment by gitut2007** [comment]
(The position of ñ in the english layout is the key ;/: 00_27)

**Comment by guigofu** [comment]
I have a Spanish keyboard, comfirming that in Sharpkeys the ñ key is registered as ;/: 00_27.
So I guess you could choose a layout in windows that has the ñ as a separate key and use that, obviously this will also change the position of symbols (keys and shift + numbers on top row). Finally I think that a different software is best suited for this particular job (AutoHotKeys, EurKey).

**Comment by fabriph** [comment]
For the record, EurKey was the best option I could find when trying to address this issue. Thanks for suggesting

**Comment by marcelo4768** [comment]
in the section "to this key ( to key ) " which one is the " ñ " ??

**Comment by DreymaR** [comment]
> For the record, EurKey was the best option I could find when trying to address this issue. Thanks for suggesting

I think EurKey is quite haphazardly designed. At least look at the [eD] AltGr/deadkey layers as a IMNSHO much better alternative.

https://dreymar.colemak.org

Also note that EurKey is a layer design, not a remapping tool. The tools in use will typically be AutoHotKey or MSKLC (Microsoft's keyboard layout creator tool).
