### ISSUE TITLE
The Dev Team Doesn't Get Thanked Enough!

### ISSUE THREAD

**Issue by xgpt** [randyrants/sharpkeys#142]
Just wanted to give you an easy issue to fix, thanks for this fantastic software! Really improved my workflow when I'm stuck on Windows and can't remap keys like I usually do in *nix!

**Comment by randyrants** [comment]
Thanks!  And by that I mean thanks to all of the coders contributing to the project through PR and support!

**Comment by vmiheer** [comment]
I have been using this software for atleast two years. The first thing I do after installing Windows is to install this software. Given I use emacs, this is the boon to remap my Ctrl <-> Caps Lock.

**Comment by tkf144** [comment]
Thanks Randy and contributors, for making simple, intuitive software that does just what it needs to and nothing more. Every time I set up a machine where re-mapping is needed, I appreciate SharpKeys. Thanks again!

**Comment by psyanite** [comment]
I second this. 🙏🙏🙏

**Comment by thshdw** [comment]
This method allows me to use my layout of choice when I rdp to other systems. So thank you! 😄

**Comment by bawldiggle** [comment]
A sanity saver. Thank you

**Comment by RumataEstor** [comment]
A big thank you for the program! You saved my hands!

**Comment by shinmai** [comment]
Also, I'd just like to point out, that the readme saying SharpKeys will _not_
> Allow you to swap two keys with each other - e.g. you can’t have Q and Z swap places because the remapping code would get confused  

That's not actually true, at least for what I need it to do, that is to swap LCtrl & CapsLock on my work-computer with a cheap OEM keyboard, to match my Ducky Shine 2 at home, where it's a DIP switch setting.

**Comment by frame** [comment]
Yes, I also swap Left-Windows with Left-Alt (and vice versa), it works fine for me since many years. (On Windows 10 with an Apple Keyboard)

**Comment by randyrants** [comment]
Huh.  I had gotten feedback that this wasn't working, which is why it went into the FAQ; I'll update that.

**Comment by hmahadik** [comment]
This is the best issue ever. Thanks randyrants! I've been using this software for so many years too. Love the apple keyboard that came with my iMac but hated the fact that the Windows <-> Alt key mapping was reverse. Thanks once again!

**Comment by dcts** [comment]
yeah this works perfectly for me! Remapped my `alt gr` key to `backspace`, typing is now much faster!

**Comment by rhuanbarreto** [comment]
Great to remap between windows and mac the command, start and alt key!

**Comment by sectorogo** [comment]
This is one really useful application. I had a problem with Windows 10 1809 and <Num .>
With this app i just remapped it and now it works.

Thank you!

**Comment by ejc1** [comment]
Thank you so much!  My new PC came without a PrintScreen key!  I mapped a function key F2 to it.  Now I get F2 = take a screenshot of the whole screen, and Alt-F2 = take a screenshot of the currently active window, which is perfect.  Also I have Windows 10 and it worked fine.

**Comment by randyrants** [comment]
Thanks for all the kind words!  Also, as an FYI, if there are any Surface users here, I uploaded an SKL file that flips F9-F12 to Home/End/PgUp/PgDn - more information lives here: https://github.com/randyrants/sharpkeys/blob/master/HandyRemapForSurfaceKeyboard.skl

**Comment by epalm** [comment]
Thanks @randyrants been using SharpKeys for years. I appreciate not only the software itself, but the fact that you've been a good guardian, merging PRs and releasing new versions like a boss.

**Comment by h3nn1ng** [comment]
thank you very much :) 10/10

**Comment by efruchter** [comment]
What an amazing tool!

**Comment by adamhrosenberg** [comment]
big thanks
