### ISSUE TITLE
Improper save of HP Display key mapping

### ISSUE THREAD

**Issue by tjuhasz1** [randyrants/sharpkeys#143]
Hi! HP Display key (E0_1F6D) was newly added to latest release on my request. When I save a mapping to the insert key, and exit/restart Sharpkeys, it shows that the App Media Select (E0_6D) key was mapped - seems to be a bug. The mapping is also ineffective after restart of the machine. Regards: Tamas

![image](https://user-images.githubusercontent.com/44211364/47988551-cceb3f00-e0e2-11e8-92ae-5318299ca7b0.png)

**Comment by randyrants** [comment]
Please follow up with the contributors that assured this community that triple byte codes were now supported and working, when they made their pull request, https://github.com/randyrants/sharpkeys/pull/55

**Comment by rchoc** [comment]
Hello, I can also confirm HP keys are not saved in registry correctly. (v3.8.0)
HP Display Key (E0_1F6D) is being saved as App: Media Select (E0_6D)
HP HangUp Key (E0_1F65) is being saved as Web: Search (E0_65)
HP Call key is not captured as input.

@igieon tested different triple byte keys for #55, #39 and #54 and #39 was tested & confirmed by reporter. So triple byte seems to be working, but not for these HP keys.

@etomkra, did these keys work for you? from #127 or #128.
