### ISSUE TITLE
Key swaps don't work in some instances

### ISSUE THREAD

**Issue by Vilacard** [randyrants/sharpkeys#146]
I'm not sure where else to post about this. I have my left caps lock mapped to act as left ctrl, and my left ctrl to act as caps lock. The vast majority of times, it works fine.

Sometimes it doesn't work though, and they'll revert to the default keys (caps lock is caps lock). It's not random, and only happens with certain programs. First, while it works in Firefox the vast majority of the time, whenever I load a character armory page for World of Warcraft (ex: https://worldofwarcraft.com/en-us/character/lightbringer/Einzbern), it happens. It also happens while playing Final Fantasy XI.

**Comment by guigofu** [comment]
Hi, as it is stated in the readme it is not "supported", but has been working well for me swapping esc with caps lock.

> Things that SharpKeys will not do:
>  Allow you to swap two keys with each other - e.g. you can’t have Q and Z swap places because the remapping code would get confused

**Comment by Vilacard** [comment]
Huh, never knew that. I had been using it that way for years.

I changed it so caps lock is now right ctrl, and kept left ctrl as caps lock. That seems to work fine mostly. It behaves as expected on the world of warcraft armory page. 

It still doesn't behave correctly in Final Fantasy 11 though: my caps lock key (which is mapped to right ctrl) does nothing. The physical right ctrl key does as it should (bring up a set of macros, which left ctrl does the same). What's bizarre now is that my left ctrl key brings up the macros as it should, but it also triggers caps lock.

**Comment by randyrants** [comment]
Games are unique creatures on PC: simply put, keys don't always come to Windows, so they cannot be remapped, much like how some keys bypass games and go straight to Windows (as most gamers know if they hit the Win key accidentally while a game is fullscreen).
