### ISSUE TITLE
"Eject" button on Mac Keyboard not being detected

### ISSUE THREAD

**Issue by dmhelenberger** [randyrants/sharpkeys#148]
It's the top-right button on said keyboard, and when I press "Detect Key" it doesn't pop up, nor is there any option for an Eject button in all the keys :<

**Comment by randyrants** [comment]
Pretty sure this is a hardware key, meaning that Windows doesn't get notified of it being pressed.  Either that or Bootcamp drivers are not forwarding it along to Windows.
