### ISSUE TITLE
Some keys do not fuction in some programs

### ISSUE THREAD

**Issue by DrunkDeo** [randyrants/sharpkeys#15]
My laptop's keyboard is broken so some letters don't work, for example, the "F" key didn't work so I re-mapped it to CAPS LOCK, and it works perfectly on Chrome and in some keyboard testers, but when I open some games or even Microsoft Word it doesn't seem to be working

**Comment by randyrants** [comment]
Games I cannot speak to because they often use a different input flow for keyboard presses but it should be working on Word since Windows itself is mapping the key.  Very odd.
