### ISSUE TITLE
Mapping button E0_1F18

### ISSUE THREAD

**Issue by Voo2** [randyrants/sharpkeys#150]
On my Microsoft Surface Ergonomic keyboard there is a button called E0_1F18. It is intended to open the Action Center of Microsoft Windows. Sharpkeys don't support this button yet.

**Comment by randyrants** [comment]
Sorry but triple byte keys are not supported.

**Comment by RumataEstor** [comment]
@randyrants I've got Microsoft Sculpt Ergonomic Desktop Keyboard and wanted to remap (E0_1F6C) to F5. As I understood your response, it's not possible through the registry mapping, is it?

**Comment by randyrants** [comment]
Correct: it is not possible.
