### ISSUE TITLE
Type Key issue when mapping Num Lock key

### ISSUE THREAD

**Issue by clementratel** [randyrants/sharpkeys#151]
Hi,

Seems there is some trouble with the "Type Key" feature, even I found workaround.
I needed to map the Num Lock key of my laptop (to permanently disable it).
When using the "Type Key" and hitting the Num Lock key, I received code "Special € (E0_45)".
Mapping this key would have no effect at all on Num Lock.
I used instead the "Special Num Lock (00_45)" from the sharpkeys list and then it worked.

a+,=)
-=Clement=-

Configuration: Windows 10 Pro ; DELL Latitude E5570
Sharpkeys 3.8 portable

**Comment by randyrants** [comment]
No idea why Num Lock is sending the wrong scan code but you've done the right thing in selecting it in the available keys list.  I can't hard code the E0_45 to reflect 00_45 because I'm pretty sure that Euro key is real.  

Sorry for the confusion!
