### ISSUE TITLE
Backslash key types # instead

### ISSUE THREAD

**Issue by Hague80** [randyrants/sharpkeys#153]
So I use the excellent sharpkeys to remap some keys on my Panasonic, which has a Japanese/International keyboard. But one of these seems to have an error: when I map a key to (00_2B), which should be the backslash key, it instead types # (or with shift, ~). Any idea why this might be happening and how I coudl fix it?

Thanks so much!

Stephen

**Comment by Hague80** [comment]
So I use the excellent sharpkeys to remap some keys on my Panasonic, which has a Japanese/International keyboard. But one of these seems to have an error: when I map a key to (00_2B), which should be the backslash key, it instead types # (or with shift, ~). Any idea why this might be happening and how I coudl fix it?

Thanks so much!

Stephen

**Comment by randyrants** [comment]
Well, I can't test this - no International keyboard - but it could be that 00_2B makes to # on the Japanese layout instead of the / that you're expecting.  Not sure if this is something that can be fixed wit hthe Windows remapping tech.
