### ISSUE TITLE
Unknown key: 0xE004 (E0_04)

### ISSUE THREAD

**Issue by SkippyTheMoonRock** [randyrants/sharpkeys#154]
I have a "Turbo-Trak KD-9001R+" keyboard, and a key that's labeled "DOS" does not work with SharpKeys.

**Comment by randyrants** [comment]
I would recommend trying to remap this by hand in the Registry because this "DOS" key sound like what would be a triple byte enabled key which is not re-mappable by SharpKeys.  Another option is to use an active remapper like AutoHotKeys
