### ISSUE TITLE
Unknown key: (E0_1F00)

### ISSUE THREAD

**Issue by heX16** [randyrants/sharpkeys#155]
Lenovo ThinkPad P50 

![image](https://user-images.githubusercontent.com/3930496/51305468-0679e800-1a4c-11e9-9222-cd80ab6c0a8f.png)
I do not know what this "fn" button does. When pressed (with **Fn** of course), nothing happens. But she gives out the code and it can be useful to me.

**Comment by randyrants** [comment]
Well, this key is going to popup the Alt+Tab overlay that's available in Windows 10 or if Fn+Lock is on, F11.  F11 is easy to remap but the Alt+Tab functionality looks to be generating a triple byte code, which is not supported by the Windows remapping tech.
