### ISSUE TITLE
Option key on Apple Magic Keyboard can't be mapped

### ISSUE THREAD

**Issue by tgkreutz** [randyrants/sharpkeys#157]
I just connected a new Apple Magic keyboard to a Windows 10 Dell workstation, and successfully mapped Left Command to Left Control.  But, when I hit the "Type Key" button and hit the Option key, nothing happens.  (Just like the "fn" key.)  Does this mean that I can't access then Alt key when using this keyboard?

Many thanks for this awesome program!

**Comment by psyanite** [comment]
maybe these will help you? 
https://github.com/randyrants/sharpkeys/wiki/Using-an-Apple-Magic-keyboard
https://github.com/randyrants/sharpkeys/issues/52
I assume you have the latest version installed.

**Comment by randyrants** [comment]
From the FAQ, Alt does not show up with Type Key: Windows intercepts the key and refuses to send it to the popup window.  You can select Special: Left Alt or Special: Right Alt by hand in the remapping window.

**Comment by tgkreutz** [comment]
Randy,

   Thanks for your note, but I'm still confused.  I would like the Magic 
keyboard's Option key to act as a Windows Alt key.  Is that possible, or 
is the Option key effectively dead?

   Many thanks!

Tom

**Comment by psyanite** [comment]
try this ? 

https://drive.google.com/file/d/0B-xKnsieUawEOFVfVEpMWThxSmFWRnloU082VzYzVUo0WmZN/view?usp=drivesdk

I'm pretty sure I opened sharp keys and asked it to listen to a key and then hit the option key. and then on the right hand side I selected the windows key.

**Comment by psyanite** [comment]
there are still some missing ones like alt tab doesn't work the same anymore, so I would recommend you try win apple key maybe  or autokey to map alt tab

**Comment by randyrants** [comment]
Well, I can’t say what the Option key is on the Magic’s keyboard because I’ve never seen it.  What I was calling out is that if you try to type Alt on the “Type key” screen, it won’t work.  You always have to select Alt from the list of available keys, when remapping it.

 

HTH!
