### ISSUE TITLE
Can I map a key as a "new" mod key?

### ISSUE THREAD

**Issue by andrew-vant** [randyrants/sharpkeys#158]
I gather that one of the most common uses of sharpkeys is to make capslock act as something more useful -- often esc or alt. I want to make it act as Hyper, which doesn't exist on my keyboard (or most others, I think). The idea being that I could then use it for personal keyboard shortcuts and be reasonably sure they will never conflict with anything else.

Can this be done? I don't see hyper in the list of available mappings, and I'm not sure if any of the ones I don't recognize can act as mod keys.

**Comment by randyrants** [comment]
I have no idea what Hyper is so I cannot comment to that - would need the Scancode so it could be added to the source.  

You can definitely remap it to Esc or Shirt of Alt.

**Comment by andrew-vant** [comment]
Hyper was a modifier key on the [Space Cadet Keyboard](https://en.wikipedia.org/wiki/Space-cadet_keyboard). It doesn't exist on modern keyboards. It acted like alt/shift/ctrl do. I don't know what its scancode is on the keyboard where it's actually present. (I'm not even sure that's a meaningful concept across keyboards).

I'm not looking to map capslock to the shift/alt/ctrl modifier keys; I'm looking to turn it into an entirely new modifier key, so that I can (for example) map `caps+G` to "open gvim" without interfering with anything that might already be mapped to `[ctrl|alt|shift]+G`. I thought mapping capslock to a mod key that didn't exist on my keyboard (but which does on others) might work, but I don't know much about how keyboards function so I may be looking in entirely the wrong direction.

Another possibility would be to map it to one of the unknown values in the "to this key" list, but I don't know what that would do exactly...it's not clear from the list which keys are "modifier-like." I tried the "ISO extra key" for example (which also doesn't exist on my keyboard) but it just made capslock insert a backslash.

**Comment by randyrants** [comment]
Way outside the scope of the ability of Windows remapping.  You might want to look at AutoHotKeys or something that is a proactive remapper.

**Comment by andrew-vant** [comment]
Maybe. I see entries in Sharp for F13-F24. Mapping caps->F24 sort-of-works; AHK's keyboard hook detects the keystrokes, though it lists them as "unknown"; VK code 0xED instead of the expected 0x87 ([reference](https://docs.microsoft.com/en-us/windows/desktop/inputdev/virtual-key-codes)). 0xED is in the "OEM Specific" range.

The nonexistent F keys are probably "safe" in the sense that nothing uses them, so I might be able to figure something out.
