### ISSUE TITLE
Clarify from and to columns

### ISSUE THREAD

**Issue by mikemccaffrey** [randyrants/sharpkeys#161]
Every time I get a new computer and go to set up SharpKeys, I am confused about the "From" and "To" columns on the main screen and which side to put which key. I can never remember if I am trying to map the function **from** one key **to** another, or changing a key **from** its original function **to** the function of another key. 

Maybe relabel the columns "Key" and "New Function" for clarity?

**Comment by randyrants** [comment]
Can you verify which form/scene you're looking at and version?  For example, on the Add New Key Mapping, the labels are "Map this key (From key)" and "To this key (To key)".

Thanks!

**Comment by mikemccaffrey** [comment]
@randyrants I think the important part is to distinguish that are are mapping a "function" onto a "key".

PS. I totally guessed wrong this time, and now I have two keys that do the function that I don't care about and no keys doing the function that I want!

**Comment by randyrants** [comment]
...which answered none of my questions.  

Also, this doesn't move "function" - this is actually remapping the whole key, which is different from function which might sound OK when remapping Sleep or Play but more confusing when remapping the dual keys like [ { and ] }.
