### ISSUE TITLE
Caps Lock Key

### ISSUE THREAD

**Issue by clickman818** [randyrants/sharpkeys#162]
It does not recognize this key if the key is already already mapped to be turned off. Unsetting the key back to the normal CapsLock will make it recognizable and allow it to be remapped to another  key., In my case, I was ( and did )  wanting to remap to DEL. Perhaps when the user types the CAPSLOCK, and then tried to remap, the error message could recognize the CapsLock but tell user that it is already remapped., instead of telling user that caps lock is not recognized.

**Comment by DreymaR** [comment]
That's not quite how it works I believe. When SharpKeys (or manual registry editing) has disabled the CapsLock key, there is no way SharpKeys could see that you pressed CapsLock. Therefore, the program could not behave like you want it to.

Again: The remapping itself is done in the Windows Registry. Not in the program. SharpKeys is a front-end for registry remapping.
