### ISSUE TITLE
Unknown key - HP 840G5 call end key

### ISSUE THREAD

**Issue by futrix** [randyrants/sharpkeys#163]
HP EliteBook 840 G5 has no Insert button and I would like to map it with SharpKeys. 
The button code is E0_1F65 and it's labeled with call end icon. Is there any chance to introduce it do SharpKeys?

**Comment by randyrants** [comment]
No: this is a triple byte key which Windows does not support the remapping of.  Nothing for SharpKeys can do with this.

**Comment by rbarte** [comment]
On this laptop you can use FN+E for the Insert.

FN+R = Break

FN+S = Sys Rq

FN+C = Scroll Lock

FN+W = Pause

https://h30434.www3.hp.com/t5/Business-Notebooks/There-is-no-INSERT-key-on-the-new-2018-Hp-840-elitebook-G5/td-p/6695864
