### ISSUE TITLE
Remap Num Lock

### ISSUE THREAD

**Issue by Robertus00** [randyrants/sharpkeys#165]
Hello. 

I remap Num Lock key so now is always disabled. But the problem is when I start Windows, Num Lock is off and I cannot use the numbers to introduce my PIN (because the key is disabled). Any idea how can I solve this?

Regards.

**Comment by bawldiggle** [comment]
You have disabled NumLock you need it to be ON (enabled), to atleast insert numerals using NK ( Numeric Keypad).
If you dont want NK in Navigate mode I would suggest ...
http://atornblad.se/keep-numlock-on-permanently  by by "Anders Tornblad"
To lock the NK in permanent Numeric input (NumLock ON)
