### ISSUE TITLE
Remap help F1 question

### ISSUE THREAD

**Issue by El-Poyo-Loco** [randyrants/sharpkeys#167]
If I remap the key F1 without the fn button on my laptop, I get both the new key (delete) and the help function on windows. In other words, I cannot remove the help (?) function from windows.

**Comment by randyrants** [comment]
Fn depends on whether or not it's a hardware toggle or software.  Sounds like yours is software which means SharpKeys cannot help.

https://github.com/randyrants/sharpkeys#things-that-sharpkeys-will-not-do
