### ISSUE TITLE
Logitech K400 Keyboard - Unrecognized Volume Commands

### ISSUE THREAD

**Issue by thuhreb** [randyrants/sharpkeys#168]
I'm using the quite common - for entertainment PCs anyway - Logitech K400 Plus keyboard with touchpad.  I'm wanting the large mute volume button to send an F11 - fullscreen web browser keystroke.  SharpKeys 3.9.0 is seeing this as  (00-100), resulting in an unknown key error.  I'm also seeing that volume up and down keys also sending the (00-100) code with same error.  These are the only keys I've noticed having issues reading.  Let me know if there's anything I can do on my end to give you more data or test a possible solution.  Thanks.

**Comment by randyrants** [comment]
Nothing Windows or SharpKeys can do: https://github.com/randyrants/sharpkeys#additional-faq-and-answers
