### ISSUE TITLE
Trying to use with a bluetooth game controller and scan codes are constantly overwritten

### ISSUE THREAD

**Issue by seanspotatobusiness** [randyrants/sharpkeys#17]
I can't get the key scan code that I want because it keeps getting overwritten. I have this* bluetooth game controller that I want to use to simulate some keyboard buttons. The problem is that it seems to constantly output the code E0_3F6A so when I press another button (or keyboard key) it flashes only very quickly before returning to E0_3F6A. By recording my screen I've determined the codes for the four buttons: E0_3F65, E0_3F64, E0_3F76, E0_3F6E but I don't know how to use this information with SharpKeys since it relies on not getting another scan code before you hit OK. I'm using Windows 10.

Video: https://youtu.be/Wb6MZbgIEuQ

*https://www.aliexpress.com/item/100-New-Arrival-Wireless-Bluetooth-Game-Controller-Gamepad-Joystick-for-Android-iOS-Smart-Phone-Smartphone-Hot/32270082587.html

**Comment by randyrants** [comment]
Triple byte codes are always a tricky thing to remap in this key and not something that all that easy to figure out.  That said I'll leave this Issue open in case someone on GitHub to offer up a Pull request.
