### ISSUE TITLE
 Double key mapping

### ISSUE THREAD

**Issue by jefke723** [randyrants/sharpkeys#173]
Here the question whether it is possible to double browse through?
I have a 4-key kensington presenter
1 of those keys is recognized by the PC as being the "b" key
When I re-map to enter, I get the phenomenon that when I need a letter "b", it is recognized as enter
I had in mind to first reregister the "b" to eg "$", then reregister this "$" to "µ" and then correctly reregister the "b" key because it is still " $ "but this doesn't work
I use the latest version 3.9 and even this is not possible
I would like a solution to be able to change from a key "b" (recognized by pressing a key) to an enter key with or without specifying another key

**Comment by randyrants** [comment]
No idea, as I do not have a Kensington presenter but I can say that this Windows Registry key only remaps keyboards.  If this is some other type of device, I would not expect it to work.

**Comment by jefke723** [comment]
![kingston presenter](https://user-images.githubusercontent.com/49001822/55272931-c8f3cf80-52c4-11e9-86bc-a8dccdf649ec.png)
Dear see a photo of the presenter here
This is used for powerpoint presentation
So this is read on the keyboard
The green key can simply be re-mapped that this becomes a digit "0"
I can remap the forward arrow to a "+" sign
With the arrow backwards I can re-map to a "-" sign
I can re-map the pause key to an "enter" key
But by re-mapping these, I lose the letter "b" on the keyboard
I am willing to assign a different letter to it, but this only works once and not twice

**Comment by randyrants** [comment]
That is not a keyboard, so I would not expect it to work.

**Comment by jefke723** [comment]
![sharp key mapping](https://user-images.githubusercontent.com/49001822/55285847-c7450d00-5393-11e9-9e46-9b207e04658f.png)
With the built-in function, see figure, this works perfectly
Only, as already explained when pushing, the key with the square is recognized by the system as a "b"
But if, for example, after the remapping, the word "but" needs to enter it does not succeed, then the "b" has become an enter key
I am therefore looking for a solution problem for this
I need an enter key from that presenter to operate a program with
as indicated at the beginning to do multiple re-mapping, the program does not allow this I have already tried
Ps after some looking for work in the hardware I have found that input from the presenter read word through p / s2 interface has become recognized on hard ware possible as another option to the remapping

**Comment by randyrants** [comment]
And again, there's nothing that I can do for this.  The remapping fucntionality is a part of Windows: my app is used to define mappings that Windows accepts and puts it in a Registry key for Windows to pick up.  There's no way to have the B key remapped to Enter for the remote thing but still be a B on the keyboard.  It is impossible with the remapping tech that Windows offers.  I recommend trying something like AutoHotKeys or maybe even XMouse which might have the ability to profile what is pressing what and remap the key actively.
