### ISSUE TITLE
Unknown key

### ISSUE THREAD

**Issue by bou7a** [randyrants/sharpkeys#174]
I'm trying to swipe the right "Alt Gr" with the left "Alt" it shows an unknown key for the "Alt Gr" and does not detect the left "Alt" when typing the key.

**Comment by randyrants** [comment]
This is expected, albeit a painful thing.  The Alt key doesn't get all the way to the the Type Key window, so you'll have to select Alt from the list of keys by hand.

https://github.com/randyrants/sharpkeys#additional-faq-and-answers
