### ISSUE TITLE
Keys that SharpKeys doesn't know about

### ISSUE THREAD

**Issue by DavidRBailey** [randyrants/sharpkeys#175]
I've got a case where I'm running a Windows 10 PC through a remote connection on a Mac, and one of the keys comes back as E0_1F38, which SharpKeys says it doesn't know about.

Is there a way to add an option for a custom keycode in the "Map this key (From key):" list?

**Comment by randyrants** [comment]
Keycodes can be added through source code contributions.  While anyone can add scancodes to the Registry themselves, I feel that opening up the app to take in straight test will eventually lead to a bad write to the Registry and thus begins the "I'm had to reinstall Windows and it's your apps' fault!"  I already get a lot of "I uninstalled your app and the keys are still remapped!" email inspite of all efforts to teach people that a) SharpKeys is not doing the remapping and b) the only way to get rid of a remapping is to update the Registry and reboot (which can be done with my app or directly through regedit).

Anyway, for this key, it's a triple-byte scancode so Windows cannot process it anyway, per https://github.com/randyrants/sharpkeys#additional-faq-and-answers

Thanks!
