### ISSUE TITLE
Trying to remap unused keys to the þ symbol

### ISSUE THREAD

**Issue by Duvi0** [randyrants/sharpkeys#176]
My fantasy world that I'm writing uses a lot of the thorn symbol, both in its capital (Þ) and lowercase (þ) forms. As a result, I've gone all but mad with the amount of Ctrl+C/Ctrl+V I have to do for words, names, places, etc. I was hoping to use SharpKeys to adjust a pair (or if possible a single) key(s) in order to do this,, but I believe this key type is obscure enough to where there's no way for my programming-illiterate behind to figure out how to accomplish that. Please, someone help?

**Comment by randyrants** [comment]
The only way for that to work is if there's a dedicated key for the symbol - no idea if such a scan codee exists.
