### ISSUE TITLE
just a comment : Caps Lock for Clipboard History

### ISSUE THREAD

**Issue by LucianoBestia** [randyrants/sharpkeys#178]
Mostly all we hate the CapsLock key. 
So I use it to open the Clipboard History from Outertech.
I was always upset, that windows Clipboard has only one item.
I think most people need more that one text item in Clipboard.

I will use SharpKey on my MacBookAir with BootCamp Win10 to change the Cmd and Alt keys.
The Mac locations is different from the windows location and it makes me go crazy when I'm typing.

Thanks.

**Comment by randyrants** [comment]
If I've read the Insider notes for Windows 10's 1903 update, there will be a new clipboard available that will be available, but I think that's tied to Win+V to paste from a list of copied content; Ctrl+V still pastes the most recent item.

That said, as this as a combination of keys, SharpKeys won't be able to remap  the functionality, but might save you an install down the line.
