### ISSUE TITLE
possible to map unknown key E0_1F65 to "Insert" key ?

### ISSUE THREAD

**Issue by aiwaxxx** [randyrants/sharpkeys#180]
Is it possible to map unknown key E0_1F65 to "Insert" key ?

E0_1F65 is Phone disconnect key on new systems with mobile SIM-Card slot. These systems dont have an Insert button !

**Comment by randyrants** [comment]
No, because that is a triple-byte key code.  For more see https://github.com/randyrants/sharpkeys#additional-faq-and-answers
