### ISSUE TITLE
How to install this??

### ISSUE THREAD

**Issue by cobbit** [randyrants/sharpkeys#181]
Thanks for the software but tell me how to install this thing, please.

**Comment by frame** [comment]
You can either run the msi installer or extract the zip folder anywhere on your computer and run SharpKeys.exe. You can find the download for each version at the Releases page, here on Github: https://github.com/randyrants/sharpkeys/releases

In your case I recommend downloading and running the msi Installer. It will do everything for you.

**Comment by randyrants** [comment]
What @frame said :)
