### ISSUE TITLE
Key remapping not working

### ISSUE THREAD

**Issue by gKrager** [randyrants/sharpkeys#188]
I've remapped the "Web keys" from my keyboard to "Media keys".. I want the forward-backwards to work as media keys and the Home key to work as Play/Pause.

I've set the keys, wrote to registry, restarted and I do see them set in the program, but the keys were not changed in practical use.

Is there any reason why the programs settings wouldn't be working?

edit: trying to "type" the keys when remapping it gives back the same code "00_100" to all of them and when setting them it says "you've entered a key that sharpkeys doesn't know about".
It's a genius keyboard with a web keys layout on top, are these not supported?

**Comment by randyrants** [comment]
00_100 means that the key values are not getting to Windows so Windows cannot remap them successfully.

https://github.com/randyrants/sharpkeys#additional-faq-and-answers
