### ISSUE TITLE
Not an issue, just a thank you note

### ISSUE THREAD

**Issue by neothoms** [randyrants/sharpkeys#190]
Thank you so much.
Thanks to you I have been able to switch the awfull keyboard placement of my lenovo back to a more usable disposition.

**Comment by randyrants** [comment]
Thanks ;)

**Comment by Rusty-Shackleford** [comment]
My left pinky also thanks you, horribly disfigured by that nefarious `ctrl` key... Well done!  

ヽ(´▽`)/

**Comment by randyrants** [comment]
Cheers :)
