### ISSUE TITLE
Sharpkeys window stays in external monitor

### ISSUE THREAD

**Issue by jenny-xing** [randyrants/sharpkeys#193]
I was using sharp keys on my laptop that was plugged into an external monitor. I dragged the Sharpkeys window to use on my external monitor. After unplugging my HDMI cable, the Sharpkeys window was not consolidated/moved to my computer monitor, making it seem like it was not opening (wen in fact, it was, but was just "off screen".

This is happening on my windows 10 machine. 

also, it looks like multiple instances can be run simultaneously. 

Screenshot (right side is external monitor): 
![image](https://user-images.githubusercontent.com/5709881/60556937-81407200-9d11-11e9-93f0-4c8e16bbdcff.png)

**Comment by randyrants** [comment]
That it opens more than once is expected.  My memory is fuzzy on this but at one point the code required to check for an existing instance of the app running was a pain in the neck for .NET when I first wrote the app in 2004 and I likely didn't think it hurt anything so... feature?  I can look into it in the future.

Why the app is hanging out on the external monitor I have no seen and is frankly something Windows should be taking care of for the app.  One thing to try, if you see this happen again, is to see what state the computer is in when you unplug the HDMI cable.  Meaning if you hit Win+P after unplugging, does the PC still think it's Extending?  If so then it could be a driver issue with the graphics subsystem, where the PC still thinks the cable is connected, so it doesn't know to tear down the other monitor.  Likewise, if it's still in that state, try Win+P again and select "PC Screen" to see what happens.

**Comment by alexcode9** [comment]
Alt+Space > Maximize
