### ISSUE TITLE
My laptop shuts down

### ISSUE THREAD

**Issue by derikbacon** [randyrants/sharpkeys#196]
Hello team, 
First of all, thank you for developing this useful tool.

I remaped my Function key to use it as "left control" and vice versa. It worked in the beginning, but 2 days after it broke. Now every time I push the Function button the laptop shuts down. I tried to re-remap them and also formatted the laptop, but it doesn't work. Any idea how to fix it?
Thank you very much.

**Comment by randyrants** [comment]
Frankly, I have no idea.  The Fn key is not a key that can be mapped on most keyboard or laptops.  They are very often a hardware key that doesn't get sent to Windows at all, so Windows never has a chance to remap it.

If it worked for a day or two and then stopped, it could be that some other driver or app got installed that has changed the support.  You might want to use an active remapper like AutoHotKeys.
