### ISSUE TITLE
Doesn't full work.

### ISSUE THREAD

**Issue by quickeagle12** [randyrants/sharpkeys#198]
It works while typing but when I go to a game for example rainbow six siege the key remapping doesn't work the key's I changed was from caps lock to left shift, It worked normally doing anything else except for games, I set it to change the registry as an attempt to fix it but it did not. Just wanted to report this

**Comment by randyrants** [comment]
Actually, you've got the right of it: Games have nearly complete control over the machine, especially when full screen, and they may or may not control the keystrokes on their own.  Meaning that they may not send them back to Windows which means that Windows cannot remap them.

Might want to get something more active like AutoHotKeys or see if you can remap keys within in the game itself.
