### ISSUE TITLE
downloaded but can't install

### ISSUE THREAD

**Issue by apexcorner** [randyrants/sharpkeys#2]
Hi, I just downloaded SharpKeys (Windows 10) by clicking "clone or download" and then choosing "download zip". I then extracted the directory but there doesn't seem to be an executable installer or setup file in there. If I try opening "app.config" or "Sharpkeys.exe.manifest" I just get a windows message asking me what app I would like to use to open this type of file extension. Sorry - not very technically gifted. What am I missing? Thanks.

**Comment by randyrants** [comment]
You were likely on the Code tab, which means you downloaded the source code.  On that same page, click Releases or go there directly: [https://github.com/randyrants/sharpkeys/releases](https://github.com/randyrants/sharpkeys/releases)

**Comment by apexcorner** [comment]
Oh you're quite right. Thanks. Now installed. Only thing is: I can't find a mapping for the "Break" key (I'm on an Asus Laptop with German keyboard layout, where it's designated "Pause/Untbr"). I tried using the "type key" function and it interpreted it as "Num Lock", but when I implemented that, it didn't successfully map the Break key and it did remap the Num Lock key, which I didn't want to do. Is there any fix for this (or any prospect of one)? Apologies if this is the wrong place to be asking a tech help question.

**Comment by randyrants** [comment]
Asks for tech support are cool, but it'll but up to a contributor to make a fix and there might not be one for this.  Break, Pause, and NumLock are all unique keys with "strange" attributes, being either hardware based or triple byte enabled all of which make remapping unlikely.  There's more of a write up on my blog from years back at http://www.randyrants.com/sharpkeys.
