### ISSUE TITLE
Genius Smart keyboard

### ISSUE THREAD

**Issue by Monteo** [randyrants/sharpkeys#200]
![Безымянный](https://user-images.githubusercontent.com/24656088/63501322-a3769500-c4f5-11e9-8fdf-c1441a9162f7.png)
Want to remap this is button by means of windows- is not defined by the application

**Comment by frame** [comment]
@randyrants: Clearly spam.

What a waste for issue #200 :)

**Comment by Monteo** [comment]
@frame obviously disappear in horror

**Comment by randyrants** [comment]
Well, if Windows doesn't know what it is, it can't remap it and since my app is just a UI friendly interface to a Registry key, it cannot help. Maybe AutoHotKeys?

Unless it is some joke reference and I'm not grokking the icon.  That would be worthy of #200 :)

**Comment by Monteo** [comment]
not like a joke
http://us.geniusnet.com/product/smart-kb-101

**Comment by randyrants** [comment]
Thanks for the link: this is definitely not going to be something that Windows can remap on it's own.  If it's not a hardware based key (like Fn often is) it's scancode is bound to be trapped at the driver level.

Sorry!
