### ISSUE TITLE
Support for E0_1F1D

### ISSUE THREAD

**Issue by Alastowor** [randyrants/sharpkeys#203]
So I saw that this issue was posted before, and in a commit it was removed. I'm wondering if it's possible that we can get it back at all, or an explanation as to why it was removed and can't be added back or supported, and are there any alternatives for Windows 10.
I'm on a laptop, ThinkPad X220t. I was told to try using Autohotkey, however I have no experience with it and no idea on how I would use it to set up the key.

**Comment by randyrants** [comment]
**Q: Type a Key shows a code that is E0_nnnn - can I remap this key?**
A: If a scancode has 6 numbers, then it is what is known as a triple byte scancode which is something that cannot be remapped by the Windows Registry. To remap a key like this, you'll need an active remapper like AutoHotKeys or the app that came with the keyboard (e.g. Logitech's Options) if available.

From: https://github.com/randyrants/sharpkeys#additional-faq-and-answers

**Comment by Alastowor** [comment]
Aw okay. So since I can't find any sort of AutoHotKey script or any program to use; how would I go on about remapping this key? AutoHotKey documentation doesn't tell me anything.

**Comment by randyrants** [comment]
Not up to me: it's a limitation of Windows, which is what is doing the remapping.  While I can record a triple-byte key easily enough, there's no way to get it to remap.  Sorry!
