### ISSUE TITLE
Key remapping doesnt work

### ISSUE THREAD

**Issue by Banananass** [randyrants/sharpkeys#207]
I tried to remap next track to num-6 but it doesnt work. I restartet the system twice but it still doesnt work on deezer (desktop app) and vlc media player.

**Comment by randyrants** [comment]
If the key was successfully remapped by Windows it would work everywhere; are you saying it doesn't work anywhere or just not in these two apps?

**Comment by Banananass** [comment]
It doesnt work at all

**Comment by randyrants** [comment]
Then I've no idea.  The key is pretty standard so maybe the keyboard is doing something weird with it.  Might want to try another re-mapper and see if that can help.
