### ISSUE TITLE
Remapping pause/break key does not work

### ISSUE THREAD

**Issue by Kroesss** [randyrants/sharpkeys#208]
I'm trying to bring back the end-key on my new laptop, because Asus decided it was no longer needed, and put the on/off-button on that place.

The key I use the less (read: never) is the pause/break-key. I tried remapping it with sharpkeys, but this is not working as expected. The problem lies with the "from key". The "To key" is working fine.

First I tried the type key-function. When I hit the pause/break it tells me it received "Special: Num Lock 00_45". When I save it, and log off and on again, the actual num lock-key is remapped, and the pause/break is not. Then I manually selected "Special: Break (E0_46)" from the list, but this doesn't have an effect on the pause/break-key. Are there any other keys I should try? E.g. some of the unknown ones?

**Comment by randyrants** [comment]
Not much I can offer for this one: Pause/Break is a strange key because it's not always the same key, especially on laptops.  If Break from the list didn't work you might want to try something more active like AutoHotkey or another remapper.
