### ISSUE TITLE
CapsLock disable no longer working and can't re-disable it

### ISSUE THREAD

**Issue by greenbergman** [randyrants/sharpkeys#21]
I've had SharpKeys working forever to disable the hated CapsLock key, but it just stopped working. When I try to re-disable it, I get an error "Unhandled exception has occurred in your application. If you click.... Access to the registry key 'HKEY_LOCAL_MACHINES\System\CurrentControlSet\Control\Keyboard Layout' is denied."

I tried clicking Continue, which just gave me an hourglass. And I tried rebooting.

Clues? Suggestions?

![sharpkeys error](https://user-images.githubusercontent.com/20523366/27565148-62fca210-5aaa-11e7-9a1b-0aa831bf2857.jpg)

**Comment by randyrants** [comment]
If I had to guess, you aren't running it as an Administrator.  Right click on the icon and select Run as Administrator.

**Comment by greenbergman** [comment]
That indeed fixed it! (Though I don't know what caused it to stop working in the first place.)

Thank you being so responsive - and for providing this great piece of software.

David

**Comment by randyrants** [comment]
Anytime!
