### ISSUE TITLE
How to map my useless media keys to brightness control?

### ISSUE THREAD

**Issue by andrewlin0410** [randyrants/sharpkeys#210]
These keys do not need Fn to be presses to trigger. But I can't find brightness keys in the TO list. Also, I need to press Fn + up or down to control brightness and the program does not recognize these 2 actions. Thanks in advance!

**Comment by randyrants** [comment]
Fn + any key will change the entire key's function.  For example, on a Surface keyboard F9 shares a physical key with Home, but as far as Windows is concerned, F9 is one key and Home is another: Fn sends the correct scancodes accordingly which is completely different than Shift or Alt.  Shift+A sends the same scancode as A.

Brightness - as it controls hardware - very likely doesn't send the scancode on to Windows.  You can try Type Key and see if a valid code comes up - just remember to use the Fn key to send the codes for brightness.
