### ISSUE TITLE
Mapping to F24 key is detected as UNDEFINED

### ISSUE THREAD

**Issue by sandorex** [randyrants/sharpkeys#211]
I mapped my caps lock to F24 and when i try it in an application it detects UNDEFINED something

if you need some log or something ill add it

**Comment by sandorex** [comment]
F23, F22 work fine so i guess F24 is the problem

**Comment by randyrants** [comment]
Please see this post w/r/t F24.  It's trickier than it should be.
https://github.com/randyrants/sharpkeys/issues/158
