### ISSUE TITLE
New Microsoft Ergo keyboard has new key codes

### ISSUE THREAD

**Issue by amp64** [randyrants/sharpkeys#212]
Office key is E0_205B, and this needs remapping urgently!
Calc is 00_100
Snip is E0_5B? (reported as Left Windows??)
Task is E0_5B?
Lock is E0_5B?
Search is 00_36 (reported as Right Shift??)

**Comment by amp64** [comment]
I tried just adding
`            m_hashKeys.Add("E0_205B", "Special: Office");`
then remapping the Office key to "nothing", but it did not work.

**Comment by amp64** [comment]
Now I read the whole FAQ I guess the Office key cannot be remapped, and Calc is "special" using the catch-all.

**Comment by randyrants** [comment]
Neither can the new Office key: it's triple byte which is not supported by the remapping tech that Windows is from the Registry.  Before the new key was in place, Ctrl+Alt+Shift+Win would generate the E0_205B scancode that the Office app looks for.
