### ISSUE TITLE
Add Keys!!!

### ISSUE THREAD

**Issue by CandyMan962** [randyrants/sharpkeys#214]
![image](https://user-images.githubusercontent.com/56931063/67414126-d6421580-f598-11e9-9fca-f276b5078e67.png)
![image](https://user-images.githubusercontent.com/56931063/67414190-f540a780-f598-11e9-82ce-dacd65f10294.png)

**Comment by CandyMan962** [comment]
all multimidia keys have this number!!! (sorry for my english)

**Comment by randyrants** [comment]
Per the FAQ: 00_100 is a catch all code that Windows reports when a key is captured by hardware or some other driver so there's no way to successfully remap that key, especially since multiple keys can return the same 00_100 code.

https://github.com/randyrants/sharpkeys#additional-faq-and-answers
