### ISSUE TITLE
Surface Pro 7 Type Cover Keys not shown in Sharp Keys

### ISSUE THREAD

**Issue by BillD64** [randyrants/sharpkeys#215]
Downloaded Sharp Keys to my Surface Pro 7 and when the file opened there were no keys shown.

**Comment by randyrants** [comment]
SharpKeys would always start with no mapped keys since there are very likely no keys remapped the first time you run the app.  Not sure what keys are expected to be there...

**Comment by BillD64** [comment]
So where do I start to get the original key mapping? I need to change one of the keys on the new version of the standard surface Pro type cover.

**Comment by randyrants** [comment]
Let try this a different way: what key are you trying to remap and to what?
