### ISSUE TITLE
Reset to default

### ISSUE THREAD

**Issue by CTH999** [randyrants/sharpkeys#216]
I can't find a way to reset all of my keybinds (all 1/2 of them) to factory default (F10 is putting "`p" instead of doing, you know, F10 stuff), but I undid the other half of my keybind…

What I am asking is:

A. How can I reset it now (I couldn't find anything), and, while I am good, I'm not great, so, step by step?

B. Add a Wiki (The GitHub one) article on how to reverse it

C. add a feature that will do A automaticly (You hit it, and it checks what's there, what the default is, and it re-writes the keymaps to reset it. It also will show you what it did, so you can save it)

Just some questions and suggestions!

**Comment by randyrants** [comment]
If you remapped keys with SharpKeys, open the app, click Delete All, Write to Registry, reboot.

**Comment by CTH999** [comment]
Well, thanks! I did that, and checked, and it didin't seem that way... guess F10 has another use, eh?

Well, thank you!
