### ISSUE TITLE
calculator key kill

### ISSUE THREAD

**Issue by kabuki969** [randyrants/sharpkeys#217]
Hi and thank you for your amazing work! I have an AmazonBasics USB keyboard (model number KU-0833) and I'd like to be able to disable the built-in calculator key.  Your app doesn't recognize the key (it gives the generic 00_100 code).  Any assistance would be most appreciated!

Thank you~

**Comment by jsheffers** [comment]
I know this is a generic error, but do you have any recommendations for tracking down how to stop these calculator keys from triggering (a different application)?  I'm curious as to how Windows knows which application to open if it isn't available at the registry level...

**Comment by randyrants** [comment]
You'd have to find something at the driver level.  My app doesn't do anything but post to the screen what Windows sees the key as, so it's going to have to be an active remapper like AutoHotKeys or an updated/hookable driver.
