### ISSUE TITLE
FN key not registring when i tap it.

### ISSUE THREAD

**Issue by Dorolk** [randyrants/sharpkeys#219]
Trying to rekey my Fn key at the bottom of my keyboard.
But whe i tap it sharpkey doesn't register it so i can't remap it. 

Am i blind?

**Comment by randyrants** [comment]
Not blind, but Fn is often unmappable.

Per the FAQ: https://github.com/randyrants/sharpkeys#additional-faq-and-answers 
Q: Why can't I remap my Fn key on my [notebook or Apple] keyboard?
A: Some keys simply just never get to Windows. In the case of most Fn keys, they are interpretted by the hardware and never get passed onto the OS, no matter how they appear to work... if Windows doesn't see the key, there's no way for the key to be remapped by Windows.
