### ISSUE TITLE
Euro and dollar keys won't detect

### ISSUE THREAD

**Issue by PiotrGrochowski** [randyrants/sharpkeys#22]
I have euro and dollar (€ and $) keys on my laptop, above the left and right arrows. However, I can't map them to left and right itself, as "Type Key" won't even detect them.

**Comment by randyrants** [comment]
What kind of keyboard is this and are each of these symbols their own keys?  I've never seen either as a standalone key which makes me think that the keyboard has created something custom that Windows doesn't know about.

**Comment by PiotrGrochowski** [comment]
Keyboard in a Packard Bell laptop (EasyNote TE). They have their own keys that type € and $. They won't work with shift.

**Comment by randyrants** [comment]
Sorry - no idea.  I've never seen a notebook with a dedicated key for Euro and $ - if Type Key doesn't see them then Windows isn't getting them so they can't be remapped.
