### ISSUE TITLE
Is their support for the £ symbol on a US keyboard?

### ISSUE THREAD

**Issue by cclambie** [randyrants/sharpkeys#221]

**Comment by randyrants** [comment]
Not that I'm aware of, or at least not for a regular key.  I'm pretty sure that even if you hooked up a UK keyboard to a PC running US English, you won't get a £ symbol even thought the keyboard says you should.  The PC would need to be using en-GB for that to work.

**Comment by cclambie** [comment]
That is correct randyrants. No £ on a US keyboard - even when the actually keyboard has the £ on it... as mine does.
I want to add that key, that is the idea anyway, hence trying sharpkeys. 
However I cannot find the way to enter it on a computer without that key.
I am sure it is possible. It is an ASCII symbol.
https://www.ascii-code.com/ 
Symbol 
DEC: 163
OCT: 243
HEX: A3
BIN: 10100011
HTML No: &#163;
HTML Name: &pound;

Thoughts?
