### ISSUE TITLE
sharpkey not working

### ISSUE THREAD

**Issue by frake17** [randyrants/sharpkeys#222]
i have used sharpkey for months, i remapped my esc key with my numpad 0 key. It worked for quite a few months but suddenly stopped working, and no matter what i rebind my esc key to it won't work. I tried rebinding o and p to each other and it worked, so only my esc key isn't being remapped. Is there a solution for this?

**Comment by randyrants** [comment]
None that I'm aware of: did you change Windows versions or something else on the machine that might have changed?  It would be weird for Windows to suddenly stop supporting something without something else changing it.
