### ISSUE TITLE
Office key and Emoji keys are not recognized

### ISSUE THREAD

**Issue by SanderBouwhuis** [randyrants/sharpkeys#224]
Dear Randy Rants,

I bought a new keyboard and it (unfortunately) comes with an 'office' key and an 'emoji' key. When I try to disable either of them SharpKeys comes with the message that the keys are not known yet and that I should go to the website.
Is there something I can do to 'add' them to your list?
Or maybe add them manually myself?

**Comment by randyrants** [comment]
Sadly, I cannot do a thing with either one.  Both keys are triple-byte which Windows (who does the remapping) does not remap.  I've been aware of the Office key for a while but quickly learned that it's code (E0205B) couldn't be remapped to or from any other key using this tech.

No idea what the Emoji key is but I'm 97% certain it will also be triple-byte.
