### ISSUE TITLE
german Apple Extended Keyboard II on uKey adb-usb adapter (DE-DE)

### ISSUE THREAD

**Issue by kls0e** [randyrants/sharpkeys#225]
Hi!
I appreciate sharpkeys, it is excellent! Thanks!

I am trying to remap my AKEII to be usable under a windows 10 environment. 

However,
    the = key on the numpad does not work
    the < > key (lower left) gives ^ °
    the ^ ° key (upper left) does nothing

I would like to be able to use < > of course. When I map the key according to the screenshot, it does not type < > although after logging in again sharpkeys recognizes it as such with 'type key'.

Do I have to map the key to a different char?

Kindly
Matthias

![Anmerkung 2019-12-14 065909](https://user-images.githubusercontent.com/33416529/70844315-9d5b4a00-1e3f-11ea-9e91-7bf88753fcc1.png)

Picture of keyboard available [here](https://github.com/tmk/tmk_keyboard/issues/35#issuecomment-339941093)

**Comment by randyrants** [comment]
I cannot speak to the German aspect of they keys as I've never used one.  What I do know is that if the ^ ° key showed up as 00_29, this got saved this to the Registry, and then rebooted, the key should be remapped.  If by upper/lower you meant shift then that might be working as expected: the whole key gets remapped rather than just a shifted key.

**Comment by suse1016** [comment]
The special key for < and > isn't working. You can select the < key instead and then it should work properly (> aswell).
I attach my setting, try it out  and let me know whether it worked
![sharp](https://user-images.githubusercontent.com/35639693/71548974-554b3400-29b6-11ea-9a99-94645f660b41.PNG)

**Comment by kls0e** [comment]
>>>> excellent. Thank you <<<<

**Comment by kls0e** [comment]
For the record: Instead of E0_56, one should use 00_56 and <>| works as expected.
