### ISSUE TITLE
Unknown keys: AmazonBasics BT Keyboard

### ISSUE THREAD

**Issue by jpool-cf** [randyrants/sharpkeys#227]
First off, this app is great!

I have this keyboard for my living room setup (Windows 10):
https://smile.amazon.com/amazonbasics-bluetooth-keyboard-iphone-black/dp/b005eowbke

Unfortunately the 3 bottom keys next to the space bar (home, back/undo, search) are unknown to SharpKeys (all register as 00_100).

Ideally I'm looking to map the home key to be the Windows key, and just disable the other two. 

Any pointers on how I could go about editing the registry to accomplish this?

Thanks!

**Comment by randyrants** [comment]
Sadly, any key that shows up as 00_100 means that it is being treated by hardware and not sent to Windows, which also means it cannot be remapped.

https://github.com/randyrants/sharpkeys#additional-faq-and-answers has more information on this.
