### ISSUE TITLE
Changing Ctrl to Alt key not work

### ISSUE THREAD

**Issue by noni-mizu** [randyrants/sharpkeys#228]
I tried changing my left Ctrl key to my left Alt key, but it's not working. When I try to use Alt+C for copy and Alt+V for paste, nothing happens. I tried using the old assignments and it seems the Ctrl key is disabled now. Any idea why? I have Windows 10 Home.

**Comment by randyrants** [comment]
Can you paste an image of your UX at this point?  Also, please remember that you have to reboot after writing changes to the Registry for the remapping to take effect.

**Comment by suse1016** [comment]
Try to not type the key on the keyboard, choose the key in the list instead.
Post your key settings here if you want, or try to make it like this:
![sharp](https://user-images.githubusercontent.com/35639693/71548988-90e5fe00-29b6-11ea-8646-8de87f1518de.PNG)
