### ISSUE TITLE
App hangs on Windows 10

### ISSUE THREAD

**Issue by wjohnsto** [randyrants/sharpkeys#229]
I'm currently running Windows 10 Pro 1909 (build 18363.535). It seems that SharpKeys no longer works for me. When I start the app it just sits in the taskbar and the UI never loads. Perhaps something has happened to my registry keys and it is causing the app to hang?

Has anyone run into this issue before? Are there specific registry keys I can clear out to get this back in working order?

Any help is appreciated, thanks!

2019-12-31 UPDATE: I cloned the repository to see if there is an issue found when I run the app through Visual Studio... no success. I will continue to play around and see if there is something I can do to fix it.

UPDATE 2: After commenting things out trying to track down where the issue is in the source code, the app started working again. Here are the steps I went through right before the app started working:

1. Commenting out the binding of the Dialog_Main_Load event handler (line 413) allowed the UI to load (but obviously the settings didn't load), so I un-commented the line and dove into the method
2. Commenting out the call to BuildParseTables (line 1121) ended up with a null string error in the LoadRegistrySettings method, which seemed as odd. I proceeded to un-commented the line
3. Commenting out the call to LoadRegistrySettings allowed the UI to start, but without the settings

Once I performed the 3 steps above, and then un-commented LoadRegistrySettings the app began to work again... I will wait for @randyrants to weigh-in before I close this issue out.

**Comment by brunomuratore** [comment]
+1 to @wjohnsto 
I was having the same issue. App suddenly stopped loading on Windows 10, but after commenting and un-commenting LoadRegistrySettings it started working again.

**Comment by randyrants** [comment]
Well, given that the file in question hasn't changed in 11 months, not sure what exactly is happening on these two computers, especially without knowing what specific line is failing.  The method that you're commenting out has three basic functions:
- Restore window size, position, and state from a past save or using defaults (can be ignored)
- Show the welcome message box on first run (can be ignored)
- Load the current remapped keys (if ignored, any new mapping will stomp on the existing one).

**Comment by brunomuratore** [comment]
There is no exception or error I could see. Apparently some variable is being set incorrectly that is later used to load the UI, causing it to not load. If you have any idea on how to debug this I can try it next time it happens.

**Comment by wjohnsto** [comment]
Now that I know the issue, I can try to dive a little deeper when it comes up again.
