### ISSUE TITLE
Samusung EE-BT550

### ISSUE THREAD

**Issue by JeanClaudeMerlot** [randyrants/sharpkeys#23]
Hello, 

I have got the BT-Keybord EE BT550 from Samsung and want to use it with WIN10.
Unfortunatily the keybord does not have a esc-key. Other than that it is very good! 

Sharpkeys does not support its keys. 

When I press the top-left key, that I want to become my ESC, Sharpkeys reads (00_100), but then tells me, that this key is not supported. 

Any chances, that you might include these keys?

**Comment by randyrants** [comment]
More than likely Samsung is doing something in the hardware that is preventing a proper code from getting to Windows.  Same is true for custom keyboards that are used on laptops.
