### ISSUE TITLE
Potential Issue With Windows 10

### ISSUE THREAD

**Issue by Rainbow-Thunder** [randyrants/sharpkeys#230]
Hey - I don't really understand what has gone on myself so I'm sorry if this isn't explained well. 

I downloaded the program yesterday and used it earlier today to switch some keys around. Upon restarting my system, it hung for a while (20 mins or so) on "preparing windows" and upon loading it seems to have either corrupted my user account or tried to wipe my files. 

My desktop and all my settings seem to have been restored to factory settings for the most part - but my downloaded programs were still available. None of my folders nor my saved files were immediately visible, so I did some digging and eventually found them under the desktop option on the "This PC" file. However not all of my files were there. 

I'm still trying to figure out that extent of the damage, but it's big enough that I think it's potentially a problem. I didn't do anything else with the computer that day so I can only conclude it's this program.

**Comment by randyrants** [comment]
Sorry to say, but your conclusion is likely incorrect, give what this app is and does.

The app is a very basic Windows forms based .NET application that doesn't do anything but read/write to a Registry key that Windows uses to remap the keys.  It doesn't change the OS or OS files in any way.  

If I had to guess, Windows Update updated something quietly and when you rebooted, those changes forced an upgrade and/or you hit a long standing bug where Windows opted to not load your existing profile, resulting in the default state you saw.
