### ISSUE TITLE
Possible to modify numlock-mode key maps?

### ISSUE THREAD

**Issue by RheingoldRiver** [randyrants/sharpkeys#232]
My new Lenovo laptop doesn't have numlock or a number pad on top of some of the letters on the keyboard. I figure I can rebind some key I don't care about to numlock, but can I bind e.g. R [in numlock mode only] to 7, etc?

**Comment by randyrants** [comment]
Not with the Registry key that Windows uses: that remaps a whole key at any given time, regardless of any modifier keys (Caps Lock, Shift, Alt, Ctrl, etc.).

Might want to look into something like AutoHotKeys which is an active remapper.

**Comment by RheingoldRiver** [comment]
Ok, yeah I use AHK for some other things, I'll check that out for this. Thanks for the answer! (and also for the utility ofc, it's kept capslock rebound to ctrl for me for over a decade now)
