### ISSUE TITLE
Key mapping

### ISSUE THREAD

**Issue by Hanzlah744** [randyrants/sharpkeys#233]
So basically my keyboard was messed up my arrow keys were my wasd and my wasd were arrow keys so then I downloaded sharpkeys to remap my keys then I realised I can just do FN and w but What I didnt realise is that now my down arrow is S and my S is still S I tried doing FN and w to switch it back to arrow keys are wasd and so on but now its just the same

**Comment by randyrants** [comment]
Is there a question in there for SharpKeys?  It's almost sounding like you might have turned on a Fn-Lock which SharpKeys wouldn't help with, or something?

**Comment by SumatraPeter** [comment]
@Hanzlah744: To reset to defaults all you need to do is delete all active key mappings in SharpKeys, then save and reboot. After that if anything is still messed up it's no longer the program's fault, and you'll need to undo whatever you did via FN or whatever.
