### ISSUE TITLE
How to remap combined keys like mapping Ctrl-Space to Win-Space?

### ISSUE THREAD

**Issue by Zhou-Heng** [randyrants/sharpkeys#236]
How to remap combined keys, say, from Ctrl-Space to Win-Space?

**Comment by Zhou-Heng** [comment]
@randyrants: You don't need to answer this question now, neither do you need to add this functionality if it does not exist, because I have chosen to use ATNSOFT Key manager.

Delete this ticket.

**Comment by randyrants** [comment]
No worries, it's something that SharpKeys cannot help with: Windows only remaps whole keys and not combination keys.
