### ISSUE TITLE
System Model	HP EliteBook 830 G6 Keys not recognised

### ISSUE THREAD

**Issue by chris-ayers-uk** [randyrants/sharpkeys#237]
Hi,

I have a new System Mode HP EliteBook 830 G6 that offers some new keys that are recognised by sharpkeys, but not able to be mapped:

Phone Down   E0_1F65  
Screen             E0_1FD6
Calculator        E0_1F64

(Phone up does not get captured in your program)

![image](https://user-images.githubusercontent.com/59657493/72434895-a9b32980-3794-11ea-82fe-fed70c1deb89.png)

**Comment by randyrants** [comment]
Hi,

All three are triple-byte scan codes which are not remappable by Windows.  The FAQ has more information: https://github.com/randyrants/sharpkeys#additional-faq-and-answers

Thanks!
