### ISSUE TITLE
Cannot map Pause / Break key

### ISSUE THREAD

**Issue by svnpenn** [randyrants/sharpkeys#24]
Pause/Break key is not listed in the From or To key lists.

If you try the "Type Key" option, it thinks you have pressed Num Lock and maps Num Lock instead

http://stackoverflow.com/questions/38846347/what-is-the-scancode-of-pause-break-key

**Comment by svnpenn** [comment]
https://github.com/carlin-q-scott/browser-media-keys/issues/86

**Comment by randyrants** [comment]
It's not listed because - if I remember correctly - it's a triple byte key which doesn't lend itself to remapping and it's normally not passed to Windows directly.  Not much I can do with that.

**Comment by svnpenn** [comment]
https://github.com/carlin-q-scott/browser-media-players/issues/2
