### ISSUE TITLE
Unable to map a key

### ISSUE THREAD

**Issue by klimkin** [randyrants/sharpkeys#240]
On HP laptop, I am trying to map a "Hang Up" key. The app detects the code "E0_1F65", but than it says the code is unknown.

**Comment by randyrants** [comment]
Sorry, it's not supported.  From the FAQ:

**Q: Type a Key shows a code that is E0_nnnn - can I remap this key?**
A: If a scancode has 6 numbers, then it is what is known as a triple byte scancode which is something that cannot be remapped by the Windows Registry. To remap a key like this, you'll need an active remapper like AutoHotKeys or the app that came with the keyboard (e.g. Logitech's Options) if available.
Via: https://github.com/randyrants/sharpkeys#additional-faq-and-answers

Plus these other posts, https://github.com/randyrants/sharpkeys/issues?q=is%3Aissue+E0_1F65+is%3Aclosed
