### ISSUE TITLE
registers wrong key input?

### ISSUE THREAD

**Issue by prosodyspeaks** [randyrants/sharpkeys#243]
hi, i'm trying to remap the pause/break key to media play pause, https://w3c.github.io/uievents/tools/key-event-viewer.html reads this key as 'pause' with a keycode '19', but sharpkeys registers it as 'numlock'.... any ideas?

**Comment by randyrants** [comment]
Well, it's not that SharpKeys registers it as NumLock - it's that Windows sees it as NumLock.  In this SharpKeys is just returning what Windows is reports it as.

**Comment by prosodyspeaks** [comment]
well, no, it doesn't. clearly. because the linked keyboard scanner correctly receives it as pause, while sharpkeys receives it as numlock.

also, autohotkeys did perfectly well at remapping it by calling the 'pause' key.

sorry, that sounds hostile, i just noticed that you are in fact the developer, so firstly, thanks very much for all your hard work! but yeah, SK (and only SK) is not receiving this key correctly.

**Comment by randyrants** [comment]
I find that using the word "clearly" are often pointing out something that is not clear.

AutoHotKeys is an application that uses it's own lower level hooks to grab keys and then stays running - as an app or a service - to remap the keys themselves.  SharpKeys is reporting whatever Windows is telling it and then drops that data into a Registry key for Windows to remap the key if it can.  So, if Windows says it's NumLock then SharpKeys likely will as well.

Sorry I couldn't be of more help and glad the rest of the app is working!

**Comment by prosodyspeaks** [comment]
thanks for responding, but windows can't be registering the key as numlock because it doesn't toggle numlock, but (before autohotkey remap) function perfectly normally as pause/break - it is only sharpkeys that misinterperets it.

but anyway, ahk sorted it for me, i was just trying to let you know about a bug.
