### ISSUE TITLE
How to remap CapsLock to change keyboard layout (Grave Accent) on German kbd?

### ISSUE THREAD

**Issue by Dabbrivia** [randyrants/sharpkeys#244]
Windows 10 allows single key "Grave Accent" (`) to be used to switch between input languages. What I would like to achieve is to use CapsLock to do just that. However I can't find the proper code to enter. 
I have IBM Lenovo Yoga V4 with German IBM Keyboard configured as the main keyboard layout in case that matters https://help.keyman.com/keyboard/german_ibm/1.0/german_ibm
For CapsLock I can use 00_3A but I just cant find what key or code corresponds to the grave accent as Windows need it? 
Using your "Type Key" my grave accent key is shown as +(00_0D). If I map CapsLock to it that works like backtick (´) though.
Interesting enough, german ö Key:  ; : (00_27) seems to work like grave accent to switch to alternative keyboard layout. But it was unintended and the problem with that (apart from hijacking a letter key) is that it doesn't work to switch back. My understanding is that in the alternative keyboard layout that key has yet a different mapping.

**Comment by Dabbrivia** [comment]
Not really the solution to this issue specific to sharpkeys but I was able to achieve just what I wanted with http://haali.net/winutils/ lswitch.exe . There is the source coude available as well so maybe that helps http://haali.net/winutils/lswitch.c

**Comment by Dabbrivia** [comment]
I have found another bit of information that might be helpful here https://superuser.com/a/873013/499386

**Comment by randyrants** [comment]
HTH!
