### ISSUE TITLE
remapping not working?

### ISSUE THREAD

**Issue by lusarusrex** [randyrants/sharpkeys#246]
hello,
i downloaded sharpkeys 3.9.0 because i have a few keys that need remapping as a result of them not working anymore. Specifically, i am remapping: 'tab' to 'page up' ; 'a' to 'Left Shift' ; '1!' to 'num 1' ; and ' `~ ' to 'Enter (E0-1C)'
No matter what I try the keys do not remap. I made sure to restart the laptop after writing the changes to registry. Still nothing.
I can't afford a new laptop anytime soon, so this app is a saving grace if i can get it to work. My laptop is Windows 10 and has a num pad section that im remapping some keys to.

**Comment by lluke777** [comment]
First try previous version of SharpKeys then try other app that puts remapping to registry for ex KeyTweak. If it won't work it means that is problem at OS level.

**Comment by randyrants** [comment]
Other versions of SharpKeys likely won't matter - the remapping code hasn't changed for a decade or so, even while being in open source.  There's no much more you can fix in there :)

That said, trying another Registry remapping app would confirm if it's OS level or not.  And if it is, AutoHotKeys is a way to go.

**Comment by quiquefernandez** [comment]
> First try previous version of SharpKeys then try other app that puts remapping to registry for ex KeyTweak. If it won't work it means that is problem at OS level.

I had exactly the same problem using win10, after rebooting the system the changes were not applied. I tried with a different software (KeyTweak) and it worked for me. 

I therefore do not have the problem anymore, but I hope my insight helps fixing issue.

Best.

**Comment by sungit2g** [comment]
actually found the solution just click "Delete All" then click the "Write to Registry" it should fix it

**Comment by Doubledealer** [comment]
@sungit2g is correct as I had the same issue and it was fixed when I deleted all the key maps (so sharpkeys was empty). However, I think it was because I had powertoys installed as well using the same key maps so my keyboard just ended up being the same (ctrl would be remapped to alt for example but then remapped back to ctrl). After uninstalling powertoys it's now working as intended.

Funny thing is I got sharpkeys because powertoys doesn't work for video games (tested powertoys in dota 2 and no luck). However, after installing sharpkeys, powertoys appears to be working for video games now...
Regardless, I'll keep sharpkeys as it does what I want and uninstall powertoys.

**Comment by FrancisLydz1321** [comment]
I lab you sharpkeys MWA!

**Comment by mardan-shah** [comment]
> Do the keys that you are trying to remap normally work? If those keys have stopped working altogether (at a hardware level) then its unlikely that you can remap them.

Im trying to map forward slash to my right crtl button i never use it and forward slash is the only button not working.  Remapping it would save me the repair cost to change a keyboard on my laptop. but no it just isnt working for me

**Comment by DreymaR** [comment]
> > Do the keys that you are trying to remap normally work? If those keys have stopped working altogether (at a hardware level) then its unlikely that you can remap them.
> 
> Im trying to map forward slash to my right crtl button i never use it and forward slash is the only button not working. Remapping it would save me the repair cost to change a keyboard on my laptop. but no it just isnt working for me

You don't give us a lot of information to work with. The best answer I can give you at present is therefore: You're probably doing it wrong. Sorry.
