### ISSUE TITLE
Issue with remapping on special code on windows 10

### ISSUE THREAD

**Issue by VoilierBleu** [randyrants/sharpkeys#247]
Hi,

i use sharpkey to remap the Supprt key to F2 key (and don't ask me why). Works perfectly fine under Windows 7 and 8 on two différents computer (HP and Asus). But not on Windows 10 Lenovo.

I've try all version of Sharkey, also with windows visual keyboard, definitively not working.

But what i've done is a direct export of scan code registry on my working system + reimport on the Windows 10 : et voilà : it's work.

Please find attached bot file. Maybe it could help other people with similar way.

Voilier.

[Suppr on F2, Win 10 KO.reg.txt](https://github.com/randyrants/sharpkeys/files/4272181/Suppr.on.F2.Win.10.KO.reg.txt)
[Suppr on F2, Win8 OK.reg.txt](https://github.com/randyrants/sharpkeys/files/4272182/Suppr.on.F2.Win8.OK.reg.txt)

**Comment by randyrants** [comment]
Well, something is flipping your scan code around but I cannot begin to guess as to what is doing that.  That said, if you have the Win8 reg key value exported, just import that into Windows 10.  Should work without an issue.

**Comment by MysticJay** [comment]
Hi,
what about some special Keys I get from my Cherry Keyboard?
usually they open Apps or interact with the browser or Media Player.
One of which has scan code 183.
M.
