### ISSUE TITLE
sharpkeys not showing its window

### ISSUE THREAD

**Issue by yubaoquan** [randyrants/sharpkeys#248]
I don't know the exact reason, maybe it is related to a recently update of my system.

**Expect**: Open sharpkeys, the software window shows in screen.
**Current**: Only the sharpkeys icon is showing in Quick Launch bar, and nothing happens when click on it.
 
**System**: win10

**Comment by randyrants** [comment]
Sounds like it might be getting installed off screen somewhere.

Open the Registry, Navigate to HKEY_CURRENT_USER\Software\RandyRants, delete the SharpKeys Key and start SharpKeys again.  In terms of Windows position, it should be reset now.

**Comment by yubaoquan** [comment]
It works! Thank you!
