### ISSUE TITLE
Does not remap to the specific key I was looking to use...

### ISSUE THREAD

**Issue by Beeblebrox666** [randyrants/sharpkeys#250]
This app is great, I wanted to use the scroll lock key to change how excel works, remapped it to the insert key which I never use. The other key I specifically wanted to use is the PAUSE key. it is present on the on screen keyboard but that is in the way for slideshows. Laptops don't have a pause key and it is not listed in your app. clicking type key does not help either as it is not in the list...can you fix this???

**Comment by randyrants** [comment]
Pause is a key that is not easily remapped, mostly because it doesn't ever seem to be the same keycode twice.  On a recent keyboard, it showed up as Num_Lock.  On others I've seen it show up as Break, regardless of whether or not Pause/Break is on the same key.

Not much I can do with that, sorry.
