### ISSUE TITLE
Omen Key Remapping April 2020

### ISSUE THREAD

**Issue by hamjakl** [randyrants/sharpkeys#252]
Please add the virtual/artificial LShift key (scancode: e0 2a, known from the KeyHistory). I have found no solution to replace the Omen key to the Home key. This is really frustrating. Please help..

Also, after messing around with the registory, the artificial scancode does not appear now, when the Omen key is pressed.

**Comment by randyrants** [comment]
Added to the list.  No idea when it'll be recompiled though.
