### ISSUE TITLE
AltGr works

### ISSUE THREAD

**Issue by royalrex** [randyrants/sharpkeys#254]
Just wanted to let you know that Alt+Gr remapping works.

Thank you for a great app! I prefer SharpKeys over AutoHotKeys because its a more permanent solution. But must admit that I know use AutoHotKeys because I needed more advanced remapping capabilities.

Specifically needed Alt+; to æ, Alt+' to ø, and Alt + [ to å

Weird scandinavians 😄

**Comment by randyrants** [comment]
It's not that: Windows only allows whole keys to be remapped, so there's not that I can do to enable a modified key to be remapped :(
