### ISSUE TITLE
Volume up and down key?

### ISSUE THREAD

**Issue by riccardosimo** [randyrants/sharpkeys#255]
Hi there :D first of all thank you for this awesome tool <3
I was looking for the volume up and down fuction but in the list doesn't exist 🤔 i'd like to increase or decrease the main windows 10 volume with 2 keys but i'm not finding the volume voice (only mute)

**Comment by randyrants** [comment]
Check under Media: in the list - there is a Volume Up/Down listed there that might work for you.  The tricky part with some of these types of keys is that they are often hardware based rather than software based, which means the machine takes action on the key press and doesn't send it to Windows.
