### ISSUE TITLE
keys acting like they were never remapped 

### ISSUE THREAD

**Issue by SupimX** [randyrants/sharpkeys#257]
so rn i tried setting 7 keys (basic}   stuff like from number 9 to letter p (p isnt working so im sacrificing the top numbers and using the numpad instead copy and paste is great} something like that 
and so i did and restarted my laptop and its like i did absolutely nothing  all numbers are not remapped and theres a scancode map in the regedit keyboard layouts so idk 

this used to work years ago

**Comment by randyrants** [comment]
Curious: there's no limit to the amount of keys that could be remapped so I don't think that's a problem but can you try one key, reboot, and see if it remaps?  Also which version of Windows is on your PC?

**Comment by SupimX** [comment]
I'm windows 10... But I did manage to get it working I had tried the one key thing a while back didn't work so I went to registry deleted the scancode map and tried again.. Surprisingly it worked perfectly
