### ISSUE TITLE
Sharpkeys issue

### ISSUE THREAD

**Issue by lesny1** [randyrants/sharpkeys#259]
Hello, I tried to change [left windows] key to [left alt] key. After doing this I lost my [left windows] key, now I have two[left alt] keys. It seems like I didnt change the keys but I lost my [ left windows key] to have two "[left alt keys]". I tried to "delete", "delete all", delete the app and nothing. Now when i try to select [left alt] key or [left windows] key in app Sharpkeys dont see the keys. He see only [right windows] key, no [alt] keys. Can someone help me? Thank you

**Comment by randyrants** [comment]
I'm not sure what you're trying to do, but if you map the Left Windows key to Left Alt, then that key will act like Alt going forward.  That's what the remapping is supposed to do.

If you delete all of the mappings, make sure you save it to the Registry and reboot, before expecting the remapping to be removed.
