### ISSUE TITLE
Mapping to F24 key is detected as undefined

### ISSUE THREAD

**Issue by Fxxkable** [randyrants/sharpkeys#260]
The correct one for **F24** is **E0_76**. #211 #158
Reference here [USB HID to PS/2 Scan Code Translation Table](https://download.microsoft.com/download/1/6/1/161ba512-40e2-4cc9-843a-923143f3456c/translate.pdf)

**Comment by randyrants** [comment]
It's not a clear cut as that.  The initial ask for F24 came in for the IBM Model F keyboard, code 00_6F.  No idea what other keyboards are calling for F24 - as F23 is 00_6E - but E0_76 is in the list of available keys, just labelled as unknown.  It can be remapped the same as anything else, if someone wants to try it.
