### ISSUE TITLE
Unknown Key E0_205B

### ISSUE THREAD

**Issue by ajkelsey** [randyrants/sharpkeys#264]
Hello. I have a Microsoft keyboard with a MS Office shortcut key. When typed in SharpKeys, it is mapped to E0_205B and is returned as unknown. I would love to remap this key because I always hit it by mistake and open Office.

**Comment by randyrants** [comment]
Sorry: Windows does not remap triple byte scancodes.

https://github.com/randyrants/sharpkeys#additional-faq-and-answers for more.
