### ISSUE TITLE
Can the "dead" key be remapped

### ISSUE THREAD

**Issue by sanderboele** [randyrants/sharpkeys#266]
I'd like to be able to map the dead key (https://en.wikipedia.org/wiki/Dead_key) to CapsLock. Is this possible?

**Comment by randyrants** [comment]
If you mean the combo key, no: entire keys are remapped when using this Windows hack.

If you mean Ctrl or AltGr, yes, those are supported if you want to remap the whole key.

**Comment by sanderboele** [comment]
then I guess it's not possible. Thanks anyway!!!
