### ISSUE TITLE
Unknown Keys

### ISSUE THREAD

**Issue by igorky** [randyrants/sharpkeys#268]
Tried to remap three keys on hp laptop, but SharpKeys doesn't know about those.
Screen share = E0_1F6D
Hang up call = E0_1F65
Answer call = doesn't show code, but I tried different program to read the code

![image](https://user-images.githubusercontent.com/540312/81579300-a0685100-9371-11ea-9087-04ef010be4ec.png)

**Comment by igorky** [comment]
Here is the photo how it looks 

![image](https://user-images.githubusercontent.com/540312/81579549-ecb39100-9371-11ea-902a-88b07c88d091.png)

**Comment by randyrants** [comment]
Sorry: Windows does not remap triple byte scancodes.

https://github.com/randyrants/sharpkeys#additional-faq-and-answers for more.
