### ISSUE TITLE
Scroll lock key seen as num lock

### ISSUE THREAD

**Issue by ken-list** [randyrants/sharpkeys#269]
I tried to map the scroll lock key in Windows 10 to media volume up, but it recognizes the scroll lock key as the num lock key. Also don't see scroll lock in the choice of keps to map.

**Comment by GittyAub** [comment]
Hello Ken-list,

It's usually (unless you remapped it with this or another tool) 0x00000046

SharpKeys "drops" all but two leading "just zeros" after the z, so you'd normally see in Sharpkeys :
Special: Scroll Lock (00 _ 46)

If for a weird reason, "SK" would not auto-categorize your Scroll Lock input key it might show :
Unknown: 0x0046 (00 _ 46)

Hope that helps you or another reader if you figured it out.
