### ISSUE TITLE
AltGr keys

### ISSUE THREAD

**Issue by lu8aja** [randyrants/sharpkeys#270]
Hello, it seems the remapper does not recognize the combinations of AltGr+letters
Like
E0_1F2E = AltGr + c
E0_1F2A = AltGr + Shift + C
E0_1F1B = AltGr + ~

All these in a standard latpop keyboard (latinamerican layout).

Is it possible to use these at all? or is it a limitation of the trick being used?
THANKS in advance!

**Comment by randyrants** [comment]
Sorry but Windows does not support combo-key selections or triple-byte scancodes.  Please see https://github.com/randyrants/sharpkeys#things-that-sharpkeys-will-not-do for more.
