### ISSUE TITLE
Remap Backslash Key

### ISSUE THREAD

**Issue by PeleWest** [randyrants/sharpkeys#271]
### I am using Sharpkeys to make the Print Screen key action Backslash and Bar \ | when pressed. I do not see this in the list of keys and typing the key does not work.

Please, how is this achieved?

**Comment by randyrants** [comment]
Print Screen is a nasty bit of work.  If I remember correctly, it's either a triple-byte code or it doesn't come in through the normal Windows keyboard handler as it's treated as a "copy screen to clipboard" command.  It's why it's not in the list.

**Comment by PeleWest** [comment]
Thank you for writing. Apologies, I don't think I explained the problem
correctly.

The Print Screen key is on the list as a Special key. I cannot find the
Backslash Bar \| key anywhere in the list.

I am able to change the keyboard so that pressing Print Screen emulates other
keys, for example the Applications key, but I can't make it generate a
Backslash. On my keyboard Printscreen is the left most key on the Number
Row, then Backslash, then all the numbers. I would like to be able to
move evrything one key to the left so that Backslash is at the left end
of the row and the numbers are in the correct position when touch typing.

**Comment by randyrants** [comment]
No worries - sorry for not getting it.  It's under "Key: \ | (00_2B)" if you're looking for it by hand.

Print Screen is hard to remap per the above, but the \ | key is like any other.

**Comment by PeleWest** [comment]
Hi

Thanks again for writing. I am afraid when I map "002B" it maps Print
Screen to Hash #.

**Comment by randyrants** [comment]
That sounds odd.  Is it a en-US keyboard?

**Comment by PeleWest** [comment]
It is a Uk keyboard

**Comment by randyrants** [comment]
Sadly, this is getting out side of what I've been able to successfully test, as I don't have access to UK hardware, but I do know that \ | may not be representative on other keyboards.  I mean on the ja-JP keyboard, \ id on one key and | is somewhere else.

I would try using the scan codes that Type Key reports back and give it a go.  I also know that PowerToys recently enabled their key remapping feature, if you wanted to give it a go.

**Comment by PeleWest** [comment]
Thanks. I will give it a go

**Comment by PeleWest** [comment]
Hi Again

I have managed to crack it. 

In case you are interested, I mapped the Print Screen key "E037" to
Backslash using Iso Extra Key "0056".

**Comment by randyrants** [comment]
Nice!

**Comment by yeatersink** [comment]
greetings @randyrants  I am a blind user and attempting to remap the "Print Screen" key on my new ASUS Rog. I would like to use your app to remap the print screen button to the applications key. I am using the latest version of Windows 11. I cannot seem to find a "print screen" in your app nor will the "type key" function locate it. 

Can you help?

**Comment by vishalnandagopal** [comment]
@yeatersink, I am using Windows 11 and "Print screen" is coming as a special key under E0_37.

However, it doesn't come when I type the key like you said.
