### ISSUE TITLE
Multiple keys are undefined 

### ISSUE THREAD

**Issue by bityob** [randyrants/sharpkeys#272]
I have some special keys that I want to remap, 

but when trying to use the "Type key" feature, it doesn't find it and give them the same value.

Examples - 

* Open calculator (Windows key code 183 in PassMark KeyboardTest, "Launch application" in carnac)

![image](https://user-images.githubusercontent.com/20026896/82838276-613f1180-9ed4-11ea-936c-14ea16a44e55.png)

* Play/Pause button 

Not even detected by the app (not detected with PassMark KeyboardTest too)

![image](https://user-images.githubusercontent.com/20026896/82839694-e298a300-9ed8-11ea-9d00-06190237c437.png)

* Mute/Volume down/Volume Up (Windows key code 173, 174 and 175)

Same as "Open calculator" key (Launch application)

![image](https://user-images.githubusercontent.com/20026896/82839734-065be900-9ed9-11ea-858d-ac7ecc325ea0.png)

**Comment by randyrants** [comment]
These keys are not remappable by Windows as 00_100 is a catch all.

Please see https://github.com/randyrants/sharpkeys/blob/master/README.md#additional-faq-and-answers for more information.
