### ISSUE TITLE
Remap AltGr + "."

### ISSUE THREAD

**Issue by ldlx** [randyrants/sharpkeys#273]
I use German keyboard layout, but on my US-style keyboard is missing the key between Left Shift and US-"Z", where greater than/less than/pipe character sits in German layout. So I tried to remap the chars to the keys of the US keyboard, but with Right Alt modificator.

Sharpkeys gives an error that it does not know the key "(E0_1F34)" when I press Alt + "." to register the shortcut.

**Comment by randyrants** [comment]
Remapping combo keys are not supported by Windows remapping technology nor is a triple-byte code. 

https://github.com/randyrants/sharpkeys/blob/master/README.md#additional-faq-and-answers for more.
