### ISSUE TITLE
Cant remap function keys on DELL keyboard

### ISSUE THREAD

**Issue by Kars1090** [randyrants/sharpkeys#276]
Like the title says. When i try to map function keys on a dell keyboard, it says SharpKeys doesn't know the key and asks me to update it.

![image](https://user-images.githubusercontent.com/4224674/83341214-0006ac00-a2e1-11ea-90b7-21d9c57320b9.png)

![image](https://user-images.githubusercontent.com/4224674/83341209-faa96180-a2e0-11ea-96a3-c01aaf03d5c0.png)

**Comment by Kars1090** [comment]
Could you perhaps fix or implement this? It would be a great help to me :D

**Comment by randyrants** [comment]
Sorry: 00_100 means that the hardware is telling Windows that it doesn't have a unique scancode it can send it, so it cannot be remapped.

Please see https://github.com/randyrants/sharpkeys#additional-faq-and-answers for more.
