### ISSUE TITLE
Special: Num Lock (00_45)

### ISSUE THREAD

**Issue by DevelAx** [randyrants/sharpkeys#278]
![image](https://user-images.githubusercontent.com/13222593/83794308-7ff89180-a6a6-11ea-8604-507f88b23032.png)

I'm trying to remap the <kbd>Pause/Break</kbd> button, which is detected as **Special: Num Lock (00_45)** when I type it in the "Type Key" dialog.  Then app then says:

![image](https://user-images.githubusercontent.com/13222593/83794583-e4b3ec00-a6a6-11ea-8e3f-39dd5928842e.png)

When I try to select manually **Break (E0_46)**  - it doesn't work (physical <kbd>Pause/Break</kbd> button is not remapped).

**Comment by randyrants** [comment]
Pause/Break is a tricky thing because it's two keys on one key and Pause is often trapped by the OS or hardware which doesn't get to Windows.

Please see https://github.com/randyrants/sharpkeys#additional-faq-and-answers for more.
