### ISSUE TITLE
Unknown key combination

### ISSUE THREAD

**Issue by PhoenixWyllow** [randyrants/sharpkeys#279]
![video/gif of steps taken](https://user-images.githubusercontent.com/54237626/83943641-0c699800-a7fe-11ea-8839-4925053a45ac.gif)
I'm using an Italian keyboard.
The combination I typed was `AltGr + '` with the objective of remapping it to the character \`
I'm also hoping to do the same for `AltGr + ì` into \~ (I'm using ALT codes to type them here)
I'm already using the latest available release.

**Comment by randyrants** [comment]
Two problems here: one is that Windows remapping doesn't support combination keys and the other is that even if it did because AltGr is special, it doesn't support triple-byte codes.

Please see https://github.com/randyrants/sharpkeys#additional-faq-and-answers for more.
