### ISSUE TITLE
Microsoft Eronomic Keyboard Office Key Support

### ISSUE THREAD

**Issue by jaketaylorpro** [randyrants/sharpkeys#280]
When I try to remap the office key like so:

![image](https://user-images.githubusercontent.com/1290909/84087106-724d4f80-a9b7-11ea-9235-6bfd964028a9.png)

I get this error:

![image](https://user-images.githubusercontent.com/1290909/84087195-9c067680-a9b7-11ea-9e19-d6d1d5a1ed05.png)

What will it take to override this key's default behavior?

**Comment by randyrants** [comment]
The Office key is a triple-byte enabled key and cannot be remapped by this bit of Windows tech.

Please see https://github.com/randyrants/sharpkeys#additional-faq-and-answers for more.
