### ISSUE TITLE
Remapping Apple wireless keyboard to Windows 10

### ISSUE THREAD

**Issue by MacDog** [randyrants/sharpkeys#287]
I am using an Apple wireless keyboard on Windows 10. The Apple "Delete" key works as a "Backspace" key in Windows. But there is no way to get the Windows "Delete" key (Forward Delete) working.

Using Sharpkeys, one needs to identify as existing key to remap it. 

Is there a way I can identify the eject key or one of the other F keys (or another key) and then find enter the registry code to do the Windows delete function?

I also would like to do some other things, such as "End" and "Home" -- are there instructions for this?

Thanks for any guidance.

**Comment by randyrants** [comment]
Has to be the whole key - not modified keys - and Fn has a mind of it's own.  Might want to try the PowerToys which has a more active remapper.  https://github.com/randyrants/sharpkeys#additional-faq-and-answers
