### ISSUE TITLE
Remap $ to £ on US keyboard

### ISSUE THREAD

**Issue by dafunkphenomenon** [randyrants/sharpkeys#288]
Hi

I have a US keyboard and am trying to map $ (shift + F4) to UK pound but I don't see the key in the list or know which key combination I can use to bring it up.

Can it be done?

Thanks

**Comment by misterfoo** [comment]
I think you may want to investigate Keyboard Layouts for this. I'm not well-versed in this topic but I think we're talking about two different things: keystrokes (which SharpKeys deals with), and characters (the actual letters/symbols that are generated by some keystrokes). I believe the majority of currency symbols have no "standard" keystroke but can be mapped in your keyboard layout. Take a look at this article and see if it helps: [How to Create a Custom Keyboard Layout on Windows](https://www.makeuseof.com/tag/create-custom-keyboard-layout-windows/)

**Comment by randyrants** [comment]
Also, it's not supported by the remapping tech built into Windows: https://github.com/randyrants/sharpkeys#additional-faq-and-answers
