### ISSUE TITLE
Remap command to control in Windows Server 2012 R2 Standard

### ISSUE THREAD

**Issue by plug-city** [randyrants/sharpkeys#29]
Has anyone been able to remap the control to command on an Apple Keyboard on a VPS?

I am not having any luck doing this.

<img width="755" alt="screen shot 2017-08-01 at 2 52 44 pm" src="https://user-images.githubusercontent.com/30635146/28841738-21e2d99e-76c9-11e7-8dea-81990c8d7b5a.png">

**Comment by randyrants** [comment]
Top of my head, it would depend on what Windows things those buttons are.  I know I've flipped Alt and Windows on a Powerbook years ago, but I can't remember what the Windows codes are.
