### ISSUE TITLE
Windows key not found

### ISSUE THREAD

**Issue by YayLolz** [randyrants/sharpkeys#290]
I downloaded this in order to try and fix a problem by remapping my key, but it says the key is not found.
![image](https://user-images.githubusercontent.com/67490116/85910799-3de3eb00-b821-11ea-9c6c-e5ea4b8cfa4d.png)
The key I pressed is my CTRL key.
When I press it outside of the program, it tries opening an .mp3 file, but when I open it, it opens Groove Music (Windows 10)
But no file plays. I've already tried about anything you can find on the internet, but nothing fixed it. Uninstalling Groove Music made it open Windows Media Player instead, and uninstalling that made it ask me what program to use to open the .mp3

This is really annoying because well... CTRL.
Any help is appreciated, I know this isn't technically about this program but I can't find any help anywhere else

**Comment by delfaaan** [comment]
Same problem, I used a keyboard that have a function of opening a default browser on Windows 10.

Can't remap.

Error:
You've entered a key that SharpKeys doesn't know about.

Please check the SharpKeys website for an updated release.

![SharpKeys error](https://user-images.githubusercontent.com/16264678/86325288-02ef1680-bc6a-11ea-8e13-8be76bc5a0bd.PNG)

Please update regarding the error.

**Comment by randyrants** [comment]
Different problems.

@YayLolz  - I'll need more information about what you mapped because I know of no "default" Windows layout where CTRL launches Groove.

@delfaaan - that's a non-standard key.  Please see https://github.com/randyrants/sharpkeys#additional-faq-and-answers for more information.
