### ISSUE TITLE
To map E0_1F29 to pipe symbol

### ISSUE THREAD

**Issue by robkam** [randyrants/sharpkeys#291]
When I try to use SharpKeys to remap the broken bar ¦ symbol instead to the pipe | symbol. I get "Error: You've entered a key that SharpKeys doesn't know about. Please check the SharpKeys website for an updated release."
![1](https://user-images.githubusercontent.com/4047844/86588407-8ae36200-bf83-11ea-8f76-14849e4a4414.png)
![2](https://user-images.githubusercontent.com/4047844/86588421-8f0f7f80-bf83-11ea-89b8-08112e4f6a86.png)

**Comment by randyrants** [comment]
Sorry - not supported: https://github.com/randyrants/sharpkeys#additional-faq-and-answers
