### ISSUE TITLE
Keys after remap do not working

### ISSUE THREAD

**Issue by shoaibnrbg** [randyrants/sharpkeys#292]
I installed the Sharpkeys app at first time and also remapped a key from Backspace to End key, Fortunately that worked too. But after that i again remapped Backspace key to RIght Ctrl key and hit restarted, but this time it is not working anymore. I reinstalled the app and did same again but not working yet. How can i solve it? Please help me because my Backspace key does not work.

**Comment by randyrants** [comment]
Sorry but it's not clear as to what's not working: if you remapped the Backspace key to be Right Ctrl and expect Backspace to still work.... it's been remapped to Right Ctrl so it's not going to work.

To restore your keyboard to the "non-mapped state" remove all of the SharpKeys entries, write it to the Registry and reboot.
