### ISSUE TITLE
Mapping conflict between two keyboards

### ISSUE THREAD

**Issue by augratin** [randyrants/sharpkeys#294]
A few months ago I got a small keyboard to use along with my main keyboard (image below). I frequently use a lot of special symbols like greek letters, degree symbol, etc.  It was my intention to remap the keys on this 2nd keyboard to those special symbols so I wouldn't have to call up the character map every time I wanted to type degrees or make the fraction 'one-half'.

Most of you can probably figure out what happened next. I tried a simple mapping of a->b for the second keyboard, but it affected the main keyboard as well. Is it even possible to connect two keyboards and remap the second to a totally new set of characters?  I guess what I am looking for is a keyboard that is completely blank and has no preset mapping, allowing me to assign completely new mapping to each key as needed.
![IMG_0259](https://user-images.githubusercontent.com/68468740/87854022-dd842d00-c938-11ea-82c8-bd004105716e.JPG)

**Comment by tambi-soft** [comment]
As SharpKeys works with Windows-Registry-Settings, the main Question is: Can Windows handle multiple keyboards (simulatiously) differently?

My experience with windows is: No it can't. It can (or at least could for a long time) not even handle the Capslock/Numlock keys on different Keyboards independently.

**Comment by tambi-soft** [comment]
In the hope of not offending the Author with this recommendation: Maybe keyman (https://keyman.com) is more the tool you are looking for: It allows you to change the keyboard-layout quickly on the fly.

**Comment by randyrants** [comment]
Correct, Windows remapping tech only supports remapping at the computer level, which means that all of the keyboards connected to the PC will be remapped the same way.  Except the onscreen keyboard.

@tambi-soft no worries here!  I have a few different packages in my own FAQ for people that are looking for something that SharpKeys can't do or if they like them better.  It's all good.

**Comment by augratin** [comment]
> "I guess what I am looking for is a keyboard that is completely blank and has no preset mapping, allowing me to assign completely new mapping to each key as needed."
> That's not how it works: A keyboard is sending keycodes (an individual number for each key) to the Operating System. It is the job of the Operating System (in your case probably Windows) to decide what to do with this information (probably send a character to the current application according to your preset keyboard-layout & language, do a system-call, or whatever).
> 
> As SharpKeys works with Windows-Registry-Settings, the main Question is: Can Windows handle multiple keyboards (simultaniously) differently?
> 
> My experience with windows is: No it can't. It can (or at least could for a long time) not even handle the Capslock/Numlock keys on different Keyboards independently.

In that case I guess I need a keyboard that is programmable all on its own, or talks to the o/s via its own driver.
