### ISSUE TITLE
das keyboard professional media keys

### ISSUE THREAD

**Issue by giffysquid** [randyrants/sharpkeys#295]
I apologize if this has already been addressed, but, when I attempt to map one of the media keys for the das keyboard professional 4, I get a message that I pressed "00_100," that I have entered a key that SharpKeys doesn't know about and to check the website for an updated release. I am using version 3.9.2. Is this something that SharpKeys isn't able to handle or am I doing something wrong? Thanks for the help

**Comment by randyrants** [comment]
"00_100 is a catch all code that Windows reports when a key is captured by hardware or some other driver so there's no way to successfully remap that key, especially since multiple keys can return the same 00_100 code." via https://github.com/randyrants/sharpkeys#additional-faq-and-answers
