### ISSUE TITLE
Deleted Disabled Key - cannot recover

### ISSUE THREAD

**Issue by Arkundar** [randyrants/sharpkeys#298]
Hi there,

After creating a disabled key, I deleted the entry and overwrote to the registry by mistake.

Now I don't know how to recover this key as it was.
It is the Tilde ~ key (left of the numeric row). 
When I try to select this key and revert it back to stock mapping, 
SharpKeys tells me (obviously) that this key is Disabled 00_00 and won't replace it to its original value.

**Comment by randyrants** [comment]
You can always select a key from the list (which won't care if it's Disabled or not) or remove all of the key remappings, save, and reboot.
