### ISSUE TITLE
readme fix 

### ISSUE THREAD

**Issue by Senpaiyaa** [randyrants/sharpkeys#299]
Hi there @randyrants I'm new here on the github community and just wanted to ask if you're still accepting pull requests with the readme file? I'm not a developer or anything but this is my way of saying thanks at least because you just save my life. Was having issues with my laptop keyboard recently but SharpKeys solved the problem. Saved me time and money because of this life saver tool you made. I'm just glad I found you here! 

It's nothing special though just a fix I made for the readme file. 

Thank you very much for this tool! 😄

**Comment by randyrants** [comment]
Thanks!
