### ISSUE TITLE
Winders Key?

### ISSUE THREAD

**Issue by MikRedmond** [randyrants/sharpkeys#3]
I can't seem to find the Windows key in the "To" column.  Am I short on coffee or is there something else I need to understand.  It worked before Microsoft shoved the Creators Edition onto my machine....  Try to go back to remap and can't find that Winders key.  Ideas?

**Comment by randyrants** [comment]
It's there, in the Special section: Left Windows and Right Windows.

**Comment by MikRedmond** [comment]
Thank you 
Thank you 
Thank you 
Thank you !!!  I forgot there is more than one .....

**Comment by randyrants** [comment]
No worries!
