### ISSUE TITLE
Mapping doesn't work with chrome browser

### ISSUE THREAD

**Issue by kemppare** [randyrants/sharpkeys#302]
Hi,

I have a German keyboard and would like to change the mapping of z and y to make it 'normal' Scandinavian layout. I tested that the remapping works fine with all other software but Chrome browser doesn't recognize the mapping configured in sharpkeys but behaves as if there wasn't any remapping done. 

Is there a way to make Chrome to support sharpkeys?

**Comment by randyrants** [comment]
That would be up to Chrome and specifically why it's not allowing Windows to remap keys.  My app just changes the Registry so Windows can remap the keys.
