### ISSUE TITLE
Please add Pause / Break to be re-mappable

### ISSUE THREAD

**Issue by Papoulka** [randyrants/sharpkeys#305]
User Vitox on StackOverflow (below) shows how to modify the SharpKeys source code to do this very simply, but... my last compilations were 8080 assembler so I'm too rusty.  And clearly I'm not the only one who would appreciate it.

Thanks for the nice util.

https://stackoverflow.com/questions/38846347/what-is-the-scancode-of-pause-break-key

**Comment by randyrants** [comment]
Thanks.

I read through the OP and then the comments and even went into the pages that they pulled information from.  As near as I can tell, there are at least three different scan codes for Pause/Break that came from three different keyboards, which makes it hard to add to the program.  I mean one guy was saying "Oh just use the first two bytes from the three byte code" but that doesn't work.  Most triple byte scan codes start with E0; in his example of Pause/Break it was E1 which I've never even seen before.

In terms of adding a new key, it's much easier than anything assembly had: just need to add a new entry to Dialog_Main.cs and compile it with any version of Visual Studio.  Maybe even Visual Studio Code, which is free.

**Comment by Papoulka** [comment]
Thanks for taking the time to look into this.  Not as simple as it seemed.  Maybe I'll give it a go in the source code as you described.

papoulka@fastmail.fm
