### ISSUE TITLE
Arrow Keys to [AltGR]+[key]

### ISSUE THREAD

**Issue by LondoJI** [randyrants/sharpkeys#306]
Hi! I'm facing a little problem.

All arrow keys from my keyboard got damaged and unusable, so I'd like to remap them to W,A,S,D or perhaps to I,J,K.L.
In all cases they're combined with AltGr. These are the Scan Codes Sharpkeys found:

"Arrow Up: (E0_48)" --> "ALtGr+W: (E0_1F11)" -- or --> "ALtGr+I: (E0_1F17)"
"Arrow Down: (E0_50)" --> "ALtGr+S: (E0_1F1F)" -- or --> to "ALtGr+K: (E0_1F25)"
"Arrow Left: (E0_4B)" --> "ALtGr+A: (E0_1F1E)" -- or --> "ALtGr+J: (E0_1F24)"
"Arrow Right: (E0_4D)" --> "ALtGr+D: (E0_1F20)" -- or --> "ALtGr+L: (E0_1F26)"

In all of these cases, when I press "OK", there's a message telling that I've entered a key that is unknown for SharpKeys and suggest me to check for a newer version of the app. However, I´m using Sharpkeys 3.9.2.

Is there a way to fix, or edit key assignments from this point?
Thanks in advance!

**Comment by randyrants** [comment]
Completely unsupported, per the FAQ: https://github.com/randyrants/sharpkeys#additional-faq-and-answers

That said, you might want to give Power Toys from Microsoft a shot: they have a more active remapper thank what Windows provides.
