### ISSUE TITLE
Mapping Alt keys on Surface 7 pro not working

### ISSUE THREAD

**Issue by GamaEuler** [randyrants/sharpkeys#307]
I am trying to map the right Alt key to the left Alt key so I can recreate the layout I was having on my mac when using LaTex.  Unfortunately, the left Alt key is not in the list of keys when I used the Surface Pro 7.  Weirdly, the key IS in the list when I'm using my other Windows PC.  Any solution ?

**Comment by SeanDunford** [comment]
I'm experiencing this with an Apple Keyboard on a Mac Mini as well.

**Comment by randyrants** [comment]
![image](https://user-images.githubusercontent.com/18704482/94302327-e721a680-ff20-11ea-97d1-b672d8f16672.png)

**Comment by randyrants** [comment]
Please re-open this issue if the remapping doesn't work.  Thanks!
