### ISSUE TITLE
Alt+Gr key remapping not working on Logitech MX Keys keyboard

### ISSUE THREAD

**Issue by c2h50h** [randyrants/sharpkeys#308]
I was trying to map combination of `AltGr + /` (what finally returns code E0_1F35)
![image](https://user-images.githubusercontent.com/8616480/92234678-c088c680-eeb2-11ea-876d-507d99c47859.png)
to another key `\`, but in the end i receive error message:
![image](https://user-images.githubusercontent.com/8616480/92234784-ef06a180-eeb2-11ea-942b-5296b91e8d42.png)

**Comment by randyrants** [comment]
Combination of keys are not supported.  You can remap Alt-Gr but not Alt-Gr+something else.  Additionally, triple byte codes are also not remappable by Windows, which is what this tool uses.

Please check the FAQ https://github.com/randyrants/sharpkeys#additional-faq-and-answers for more information.
