### ISSUE TITLE
Why not support map multiple key presses to one key?

### ISSUE THREAD

**Issue by rodrigolopezguerra** [randyrants/sharpkeys#309]
Map multiple key presses to one key - e.g. it will not support an attempt to remap Ctrl+C to the F5 key.

Just wondering why. I was lokking to remap win key to win+s . Thanks for this great app

**Comment by randyrants** [comment]
Because it's not supported by the tech that's remapping the keystrokes doesn't support it.  The main page + FAQ has more about this.
