### ISSUE TITLE
Mapping using ALT GR doesn't work

### ISSUE THREAD

**Issue by sebastianhatt** [randyrants/sharpkeys#310]

**Comment by sebastianhatt** [comment]
SharpKeys recognizes the scan codes for ALT GR + [any key], but I get the error message: "You've entered a key that SharpKeys doesn't know about. Please check the SharpKeys website for an update."

When choosing "OK" in 'the "add" window, the key mapping listed has the wrong scan codes, i.e. not the ones that SharpKeys found when listening for a key press.

**Comment by twirley** [comment]
I think I want to write about the same issues...

I switched from qwertz to qwerty - but still need to write at times german letters.
I can do that, by using altgr + certain characters - but they are strangely chosen.
I want to switch altgr + p (which results in ö in US intl Layout) to altgr + o - which would make more sense to me for having the character ö...

But as I understand, sharp keys won't be able to help with pressing multiple buttons at the same time?

**Comment by randyrants** [comment]
For both issues posted here, twirley is correct: SharpKeys does not re-map combo keys because Windows doesn't support it via this Registry key.  That said, the PowerToys collection from Microsoft includes a keyboard remapper that will support this.
