### ISSUE TITLE
Doesn't work for some applications

### ISSUE THREAD

**Issue by ichirou2910** [randyrants/sharpkeys#312]
Hi, thanks for the app. So I use it to swap Caps Lock and Escape. But some apps (like games) still use the unmapped keys, e.g when I press Escape, it results in both Escape and Caps Lock being pressed. The image below is my settings.
![image](https://user-images.githubusercontent.com/51302893/93665637-d9ee4e80-fa2c-11ea-9bcf-bd913c6bbcbe.png)
Am I doing wrong anywhere? Would like to know your thought.

**Comment by randyrants** [comment]
Sorry for the issue with this but it's somewhat out of my control: SharpKeys exposes a registry setting that Windows uses to remap keys.  What sometimes happens - especially with older/low level apps or games - the app running doesn't use the Windows input stack, so Windows doesn't get a chance to remap it.  This is very common with games where it's doing it's own thing.

That said you might want to try PowerToys from Microsoft: it's a more active remapper that may jump in front of the game input stack and remap successfully.
