### ISSUE TITLE
MS Office key remap

### ISSUE THREAD

**Issue by h67ma** [randyrants/sharpkeys#313]
Is it possible to add support for "MS Office key" remapping? It can be found on some Microsoft keyboards near right alt. Key code is E0_205B, which Sharpkeys says it doesn't know about. The key is pretty useless and sometimes I accidentally press it when I want to press alt.

**Comment by randyrants** [comment]
Sadly, I cannot.  Triple-byte codes aren't supported by the Windows remapped.  I tried this out well before it shipped - the combo for older keyboards is CTRL+ALT+SHIFT+WIN which generates the same scan code.  Just can't do anything with it.

That said, PowerToys by Microsoft should be able to help. Please check the FAQ for more: https://github.com/randyrants/sharpkeys#additional-faq-and-answers

**Comment by h67ma** [comment]
Thank you for speedy reply!

Unfortunately PowerToys doesn't work for this case either. The problem is that all four are modifier keys, and PowerToys requires an "action key" (a letter for example) in addition to modifier keys. Also it allows a maximum of 2 modifier keys :/

The best I could achieve is to remap left windows (part of the four key combo) to undefined, but then left windows stops working (obviously). Even then, the weird Office key still acts as shift and ctrl, so pressing it by accident still produces unintended big letters and accidental shortcuts. I'm wondering who thought putting this key near alt was a good idea.

Anyway, I think it would be good if Sharpkeys had a special message for a case when it detects a combo and not a single key, including an information that combos can't be remapped.

Cheers.

**Comment by randyrants** [comment]
What you're seeing is a triple-byte code, which flat out do not work.  That there's a keyboard combo that also triggers it is unique to the Office key.  For example the emoji key sends something that SharpKeys doesn't even see.  Likewise, combo keys - e.g. Ctrl+C - does not show up as a combo key at all.  Add to that all of the FAQ's that are on this page, my web site, the FaceBook page, and included in the install package, I think that's as far as I'm willing to go.

Of course, this is why the app is on GitHub: someone else can extend it if they want to.

Lastly, if you must remap that key, I again recommend PowerToys.  Or the keyboard and mouse center app that you can get for Microsoft keyboards as that may have remapping tech at the driver level.

**Comment by h67ma** [comment]
Microsoft's own keyboard app only allows remapping a handful of keys, and Office key is not one of them. And like I said before, I don't think this can be done with PowerToys either (at least I don't know how to do it). I finally managed to get it working using AutoHotkey.

Again, thank you for your help. Next time I'll read FAQ before asking questions ;)
