### ISSUE TITLE
HP EliteBook 840 G6 keys

### ISSUE THREAD

**Issue by depablo** [randyrants/sharpkeys#315]
Hi,

I am using laptop which does not have Insert key. Instead of there are three additional keys (right from F12).
Presentation
Answer call
Stop call

Please refer to:
https://www.myfixguide.com/store/media/catalog/product/cache/1/thumbnail/800x/cbd2aed9bfabff0c0533b9abe88bc5e9/k/e/keyboard-for-elitebook-840-g6.jpg

I wanted to use your application to map one of these keys to Insert key, but I couldn't.

This is what your application says:
Presentation key responses with E0_1F6D code
Answer call: no code
Stop call: E0_1F65

Do you think is it possible to add support for these keys to your application?

Thanks.

**Comment by randyrants** [comment]
Those are triple-byte codes and cannot be remapped by Windows, per FAQ #6 and #8 here: https://github.com/randyrants/sharpkeys#additional-faq-and-answers 

Please give Microsoft PowerToys or AutoHotKeys a look: they are more active in their remapping tech.
