### ISSUE TITLE
Pause/Break key won't remap

### ISSUE THREAD

**Issue by guidonero** [randyrants/sharpkeys#316]
On Dell SK-8115 USB keyboard the Pause/Break key will not remap.
Scan code (00_45) "Special: Num Lock" is displayed after pressing the "Type key" button on the SharpKeys app.
Per the "From key" listing, I also tried mapping this key as the "Special: Break (E0_46)" which also did not work.
Is it possible this is a non-programmable key having a more complex scan code?

**Comment by randyrants** [comment]
Hard to know for sure: it could be a software key but it's sending a strange scancode or it could be a hardware key and it's not coming to Windows.  Pause/Break is a strange key like that.

If SharpKeys does not work, give Microsoft PowerToys or AutoHotKey a try.  Their remapping tech is a lot more active than Windows.

**Comment by macruspareto** [comment]
Hi everyone!

I've come across this thread for the same reason (to remap the Pause-Break key). :}

One guy has posted his solution regarding Sharpkeys on Stackoverflow, as I quote:

> I downloaded the source code of SharpKeys, and added to its code, file Dialog_Main.cs, method BuildParseTables(), the line m_hashKeys.Add("E1_1D", "-by Vitox: Pause/Break");

> After that, I was able to remap the Pause/Break key flawlessly.

You might want to look it up:
https://stackoverflow.com/questions/38846347/what-is-the-scancode-of-pause-break-key

So, would it be possible for you to incorporate this patch into your source? That would be terrific!

**Comment by randyrants** [comment]
Sadly, no: E1_1D is not a valid key and he might want to do some more testing because E1 1D is the first part of what is a hextuple-byte scancode - E1 1D 45 E1 9D C5 - which cannot be remapped using the Windows technology that SharpKeys exposes.  Windows doesn't even want to remap triple-byte codes, which leaves out a bunch of keys.

Basically, Vitox might be remapping way more keys than just Pause.  

Incidentally break is still available in the list as that is a unique and double-byte scancode.

**Comment by tiencoffee** [comment]
> Đáng buồn thay, không: E1_1D không phải là một khóa hợp lệ và anh ấy có thể muốn thực hiện một số thử nghiệm nữa vì E1 1D là phần đầu tiên của mã quét byte hextuple là gì - E1 1D 45 E1 9D C5 - không thể ánh xạ lại bằng công nghệ Windows mà SharpKeys tiết lộ. Windows thậm chí không muốn ánh xạ lại các mã ba byte, điều này để lại một loạt các khóa.
> 
> Về cơ bản, Vitox có thể đang ánh xạ lại nhiều phím hơn là chỉ Tạm dừng.
> 
> Ngẫu nhiên phá vỡ vẫn có sẵn trong danh sách vì đó là một mã quét byte kép và duy nhất.

That's right, when I map the Pause/Break key with the code E1_1D it does both the key I set and the Numlock key
