### ISSUE TITLE
Media hotkeys don't work after installing

### ISSUE THREAD

**Issue by techismagic** [randyrants/sharpkeys#317]
i have an Asus laptop (X556UV), and after installing this program, the media controls hotkeys (fn+arrows - play, pause, skip, etc.) have stopped working. now they work only when in the app.

i tried uninstalling the app, restarting the PC, and nothing worked. the only way they work now is when the the Sharpkeys program is open with the window selected.

**Comment by randyrants** [comment]
As SharpKeys is not doing any remapping on it's own - the app exposes a Registry Key that Windows uses to remap keys - so my overarching advice is to remove all the mappings, save to the Registry, and reboot.  That should put the machine back to it's default state.

Why this is an issue, I can only guess: something like the driver that handles the media keys is unhappy with Windows trying to remap keys?  You might want to try AutoHotKeys or Microsoft's PowerToys as they remap keys differently and might not cause an issue.
