### ISSUE TITLE
Unknown key

### ISSUE THREAD

**Issue by dmcrider** [randyrants/sharpkeys#318]
Trying to remap the browser button on my CyberPowerPC Gaming Keyboard. When I click the Type Key button and hit the key, the resulting code is 00_100 and when I click OK I get a message that I've entered a key SharpKeys doesn't know about.

Screenshots:
![unknown_key](https://user-images.githubusercontent.com/9904609/96927736-5a5d0080-146c-11eb-9c51-c6546774ffb9.JPG)
![key_code](https://user-images.githubusercontent.com/9904609/96927740-5af59700-146c-11eb-839e-5494a26f08e4.JPG)

**Comment by randyrants** [comment]
Curious: saw the reply in the FAQ?

**Comment by dmcrider** [comment]
Yeah, I probably should have read that first :P

**Comment by randyrants** [comment]
No worries!  Was more curious if you found a workaround or not.

**Comment by dmcrider** [comment]
The PowerToys keyboard remapper shows it as BROWSER_HOME but that didn't
work with my AutoHotKey script. Was hoping your program could provide more
insight, but unfortunately not.
