### ISSUE TITLE
Remapping to a function key adds a c at the end

### ISSUE THREAD

**Issue by jonathanya0** [randyrants/sharpkeys#319]
I'm remapping a key on my keyboard (E0_5B). It says Special: Left Windows, however that's not actually what the key does. According to the manufacturer, it's supposed to open cortana; however, I have cortana disabled, so the key is quite useless right now. I want to map it to a function key, so that I can use it as a keybind in games. It does map it to the function key, but it also adds a c input as well. The function key output will go off as well as typing the letter c. It does the same thing for all the function keys 1-24.

**Comment by jonathanya0** [comment]
Can I remap this key at all? The shortcut for opening cortana is win + c, I don't know if sharpkeys can map that since it's more than one. Are there any alternative programs I can use?

**Comment by randyrants** [comment]
Never seen a Cortana key before.  It sounds like it's telling Windows it's a Win key press which means that if you remap it, it will map this key and the regular Windows key - no way for Windows to tell the difference.

Might want to try Microsoft PowerToys or AutoHotKeys - they are more active remappers.
