### ISSUE TITLE
Multiple Keyboards and remapping

### ISSUE THREAD

**Issue by AdamM72** [randyrants/sharpkeys#32]
Is this possible for a single keyboard on a 2 keyboard computer? For example, I have a normal keyboard that I don’t want to remap and a small USB numberpad keyboard that I want to customize for a special purpose, remapping the keys only on that keyboard.

**Comment by AdamM72** [comment]
I have found a solution, albeit not as neat as I’d like – remapper (http://www.2112design.com/blog/multi-keyboard-remapper/)

**Comment by randyrants** [comment]
Anything that touches the Registry key that Windows uses to remap keys requires a user to sign out/in; I've seen that go wonky which is why I recommend a reboot.  Glad you found something that works!

**Comment by HarryCGoldberg** [comment]
This would be a great feature!  Going to try what was suggested.
