### ISSUE TITLE
Remapping partially working

### ISSUE THREAD

**Issue by Mphoenix65** [randyrants/sharpkeys#321]
Hey,

I recently downloaded sharpkeys in the hopes that I could swap my fn and left control keys around. I did two seperate mappings, from lft ctrl to fn, and another from fn to lft ctrl. It partially worked, however I noticed that I cannot copy and paste using ctrl c or v even though my lft ctrl should be mapped. I also cannot hit ctrl alt dlt from my lft ctrl either. These are the only things that I have noticed in the two minute that I have used sharpkeys. It does work in games though so it's not as though it doesnt work at all. I was wondering if I could get any support on this.

Another thing I wanted to ask is if there was any way I could test if the rebinds had worked using sharpkeys itself instead of having to load up a game or try to copy and paste something. Maybe an area in which if u press a button it gives you feedback as to which output/s were connected to that button.

Thanks.

**Comment by randyrants** [comment]
I'm not sure there's much else I can do to call out that SharpKeys remaps the whole key and not just the "modifiers" - if you remap Ctrl, then it's remapped, as you've found out.  If you are looking for that type of remapping, take a look at Microsoft PowerToys or AutoHotKeys as they both support that.

HTH!
