### ISSUE TITLE
Bootcamp Support

### ISSUE THREAD

**Issue by daangijzen** [randyrants/sharpkeys#325]
I've used your tool in the past to change the control, command, and alt key on my macbookPro before. But it seems like it doesn't register all kinds of keyboards and buttons anymore. 

I can't find the "Command/alt key" On my Logitech Craft.
And on the mac it self it doesn't find the "Option/alt" key

Do you know a work around or is there a way to find these button mappings? Or is there any way to map the raw key input?

**Comment by randyrants** [comment]
If this is about the Alt key, it's never available via TypeKey - the system menu traps the keystroke and it never gets to my UX.  That said you can select the Alt key by hand: you'll find it in the "Special" section.

**Comment by daangijzen** [comment]
Oh that's great! I'm going to try it immediately. (I was so caught up in
something else during the mapping, that I totally forgot that that was an
option!)

Also Thanks for the quick response!
