### ISSUE TITLE
Help! Function keys get inverted from manufacturer

### ISSUE THREAD

**Issue by castielus** [randyrants/sharpkeys#326]
Hi, I need help. I bought a 3rd party Chinese bluetooth LED Android /laptop keyboard. It works great until I discover that the function keys are inverted from the factory. The most troublesome inverted key is the DELETE/LOCK button. Normally, when you press Delete button, it deletes. But mine, the lock function is on. If I need to use delete, I must press FUNCTION+DELETE. It's a nightmare! Deleting photos one by one becomes cumbersome. 

I read that, in normal laptop keyboard, function keys can be inverted back using FUNCTION+ESC. Problem is, my Esc button is combined with home button. If I need Esc, I must press FUNC+ESC. Therefore it is imposisble for me to execute FUNCTION+FUNCTION+ESC  :'( 

I tred SharpKeys but I can't find any option that can help me convert:
LOCK into DEL 
FUNC+DEL into LOCK
HOME into ESC
FUNC+ESC into HOME

Please help.... I hope there is a way to do that....

**Comment by randyrants** [comment]
This works for Surface keyboards.  I flip half the keys so I don't have to worry about Fn very often.  The write up is under "What is the craziest remapping you've ever done?" in the FAQ: https://github.com/randyrants/sharpkeys#additional-faq-and-answers  

If it doesn't work, then the keyboard might be doing something weird that Windows cannot remap.  In that case I'd recommend giving Microsoft PowerToys a look.
