### ISSUE TITLE
Unknown key codes

### ISSUE THREAD

**Issue by builtinhold** [randyrants/sharpkeys#327]
I am using Sharpkeys with a Keychron K6. There are a few keys the keyboard can send that are not recognized by Sharpkeys and it comes up with the message: "You've entered a key that Sharpkeys doesn't know about."

Keycodes in particular are:
E0_204B, E0_204D, E0_2048, E0_2050, E0_1F0E.

EDIT: Ok, I can see looking at the code that those are the keycodes of AltGr(E0_20) + left arrow (E0_4B). It is interesting though that Sharpkeys does not detect keycombos with other keys, for example Ctrl or Alt, but it detects those combinations as what it looks like single keystrokes. Trying to see fi I can add the mappings and it works.

EDIT2: Right, so I think I understand how this works. I have a question though as I am not sure if this is by design or it is a bug:

Keycodes in Sharpkeys list are of the form E0_XX. All except the special code for AltGr which is E0_2048. This character is already present in the list of available codes. However, when Sharpkeys is writing the ScanCodeMap to registry, it is deliberately ignoring two of the digits :
```C#
String str = lvKeys.Items[i].SubItems[1].Text; //Example: (E0_0020)
 int BinaryStartIndex = str.LastIndexOf("_") + 1;
 int BinaryLength = str.LastIndexOf(")") - str.LastIndexOf("_") - 1;
 String Binary = str.Substring(BinaryStartIndex, BinaryLength); //Example: 0020
 String Reg = str.Substring(str.LastIndexOf("(") + 1, 2); //Example: E0
if (Binary.Length > 2)
     {
          Binary = Binary.Substring(2);     <<<<----------------HERE
     }
bytes[(i * 4) + 12 + 0] = Convert.ToByte(Binary, 16);
bytes[(i * 4) + 12 + 1] = Convert.ToByte(Reg, 16);
```
In fact, if you create a mapping that includes AltGr, write the ScanCodeMap to registry and fire Sharpkeys again to reload it from registry, you'll see that it will load as right Alt(E0_48) because of the missing bytes (E0_**20**48).

Is there a reason for this? Can the whole E0_2048 keycode code be written somehow into the ScanCodeMap? Is it a windows limitation? If this is possible, then just adding the other codes I am trying to map seems straighforward, but I am not familiar with the codemap format that windows stores in he registry....

Cheers!

**Comment by randyrants** [comment]
Hi - thanks for trying to dig into this but I wish you had checked the FAQ first: triple-byte codes are not supported by the Windows remapping technology that SharpKeys exposes.  No changes to SharpKeys can fix this.

Might want to try Microsoft PowerToys or AutoHotKeys as they have active remapping hooks that can likely support this.

**Comment by builtinhold** [comment]
Thanks a lot for clarifying!
