### ISSUE TITLE
Cannot Reverse swapped keys back to orginal map

### ISSUE THREAD

**Issue by coliven** [randyrants/sharpkeys#328]
I reversed my 0 and . on number pad Keys 52 and 53. I want to restore to the original layout--and cannot. 

I do NOT see the remapped keys in the drop down, except under special--so I choose those and it inserted "udo" . I tried that and it did not work. 

![image](https://user-images.githubusercontent.com/75632036/101378843-35381c00-3879-11eb-9449-d69875714725.png)

I tried typing the "From" key and it says it does not recognize it when I try to add, but it does recognize and showe the correct keys 53 and 52. 

Please advise how to put my keys back!

**Comment by coliven** [comment]
nm--I found the answer. Please add to your notes here to delete all and then save to registry.

**Comment by randyrants** [comment]
Um, I'm pretty sure that's in the FAQ, past comments, and even on the blog.  There's also a button for "delete all" which should also help.

**Comment by coliven** [comment]
thanks for writing. 
I'm new to github--the only FAQ's I saw were here: https://github.com/randyrants/sharpkeys and I still do not see an undo FAQ. I do not see the blog either. Maybe they are somewhere else.
My feedback would be that when I see your "Delete" it looks like it is for clearing the screen. It would not occur to me that it would delete--or undo---the changes.
In any case, thanks for getting back to me.
Catherine





    On Wednesday, December 9, 2020, 04:46:50 PM CST, Randy <notifications@github.com> wrote:  
 
 


Um, I'm pretty sure that's in the FAQ, past comments, and even on the blog. There's also a button for "delete all" which should also help.
