### ISSUE TITLE
Key that sharpkeys does not know about

### ISSUE THREAD

**Issue by robertsmit** [randyrants/sharpkeys#329]
![image](https://user-images.githubusercontent.com/7447535/101657358-133ec500-3a44-11eb-91ef-0d514bf33e66.png)
![image](https://user-images.githubusercontent.com/7447535/101657512-45502700-3a44-11eb-8833-5b0d29f3c3a4.png)
![image](https://user-images.githubusercontent.com/7447535/101657578-5a2cba80-3a44-11eb-9c7e-1024f0f5ab01.png)

![image](https://user-images.githubusercontent.com/7447535/101657436-2e113980-3a44-11eb-929b-4973b60a9cc6.png)

**Comment by randyrants** [comment]
It would be far more useful if I knew what keys you were pressing but the first and third keys are covered by the [FAQ](https://github.com/randyrants/sharpkeys#additional-faq-and-answers); the second one should remap fine.
