### ISSUE TITLE
Incomplete remap keyboard BMAX Y13 (i attach saved keyboard layout)

### ISSUE THREAD

**Issue by otraver** [randyrants/sharpkeys#330]
Hello everyone.
First of all I want to thank **_Randy_** for his work with **_Sharpkeys_**.
Since October 2019 I am the owner of a **BMAX Y13**. A magnificent laptop in relation to quality and price (just for about€ 320)
The BMAX brand has had the bad idea of ​​leaving the action keys active by default (_volume up/down, brightness, play/pause, etc_). 
To use the function keys it is necessary to press them together with the “**FN**” key.
Maybe with a multimedia use of the **Y13** it is more useful the use of the “action keys” instead of the “Function keys” but to work it is very cumbersome to have to press FN+F2 to rename, FN+F5 to update, Ctrl+FN+F4 to close tab or Alt+FN+F4 to close a application… 
I contacted with BMAX and they informed me that they would release a bios update that would solve the problem, but after 14 months this update has not come out and I think nor will it come out. 
The default layout of the "F,s" keys is this: 
F1 – Sleep 
F2 – Keyboard backlight 
F3 – Mute 
F4 – Vol down 
F5 – Vol up 
F6 – Screen Brightness down 
F7 – Screen Brightness up 
F8 – Fly mode 
F9 – Previous track 
F10 – Next Track 
F11 – Play/pause
F12 – second display config

By default, when you press any of them it performs the action that I describe. 
Yesterday I discovered **_Sharpkeys_** and I recognize that it has been very useful since I have been able to change the use of most of the keys except for:
F2 – Keyboard backlight 
F6 – Screen Brightness down 
F7 – Screen Brightness up 
F8 – Fly mode 
F12 – second display config 
Actually, now I just need to be able to change **F2 (rename)** and **F12 (developer mode in browsers)**. 
F6 and F7 I hardly ever use them. 
The problem is that when I click on “Type a Key” none of the four keys (F2, F6, F7, F8 and F12) is recognized by **Sharpkeys** 
THANK YOU, THANK YOU, THANK YOU for your work, **Randy**
I attachs the saved keyboard layout for the BMAX Y13 (may be compatible with other BMAX models)
[BMAX Y13.zip](https://github.com/randyrants/sharpkeys/files/5672884/BMAX.Y13.zip)

**Comment by randyrants** [comment]
Hi - that's because these six keys are not recognized by Windows.  Some of them are hardware specific (like keyboard/screen brightness) and others are bypassing the regular Windows keypress loop.  Basically, somethings cannot be remapped by Windows.  You might want to give Microsoft PowerToys a look, as they have a much more active remapper bit of tech.  It might support these other keys.

HTH!

**Comment by otraver** [comment]
> 
> 
> Hi - that's because these six keys are not recognized by Windows. Some of them are hardware specific (like keyboard/screen brightness) and others are bypassing the regular Windows keypress loop. Basically, somethings cannot be remapped by Windows. You might want to give Microsoft PowerToys a look, as they have a much more active remapper bit of tech. It might support these other keys.
> 
> HTH!

Thank's, is this the problem.
I've tried with powertoys and neither recognized that this keys are pressed.

**Comment by randyrants** [comment]
Sure!
