### ISSUE TITLE
Remapping for a specific keyboard

### ISSUE THREAD

**Issue by Mariusz-W** [randyrants/sharpkeys#334]
I need to swap Option and Command keys on an Apple keyboard when I use it with Windows in order that Alt and Win keys are in their proper places. On the Apple keyboard Option corresponds to Alt, Command — to Win, but their location is the opposite to what it is on Windows keyboards.

Important: I need this **only** when I connect the Apple keyboard.

How this can be achieved?

Secondly, since there is no other place to ask this: in the most recent release announcement you say:

_Stable release that removes support for any **triple-byte** keys as they are not support by Windows._

What does “triple-byte” keys stand for?

**Comment by randyrants** [comment]
If you are in Type Key and the scan code is something like E0_AABB this is a triple-byte scan code which is unsupported.  Double-byte is AABB which are often supported.  Some of these are still out of bounds but only a handful.

**Comment by Mariusz-W** [comment]
I installed sharpkeys in order to better understand your answer. I found that on a PC keyboard I often use with my notebook, right Alt emits , according to Type Key, E0_2038, so that key cannot be, for example, swapped with any other key. is this correct?
