### ISSUE TITLE
Pause Key

### ISSUE THREAD

**Issue by Fabirosmash** [randyrants/sharpkeys#337]
Excellent app! I'm just having a little issue trying to find the map for the PAUSE key. Not the multimedia pause, but the old pause key, like Win + Pause to see the PC specifications, for instance. I really need to edit this PAUSE key for my current keyboard.
Thanks for your attention.

**Comment by randyrants** [comment]
Sadly, Pause is a special key, similar to Break: it's not always sent to Windows in a way that capturable and many keyboards - as you've found - don't even call it it.  Or if they do it's under an Fn combo.

My keyboard has a dedicated Pause key so I tried to get the scancode but it just flows through the system without going through my code.
