### ISSUE TITLE
Map all apple keyboard buttons?

### ISSUE THREAD

**Issue by vlori2k** [randyrants/sharpkeys#338]
How about making a ready file for mappin all apple keyboards button? :) Im on my way doing it now, can share it once finished.

**Comment by technixp** [comment]
@vlori2k Can you share your mappings?

**Comment by vlori2k** [comment]
![SharpKeys_RMLbs7Ch6C](https://user-images.githubusercontent.com/9167528/109574224-da1c6b00-7aef-11eb-9854-0790b05d1231.png)

**Comment by randyrants** [comment]
Eject would depend on the keyboard: if the command comes to Windows, it would be remapped.  If it doesn't, you'd need something like Microsoft PowerToys.  SharpKeys cannot do anything with a combo key.

**Comment by Angebica** [comment]
SUPER INTERESTED IN THIS

**Comment by Angebica** [comment]
> ![SharpKeys_RMLbs7Ch6C](https://user-images.githubusercontent.com/9167528/109574224-da1c6b00-7aef-11eb-9854-0790b05d1231.png)
> 
> This works perfectly for me.

can you save and upload your keys mapping file?

**Comment by vlori2k** [comment]
I dont know how to upload the file here, so i shared it inside a folder in my google drive:

https://drive.google.com/drive/folders/1moZJp8P3EmBpfro1aFBoTvlGbF4PNA2g?usp=sharing
