### ISSUE TITLE
Trying to remap Hanja/Chinese character key on Korean keyboard

### ISSUE THREAD

**Issue by quietsilent** [randyrants/sharpkeys#34]
There are several different Korean keyboards out there. The one I have is 103 or 106, I think? Anyway it has a key for typing Chinese characters. SharpKeys says it's E0_40F1, and "SharpKeys doesn't know about" it. Is there any way to add this key to the table so that I can remap it?

Otherwise, I love SharpKeys. Way simpler and easier than the other utilities I tried for this purpose.

I'm new to most of this keyboard business, but if I can provide any helpful info, I will do my best. 

Attached a picture of the keyboard with the key highlighted.

![kakaotalk_20170831_144637272](https://user-images.githubusercontent.com/31499964/29908292-9fefbde4-8e5b-11e7-873b-c016ed08451f.jpg)

**Comment by randyrants** [comment]
That key is a triple byte code key which is something the registry doesn't remap well, if at all.  I've tried to enable this for keys like PrtScn but have been unable to get it to successfully remap it.  Someone else on the project may be able to help.
