### ISSUE TITLE
Add reverse button for mappings

### ISSUE THREAD

**Issue by OndrejPistora** [randyrants/sharpkeys#343]
Enhancement:
Please add reverse button next to a mapping co if I have mapping from A -> B so I could simply create mapping from B -> A.

**Comment by randyrants** [comment]
This one I'm a little leery of: there are at least a dozen posts in Issues calling out that they are confused with how to the map keys - making it easy to swap values (great for people that want it but dangerous for people that don't to) is hard to rationalize.
