### ISSUE TITLE
Pause/Break Bug

### ISSUE THREAD

**Issue by Florian-Mahlberg** [randyrants/sharpkeys#346]
Hey, I wanted to select the Pause/Break key, but the "Type Key" function said, I pressed the Num Lock key. 
Is this a software issue or is it local, beacuse of my computer?
 The Num Lock key light is not going on, if I press the Pause/Break button.

Thanks for your help. 

[Edit]
Keyboard Model: Logitech K120

**Comment by macruspareto** [comment]
I've built myself a custom version of SharpKeys with this patch and can confirm that it's working without any problem.

https://stackoverflow.com/questions/38846347/what-is-the-scancode-of-pause-break-key

All you have to do is get a Visual Studio 2019 Community, add one line and compile. Took me 20 minutes to download/install and 2 minutes to change/compile. :)

It doesnt seem to have broken anything but if it does, just restore the original keymap and forget the whole damn thing :)
