### ISSUE TITLE
Swapping keys not working!

### ISSUE THREAD

**Issue by zweili** [randyrants/sharpkeys#347]
Hi! I tried to swap Z and Y but not effect! I can map Y to Z or the inverse but not both at the same time (swap).
Should I do something differently ?

Thank you very much
![swapp](https://user-images.githubusercontent.com/22447196/107852718-9b5d9400-6e12-11eb-9da7-78df69a75f14.png)

**Comment by randyrants** [comment]
Not entirely sure, it might depend on the keyboard.  I've remapped Windows to Ctrl and Ctrl to Windows successfully but I have heard that swapping keys doesn't work, which is why it's called out in the FAQ.  Might want to give PowerToys a try.
