### ISSUE TITLE
Map one key to multiple keys?

### ISSUE THREAD

**Issue by bryansray** [randyrants/sharpkeys#348]
I'm looking to remap my `<CAPS LOCK>` to  `<CTRL> + <ALT>`

According to the README.md it looks like SharpKeys will support that? But for the life of me I can't find out how to set it up via the UI. Perhaps I have to make a custom `.skl` file?

Is this possible?

**Comment by randyrants** [comment]
Actually, the README shows just the opposite: "Map multiple key presses to one key - e.g. it will not support an attempt to remap Ctrl+C to the F5 key"

Try Microsoft's PowerToys: they support mapping to modified keystrokes.

**Comment by bryansray** [comment]
Ah, I see. Thanks for the reply @randyrants. I think I as having a tough time deciphering what that meant for some reason.
