### ISSUE TITLE
Should the message box be updated?

### ISSUE THREAD

**Issue by Seanny123** [randyrants/sharpkeys#35]
The message box does not currently state support for Windows 8 and 10? Would it be appropriate to change at this point? Also, should Windows versions that are no longer supported be dropped?

**Comment by randyrants** [comment]
The welcome box should have called out all Windows builds from 2000 or XP through 10 so it should be OK - the Registry key that I point to has been in there since NT 4, give or take a year.

Windows 3.1, 95, 98, or Millennium would not be supported.
