### ISSUE TITLE
Reprogrammed keys "disappeared" 

### ISSUE THREAD

**Issue by JERoed** [randyrants/sharpkeys#352]
I reprogrammed three keys on my keyboard, but after i wanted to change something, the reprogrammed keys stopped working.
![Udklip](https://user-images.githubusercontent.com/80294228/110397079-77881980-8071-11eb-865a-88e19dc0024b.PNG)

**Comment by randyrants** [comment]
Looks like the Registry key got borked.  Please remove all the mapped keys and re-enter them.
