### ISSUE TITLE
Unable to use Alt Gr + Num combinations

### ISSUE THREAD

**Issue by barletta** [randyrants/sharpkeys#353]
I'm using US INT keyboard settings and am trying to remap the Alt+Gr + Num values to something else and I get an error saying I've entered a key SharpKeys doesn't know about: `Special: Alt Gr (E0_2038) + Key: 4 $ (00_05) = (E0_1F05)`

I'm also trying to remap this to the £ sign which doesn't seem to be available as a Special character on the "To this key" section.

**Comment by randyrants** [comment]
As called out in the FAQ, combination keys are not supported.  Please try Microsoft's PowerToys.
