### ISSUE TITLE
Key E0_1F65 on HP Elitbook is missing 

### ISSUE THREAD

**Issue by redia00** [randyrants/sharpkeys#355]
Hey guys, thanks for your great work.

Everything is in the title. There is 2 "non used" key on a HP elitebook laptop, with phone design on it. Not working with teams or zoom. So not used at all. One of them don't have key number, the second one is E0_1F65 , that is not included in current release. (3.9.2).
Thanks

**Comment by randyrants** [comment]
Hi - per the FAQ:
Q: Type a Key shows a code that is E0_nnnn - can I remap this key?
A: If a scancode has 6 characters, then it is what is known as a triple byte scancode which is something that cannot be remapped by the Windows Registry. To remap a key like this, you'll need an active remapper like Microsoft PowerToys or AutoHotKeys or the app that came with the keyboard (e.g. Logitech's Options) if available.
