### ISSUE TITLE
2 Keys not Recognized

### ISSUE THREAD

**Issue by FlubnubBub** [randyrants/sharpkeys#356]
My (ancient) keyboard has 2 keys that aren't seen by Sharpkeys.  When I use the "Type Key" method, nothing is registered at all.  When I manually select "App: Media Select" and "Web: Home", it has no effect after restarting.  MS Powertoys describes the inputs as "Select Media" and "Browser Home".  
Both of these keys cause windows to pop up.  Is it possible that these windows are stealing the focus before Sharpkeys has a chance to accept the input?     (Win10/64)
Thx

**Comment by randyrants** [comment]
Yes, although to my knowledge the Alt key is usually the "problem" key that Windows traps.  If PowerToys can see it, I'd let them remap it.
