### ISSUE TITLE
no clue what to do with this key

### ISSUE THREAD

**Issue by Latravant** [randyrants/sharpkeys#358]
all i want to do is disable a key on my keyboard that i accidentally push. when i push it it locks the screen, like my log in screen pops up. all my games have open close, my itunes freezes up. and honestly i never use it on purpose. when i try to press the key using sharp key, the same thing happened and it locked the screen and i'm not sure if the program actually captured the key i pushed. it showed this when i logged in Special: Left Windows (E0_5B). i dont want to select that as the key to disable  since i'm not 100% sure thats the key i pushed. 

the only way i can describe the key is it shows a small lock icon on it. no numbers or letters, just a picture of a lock

**Comment by randyrants** [comment]
Sounds like one of the new Microsoft keyboards, which has "Lock Windows" in the upper right corner.  Sadly this key, like the new Office key, are triple byte and cannot be remapped by SharpKeys.  If it is a Microsoft keyboard, please download the Keyboard/Moues Control center software as that may have the ability to remap it.  Or Microsoft PowerToys which is an active remapper.

**Comment by Latravant** [comment]
thank you
