### ISSUE TITLE
Can't remap € and $

### ISSUE THREAD

**Issue by hgdagon** [randyrants/sharpkeys#36]
On my very first run, I pressed type key and typed "€", it said that I entered a key that it doesn't recognize. On subsequent runs, it failed to detect "€" or "$". I'm having a problem with these keys and want to disable them completely.

**Comment by randyrants** [comment]
Not sure what you mean by run: running the app doesn't change anything as the reboot of Windows is when the remapping kicks in.  I also have no idea scancaode the euro key has but if that's partnered with $ then please be aware that you're remapping the whole key, not just Shift+Euro.
