### ISSUE TITLE
Remap Backslash key

### ISSUE THREAD

**Issue by JohnBrun31** [randyrants/sharpkeys#363]
Hey I want to remap the Application key to the backslash key, but my keyboard is Spanish.
I have it set to `Key: \| (00_2B)`, but instead of printing `\ `and `| `it just prints `ç`
How can I change that? 
Thanks!

**Comment by randyrants** [comment]
I would check the scancode of the \ | key on the Spanish keyboard layout.  For example, when using a UK keyboard the scancodes don't always match the key unless I'm also using the en-UK layout as well.

You might also want to give Microsoft Power Toys a look.
