### ISSUE TITLE
Keyboard mapped to US layout

### ISSUE THREAD

**Issue by Biumsp** [randyrants/sharpkeys#364]
I have a dumb keyboard without > and < keys. I wanted to remap the `Page Up` and `Page Down` keys to the `, <` and `, >` keys, and I added those mappings. I wrote to register and restarted. Once the laptop was on I noticed that many other keys changed. I think my Italian keyboard has been mapped to a US keyboard. So I don-t have many symbols and almost every special symbol changed place. How can I fix this?

EDIT:
I found out how to restore the Italian layout, but it should be clearly specified that using this software maps automatically to a US keyboard, not only switches the selected key.

**Comment by randyrants** [comment]
SharpKeys does not have the ability to change this and I have actually tried it on a Japanese keyboard with a ja-JP layout select: worked fine.  It's sounding like Windows took offense to something and dropped out to a default of en-US.  Sorry about that, but I'm not sure SharpKeys did that to you.
