### ISSUE TITLE
"You've entered a key that Sharpkeys doesn't know about"

### ISSUE THREAD

**Issue by Pacfanweb** [randyrants/sharpkeys#366]
I have a Merc Stealth keyboard.   It's for gaming.  Has an extra pad to the left of the regular keyboard, with all the commonly-used gaming keys in a nice shape.  Best keyboard ever made, IMO.  
Anyway, the manufacturer discontinued it, then let the driver become untrusted, so now it won't work in Windows 10. 

I've been using Powertoys as a work around.   I remapped the keys....when you don't have them remapped or the driver working, hitting the "W" on the gaming pad part opens a new window in Chrome.  (or probably whatever is your default browser)

Problem is, you can't press buttons at the same time with Powertoys.  It remapped them fine, but if you're going forward and want to scoot left a bit, you can't do it while you're still going forward...you have to stop, move left, then back forward.   So it makes it impossible to game, at least any shooter-type games.   
I inquired about this on the Powertoys site here and they recommended Sharpkeys.   

So installed Sharpkeys tonight.   The "W" on the gaming portion, when I hit "Type" to remap it, says "You've entered a key that Sharpkeys doesn't know about"
The key # shows up a (00_100)  when you try and map it.  It does this with several of the keys on the gaming portion of the keyboard.  
Has anyone heard of this?   Any fix?    Thanks

**Comment by dwiqi12** [comment]
same issue here, happen to my F4 key. there are no F4 in from key menu but there are F4 in to key menu

**Comment by randyrants** [comment]
Per https://github.com/randyrants/sharpkeys#additional-faq-and-answers:
Q: Type a Key shows 00_100 - can I remap this key?
A: 00_100 is a catch all code that Windows reports when a key is captured by hardware or some other driver so there's no way to successfully remap that key, especially since multiple keys can return the same 00_100 code.
