### ISSUE TITLE
INSERT key ... help!

### ISSUE THREAD

**Issue by bawldiggle** [randyrants/sharpkeys#367]
I use Ctrl+INSERT to display a Clipboard Extender (menu)
I only want to INSERT and never Overwrite
Is it possible force INSERT key to always default to INSERT and never OVERWRITE ?

*My only experience is with VBA in Excel ... and Key Events (eg, KeyUp runs after KeyDown)*

Thank you

**Comment by randyrants** [comment]
Modified keys cannot be mapped by SharpKeys.  Please give Microsoft Power Toys a look.
