### ISSUE TITLE
Logitech mouse [sic] task switch key: E0_1F38

### ISSUE THREAD

**Issue by ardasaltoglu** [randyrants/sharpkeys#368]
My Logitech mouse seems to emit a keyboard press event with the code `E0_1F38` if the thumb button is pressed. It opens an overlay where one can select the window to switch to. It doesn't look like the Alt-Tab or Windows-Tab overlays.

Can the code `E0_1F38` be added?

![image](https://user-images.githubusercontent.com/43547431/116127971-196ece80-a6d1-11eb-8660-a58ea0ecbadf.png)

I read in the FAQ that a three-byte code is not supported but I could not be sure if this is one, and in the code I saw other codes with the same length (Alt Gr).

**Comment by randyrants** [comment]
Per https://github.com/randyrants/sharpkeys#additional-faq-and-answers:
Q: Type a Key shows a code that is E0_nnnn - can I remap this key?
A: If a scancode has 6 characters, then it is what is known as a triple byte scancode which is something that cannot be remapped by the Windows Registry. To remap a key like this, you'll need an active remapper like Microsoft PowerToys or AutoHotKeys or the app that came with the keyboard (e.g. Logitech's Options) if available.
