### ISSUE TITLE
Ctrl+Down stops working while Sharpkeys is in use

### ISSUE THREAD

**Issue by michaelmendis** [randyrants/sharpkeys#370]
My delete button is over-sensitive and becomes active without  being touched (and, for example, deletes chunks of text letter by letter in a Word document or file after file in File Explorer). I installed Sharpkeys and deactivated the Delete button as a temporary solution, but I have found, since then, that the keyboard shortcut CTRL+Down (which I use to navigate between paragraphs in Word, or to the bottom of a row of data in Excel) stops working. When I remove the entry deactivating DEL in Sharpkeys and reboot, CTRL+Down is working again...

**Comment by randyrants** [comment]
The Windows technology that SharpKeys exposes has no way to remap modified keys - no idea what the keyboard is doing but it sounds like there's some confusion in the scan codes that is disabling more than one key.

Please remove all the SharpKeys mapping and give AutoHotKeys or Windows PowerToys a shot.
