### ISSUE TITLE
Sharp keys app not opening

### ISSUE THREAD

**Issue by DanielBokan** [randyrants/sharpkeys#372]
When I click on the .exe file to open the app, nothin pops up, only the icon shows in the taskbar. Now I cannot remove the key mappings. Please can you help me fix this

**Comment by randyrants** [comment]
Could be the window is trying to draw itself somewhere it cannot be drawn to, like a different monitor or maybe a different resolution space.  While the app is running, right click the task bar and select cascade or tile or something, which should force the window into view.  Worst case you can always remove the mapping yourself via the Registry.

**Comment by DanielBokan** [comment]
That fixed it, thank you. For some reason it was permanently minimized and I could not open it.
