### ISSUE TITLE
Very special keys of Natural Keyboard

### ISSUE THREAD

**Issue by BsNoSi** [randyrants/sharpkeys#374]
Office 365 key → opens office 635 website
Emoji key → opens emoji input field

BOTH keys return (E0_205B) which is unknown and because of this can not be substituted.

Above the keyboard there are several "media keys" and "special keys" available that return (00_100) → unknown 
Media player keys in this key line do not return any key code.

If there is a way to evaluate more information, please, let me know.

**Comment by randyrants** [comment]
No way for SharpKeys to help with this as both keys are triple-byte scancodes.  Give Microsoft PowerToys a look.
