### ISSUE TITLE
Remapping combinations with volume up/down

### ISSUE THREAD

**Issue by francescoboc** [randyrants/sharpkeys#377]
Hi, I am trying to remap some combinations with volume up/down buttons, for example:
Alt Gr + Vol up: `E0_2030`
Alt Gr + Vol down: `E0_202E`
They are correctly identified by Sharpkeys, but then I cannot remap them and I get the following error message:
You've entered a key that SharpKeys doesn't know about.

Would it be possible to allow remapping of these combinations?

**Comment by randyrants** [comment]
Per the FAQ:
Q: Type a Key shows a code that is E0_nnnn - can I remap this key?
A: If a scancode has 6 characters, then it is what is known as a triple byte scancode which is something that cannot be remapped by the Windows Registry. To remap a key like this, you'll need an active remapper like Microsoft PowerToys or AutoHotKeys or the app that came with the keyboard (e.g. Logitech's Options) if available.
