### ISSUE TITLE
CSS Fadein not Working after Installing sharpkeys

### ISSUE THREAD

**Issue by SHERMANCHEN08** [randyrants/sharpkeys#378]
After I installed sharpkeys, CSS fadein is not working any more.

**Comment by randyrants** [comment]
Not entirely sure what CSS fadein is but since SharpKeys doesn't stay running if you close the window, I'm 99.44% certain that SharpKeys is not interfering with anything else on your system.

**Comment by SHERMANCHEN08** [comment]
Hi Randy,
Thank you for your reply!
To my surprise, CSS fade-in has become working now!
Sherman
