### ISSUE TITLE
Can't map 00_100 but the number may not be right anyway

### ISSUE THREAD

**Issue by ian-sharpe** [randyrants/sharpkeys#38]
00_100 is reported by Sharpkeys for all the special keys on my Logitech keyboard - web home and various multimedia controls. Cann't map that number in any case - SharpKeys does not know about it.

Great program though.

**Comment by randyrants** [comment]
More than likely the keys are getting trapped and acted on by the hardware which prevents Windows from remapping it.  Sorry it couldn't be of more help!
