### ISSUE TITLE
Unrecognized key on Sun Type 6 USB keyboard

### ISSUE THREAD

**Issue by ebah80** [randyrants/sharpkeys#380]
Hi,
seems I cannot make working few of my beloved Type 6 keyboard on Windows 10 :(
Especially mute,volup,voldown are simply not recognized by the system, neither by SharpKeys.
Somehow Power key is recognized.

On earlier versions of windows it was working and also on linux and mac is working fine.

These are the specs:
https://deskthority.net/wiki/Sun_Type_6

Any suggestions?

Thanks for the great work!

**Comment by randyrants** [comment]
Very old keyboard, so I have no idea what it's sending to Windows.  If you try Type Key, what does it say it is?  Likewise, you can also give Microsoft PowerToys a try, as they have a more active remapper.
