### ISSUE TITLE
Can't map anything to the Special: <>| key

### ISSUE THREAD

**Issue by sthomen** [randyrants/sharpkeys#382]
I have previously used sharpkeys to use a US keyboard with a Finnish layout to great success, but when I installed it on my home PC running Windows 10N 21H1 (19043.1083) mapping the E0_56 key does not work (pressing it appears to do nothing). I can map other keys just fine, even others with E0_ prefixes except for the one I actually need (that does not exist on the physical keyboard).

Attached is a screenshot of the config and registry, does this look correct?

My only other idea is that windows would block the scancode if the physical keyboard doesn't have it for some reason. Do you know if this is something that it does?

![Screenshot 2021-07-09 212327](https://user-images.githubusercontent.com/1172760/125121836-32e2bc80-e0fd-11eb-9e3a-53c01ac1f67f.jpg)

**Comment by randyrants** [comment]
In so far as I know - and this is not much, when it comes to non-US keyboards - the < > | would need to be part of your current keyboard layout, which would be different, given your layout.  That said, you might want to give Microsoft PowerToys a look: it is actively remapping keys which should be layout agnostic.

**Comment by sthomen** [comment]
Alright, thanks.
