### ISSUE TITLE
Keys stuck

### ISSUE THREAD

**Issue by toni1331** [randyrants/sharpkeys#384]
Years ago I used this on my laptop to switch around the up arrow and the right shift keys. I now have a desk set up where I am using the same laptop but with an external keyboard that has the shift and up arrow keys in the correct spots, so I was going to undo the mapping. I thought that I had succeeded, but now both my right shift key and the up arrow are shift. When I use the find a key function on the up arrow it thinks that it is right shift, and I am now stuck. Any advice would be greatly appreciated. Thanks!

**Comment by randyrants** [comment]
Remove all of the remappings, save the changes to the registry and reboot.  That will remove all of the mappings that Windows is aware of.
