### ISSUE TITLE
Please Create [Delete from Registry] Button!

### ISSUE THREAD

**Issue by Mr-Denni** [randyrants/sharpkeys#385]
If there are already exist [Add] and [Delete] button for keys mapping, I think you also should create [Delete from Registry] button for easy deleting one or multiple keys map from registry.

**Comment by randyrants** [comment]
This should be possible by clicking "Delete All" and "Write to Registry" will accomplish this.  I'd much rather keep it a two click process, so no one hits it by accident and loses their mappings.
