### ISSUE TITLE
Can't See Window

### ISSUE THREAD

**Issue by AReardon77** [randyrants/sharpkeys#388]
Hello, I got a new computer a few weeks ago and it didn't have a play/pause key so I downloaded sharpkeys and remapped another key to it. After using the laptop for a few weeks I've decided I want to change that remapping but when I went to reopen sharpkeys the app pops up and seems to open but no window opens. It just comes up with the icon in the taskbar, but no window that I can view or use the application. I have tried uninstalling and reinstalling the app and it does the same thing. Any ideas?

**Comment by randyrants** [comment]
Likely off screen or set to 0,0 due to a multimonitor or some other bug.  Please right click on the taskbar and select Cascade or Stack windows.

**Comment by rjspiker** [comment]
I'm actually experiencing the same issue.  Cascading or stacking doesn't appear to be the solution.

**Comment by randyrants** [comment]
In that case, try closing the app, then remove this key in the Registry:

`HKEY_CURRENT_USER\Software\RandyRants\SharpKeys`

This is where the Windows size and position information is stored.  Once deleted, reopen the app.

**Comment by rjspiker** [comment]
Thanks @randyrants.  That solved it 🥂.
