### ISSUE TITLE
Map microsoft office key ?

### ISSUE THREAD

**Issue by xaff** [randyrants/sharpkeys#389]
Heyo and thanks for your tool :),

I have an microsoft ergonomic keyboard (LXM-00005) and they put on it a very annoying "office key", right to Alt Gr, wich open a office windows each time you mistape on it !

The key code returned by SharpKey is (E0_205B).

If you could add this one, you'll probably save my keboard form a suddenly violent death ^^

**Comment by randyrants** [comment]
Cannot be done with SharpKeys as it's a triple-byte code.  You can either try Windows' PowerToys or the Microsoft Keyboard software that will support your keyboard.

**Comment by xaff** [comment]
I tried theses with no luck, thanks anyway.
