### ISSUE TITLE
Can't remap E0_3F4C

### ISSUE THREAD

**Issue by coco1602** [randyrants/sharpkeys#39]
Hello !
This is a brillant software !
However, it doesn't manage to remap the key E0_3F4C.
Is there a way to resolve the problem ?
Thanks !

**Comment by randyrants** [comment]
That key is a triple byte code key which is something the registry doesn't remap well, if at all.  I've tried to enable this for keys like PrtScn but have been unable to get it to successfully remap it.  Someone else on the project may be able to help.

**Comment by 0cjs** [comment]
For what it's worth, I'm having the same issue with the Caps Lock key on a Wyse RDP terminal; for some reason those terminals don't seem to use the standard Caps Lock scan code. I'd love to hear about an alternative means of remapping this key.

(At this point, I'm looking at opening up and hardware-patching my keyboard or building a microcontroller device to do the key swapping. Replacing the keyboard would cause other problems, such as losing my TrackPoint.)

**Comment by 0cjs** [comment]
Since the problem still exists, can I suggest we leave the issue open so that a) others running into can easily find out that it's a known problem, and b) if someone comes along that knows of a fix for this, they can see that this project needs that solution?

**Comment by randyrants** [comment]
It's been a known issue since I started working on mapping keys in 2002, but sure - it can stay open.

**Comment by randyrants** [comment]
Give v3.6 a try - igieon made a change to the TypeKey screen that may clean this up.

**Comment by coco1602** [comment]
Hi ! Thanks a lot for your help ! It works perfectly now !
