### ISSUE TITLE
Doesn't not detect some buttons from Apple Magic Keyboard

### ISSUE THREAD

**Issue by maslbl4** [randyrants/sharpkeys#390]
On Windows 10  it Doesn't  detect the following button keys:
- option left and right although windows define them as Alt
- fn
- eject (⏏️)

**Comment by randyrants** [comment]
Please review the FAQ.  I explains why ALT keys need to be selected in the list (as opposed to type key) about why Fn keys are not always selectable.

For Eject, this ends up being a hardware key on Mac keyboards that goes directly to macOS; Windows doesn't get a chance to remap it unless the Apple driver for their keyboard wants Windows to.
