### ISSUE TITLE
Can't Alt+Tab to fullscreen apps

### ISSUE THREAD

**Issue by Treenguyen** [randyrants/sharpkeys#392]
Hello!  I think sharpkeys might conflicts with other files that causes flashing when alt+tab to full screen apps/games. I still can perfectly tab to other windows and borderless applications but unable to access full screen apps, they flash once and direct me back to other windows.

**Comment by Treenguyen** [comment]
I did an in place update to my Windows, thinking it was the keyboard's firmware could've malfunctioned until I launch sharpkeys. After rebooting, I'm unable to tab to fullscreen apps

**Comment by randyrants** [comment]
SharpKeys - if it's not open - cannot conflict with other apps: it does not stay running in the background and it is exclusively an app that edits a specific Registry value for Windows to use.  Windows then uses that value to remap the keys you told it to.

What keys did you remap?  If it involved one of the ALT keys or TAB, that would very likely be the reason why you're seeing different behavior but again, it's not SharpKeys changing the behavior - it is Windows reaction to these keys being remapped.

If the report is that you have the SharpKeys window open and it's doing something weird with Alt+Tab, that would be a first (as I use Alt+Tab several times an hour an never saw anything off) but at least it can be investigated.

**Comment by Treenguyen** [comment]
I remapped del - printscreen, ins - del. Updated: I believe it has something to do with Windows 10 new update, August 2021 update (KB5005033). They broke Alt + Tab, users are getting a blank screen, or just being dumped in the Windows 10 desktop. 
Thank you for your reply!
