### ISSUE TITLE
Reassign FN button

### ISSUE THREAD

**Issue by slava-poddubsky** [randyrants/sharpkeys#396]
Is it possible to reassign FN button? I'm about the button in the bottom left corner: https://www.amazon.com/OMOTON-Ultra-Slim-Bluetooth-Keyboard-Enabled/dp/B00GD1BGYO

(for now this button is not recognized at all when I press 'Type Key' button)

**Comment by WebMechanic** [comment]
I don't believe it is possible to remap this particular key. - at least according to some Microsoft docs on key remapping. Just like you can't remap "Ctrl+Alt+Del".
It's "hardwired" inside the keyboard to toggle what F-keys and others eventually send to the OS.
However, there might be keyboard that come with their own driver software and utilities that allow this, so ypu might want to check with the vendor first.

**Comment by randyrants** [comment]
As is called out in the description/FAQ: "Support certain hardware keys that never make it to Windows - e.g. Logitech’s volume buttons or most Fn keys" for the reasons WebMechanic touched on: the Fn key isn't often sent to Windows for it to remap.

**Comment by WebMechanic** [comment]
To make things more confusing...
On my (new) Lenovo laptop I was actually able to remap "Fn" to Ctrl".. **partially**. While Ctrl-C/V/X/A worked, Ctrl+S didn't and most of the media buttons occupying the F-keys were also un-re-mappable.

I meanwhile learned that the Lenovo had a "Fn-Lock" feature built into the ESC key... similar to Caps-Lock or Num-Lock to basically reverse the "feature" and have F-keys first, Fn-Stuff second.
So I could remove all the former mappings :-)

**Comment by WebMechanic** [comment]
oh and: apparently some computers have this built into their BIOS, similar to "Num-Lock" always enabled.
Might be worth having a look at that, too.
