### ISSUE TITLE
Doesn't recognise some media remote keys

### ISSUE THREAD

**Issue by cjdshaw** [randyrants/sharpkeys#4]
I have a Bluetooth media remote and the arrow keys, Enter and Escape work fine in Sharpkeys - They appear when I press "Type" and can be remapped.

The volume up, down, play, next+prev tracks buttons, though, give a (00_100) and a "You've entered a key that Sharpkeys doesn't know about" error. I've tried selecting them under Media:* but it doesn't seem to have any effect - their old function still happens when they're pressed

**Comment by randyrants** [comment]
This is expected.  Some keys on some keyboards are trapped at the driver level and don't get passed to the Windows keyboard handler.  If Windows doesn't get the keystroke, it doesn't have the opportunity to remap the key.  

You may want to investigate a more active remapper, like AutoHotKeys,
