### ISSUE TITLE
numeric function/keypad on extended keyboard

### ISSUE THREAD

**Issue by tuilbox** [randyrants/sharpkeys#40]
I was VERY happy to find this software years ago. Thanks!
I've noticed lately though, that the number pad cannot be accessed. I only get shifts in cell location in Excel, and I cannot enter numbers. I've hit Clear a thousand times. No numbers. I remapped F15 to be the num lock. Still, no numbers. I ordered a new Mac extended keyboard. No numbers. I even tried to map the numbers to the numbers, but no numbers...  I'm using Windows 7. Any thoughts?

![capture2](https://user-images.githubusercontent.com/12241760/31058313-a4494fdc-a6a6-11e7-97c0-7b96f529ebe7.JPG)

Thanks!

**Comment by randyrants** [comment]
Unless Windows gets a special scancode that denotes that something is the numeric keyboard, I'm not sure there's anything to be done here.  I do notice that there you're mapping Num 1 to Num 1 - that's not going to do anything and may actually cause unexpected results.
