### ISSUE TITLE
Avoiding "Shift" and producing LShift or RShift

### ISSUE THREAD

**Issue by dumblob** [randyrants/sharpkeys#403]
Windows NT has one big wart since their introduction AFAIK. Namely they silently map both `LShift` and `RShift` to `Shift` so that no layout nor application can distinguish which of the shifts was actually pressed.

Does sharpkeys allow to circumvent this limitation and truly pass-through `LShift` as it is as well as `RShift` as it is (I don't mind whether `Shift` will be generated in addition to the original given `RShift`/`LShift` key or if no `Shift` will be generated)?

**Comment by randyrants** [comment]
When either of Shift keys are pressed, Windows sees it as Left Shift or Right Shift, which gives you the ability to remap them independently.  Once the Shift is pass on from the remapper code, I have no idea what happens, if Windows is treating LShift and RShift the same internally.  I know games can tell the difference, but they could be grabbing the keypress before it goes to Windows, so that's not a clear example either.

Sorry, I'm not of more help for this.

**Comment by dumblob** [comment]
>Once the Shift is pass on from the remapper code, I have no idea what happens, if Windows is treating LShift and RShift the same internally.

Ah, then it doesn't really matter. Yes, RShift and LShift will be discarded (same goes for LCtrl & RCtrl and LAlt and RAlt) and further treated as one for **all** modifier behavior (note modifier behavior is distinct from dead key behavior and distinct from lock behavior).

>I know games can tell the difference, but they could be grabbing the keypress before it goes to Windows, so that's not a clear example either.

Yep, any application can read virtual key codes where RShift and LShift is of course maintained (this is also the reason why e.g. M$ Office treats some key combinations differently than other apps - simply because they overwrite the kbd layout behavior). It's really just about the **modifier** behavior where it's treated as one key :cry:.

> Sorry, I'm not of more help for this.

No problem. I'm currently considering workarounding the problem by implementing an invisible IME for the few key combinations which need to distinguish LShift from RShift during modifier behavior.

**Comment by randyrants** [comment]
Yeah, I guess I'm seeing the difference between Left/Right keys be them Shift, Ctrl, Alt, etc. but I don't know what happens after that or how their modification works on other keys.  E.g. I was just looking at PowerToys and I can remap D to be Ctrl+D but I cannot say LCtrl+D versus RCtrl+D.  Either they tried to keep it simple or specifying one of the three (L, R, or "either") isn't viable with Windows.

The most experience I've had with the IME is using it for the odd times I need a foreign character, for a long session of something - if it's a one off, I just go to a translation app and grab the native characters there.

**Comment by dumblob** [comment]
>Either they tried to keep it simple or specifying one of the three (L, R, or "either") isn't viable with Windows.

Just for reference, my primary motivation is not L, R, nor "either" but to detect the fourth last combination - "both" :laughing:.
