### ISSUE TITLE
What key is key to lock PC

### ISSUE THREAD

**Issue by Varrial** [randyrants/sharpkeys#404]
I try to change lock shortcut to sleep, because i get lock button on my keyboard. i prefer that key will sleep or hibernate my pc

**Comment by Varrial** [comment]
Unfortunately PowerToys don't allow changing shortcuts with win key

**Comment by randyrants** [comment]
Sure, you cannot change Win+L to be Win+8 or something but you can change L act like Win+L.  I guess I was thinking you'd want to move a key to act like lock.
