### ISSUE TITLE
proper way to do a 3-way remapping?

### ISSUE THREAD

**Issue by blesphy1** [randyrants/sharpkeys#405]
i want to switch ctrl to windows key, windows to alt, and alt to ctrl, but when i try writing this to registry it doesnt work properly. when i do a two-way flip it works perfectly normal. is this possible to do with sharpkeys?

**Comment by teeseus** [comment]
what is "two-way flip"?

**Comment by teeseus** [comment]
propably a swap :D

**Comment by randyrants** [comment]
I've used Left and Right on these keys to make this viable.  e.g.:
Map Left Windows to Left Alt
Map Right Alt to Left Ctrl
Map Right Ctrl to Right Windows

This would move the keys around accordingly.

**Comment by blesphy1** [comment]
sorry for the confusion, i didn't use my head much lol, just had to map the keys in the way you suggested and it worked perfectly, thanks for sharpkeys @randyrants
