### ISSUE TITLE
Ducky One 2 RGB unsupported

### ISSUE THREAD

**Issue by YeloPartyHat** [randyrants/sharpkeys#406]
Ducky is a very popular brand of keyboard and I am using the Ducky One 2 RGB full keyboard and many of the top right keys have no support in this software or map incorrectly when typed into the "Type-Key" section. 

Tested Keys:
- Pause,
- Cal
- Mute
- Volume Up
- Volume Down

**Comment by randyrants** [comment]
Right: none of these are standard keys, so there's no guarantee that these keys are going to get passed to Windows, which is the only way Windows can remap the keys.  This is true of Microsoft's own keyboards for most of these keys; Pause is a triple-byte code which isn't supported by SharpKeys for any keyboard.  Limitation of the Windows remapping tech, sorry.

Please give Microsoft PowerToys a shot or maybe Ducky has a software utility that can remap these keys.
