### ISSUE TITLE
tried to replace my 'zero' key with [ , didnt work

### ISSUE THREAD

**Issue by rasit21** [randyrants/sharpkeys#407]
my numeric 'zero' key is not working , so i tried to remap it to [.

i have windows ten fully updated
can see some entries made in the my registry  but cant understand them

i use a asus s14.

can you please help me

**Comment by randyrants** [comment]
Asus Vivobook S14?  As a laptop, I have no idea how their NumLock system works, meaning that there's usually a collection of keys that only become the number keypad is Fn or NumLock or some combination of both are used.  That's a tall order, for the key to get pressed right and sent to Windows properly.  Might have to use Microsoft PowerToys or AutoHotKeys for this one.
