### ISSUE TITLE
Loved it! But...it doesn't work with MX Keys CMD/ALT to left of spacebar :( 

### ISSUE THREAD

**Issue by HTMLGuyLLC** [randyrants/sharpkeys#408]
When I push "Type Key" and then hit the left CMD/ALT button on an MX Keys keyboard, it doesn't recognize anything as being pressed. I LOVED this app on my old wired Apple Keyboard but now I'm stuck. Thanks for building it. If there's anything I can do to help fix this, please let me know!!

**Comment by randyrants** [comment]
Not much I can do for this: either the keys get to Windows or they don't.

Might want to give Microsoft PowerToys a shot: that's an active remapper and might have better luck,

**Comment by HTMLGuyLLC** [comment]
Sorry I should have updated this. PowerToys worked wonderfully. Thank you!
