### ISSUE TITLE
Mapping PrtSc

### ISSUE THREAD

**Issue by anprieto** [randyrants/sharpkeys#409]
Does anybody know how to remap the "PrtSc" key?
I'm trying to remap it to context menu key (=shift+F10), which my laptop does not bring.
Other than that, the app is fantastic!

**Comment by randyrants** [comment]
PrtScr is a triple-byte code so it cannot be mapped by SharpKeys; the Windows technology does not support it.

Please check something like Microsoft PowerToys or AutoHotKeys.
