### ISSUE TITLE
the Pause Break key remapping does not work

### ISSUE THREAD

**Issue by Galzor** [randyrants/sharpkeys#413]
i have tried remapping the Pause Break key, but it is not working. if i use the Type Key button for that, it shows up as Num Lock Key.
plz help asap. i need this to work.

**Comment by Galzor** [comment]
i found a hack also that cud work on here: https://stackoverflow.com/questions/38846347/what-is-the-scancode-of-pause-break-key
but i am unable to compile and build app to generate working exe from the source code provided. can u plz tell me how to do that or in what version of visual studio the code can be compiled.

**Comment by randyrants** [comment]
The issue here is Pause/Break is a triple-byte scan code - lots more about that in the FAQ - so it's not supported by SharpKeys.

Give Microsoft PowerToys a look as they likely have a way to remap this key.

**Comment by Galzor** [comment]
okay, i did made it work somehow via registry settings. thanks for support
