### ISSUE TITLE
question: How is SharpKeys different than Power Toys Key Manager?

### ISSUE THREAD

**Issue by tombohub** [randyrants/sharpkeys#414]
I am curious about the difference between the 2? How do they work? 
Thanks

**Comment by randyrants** [comment]
SharpKeys exposes a Windows Registry key that allows you to tell Windows what keys you want remapped; Windows remaps the whole key and the world continues to turn.

PowerToys is an active remapper, so it's actively doing things for you; this is how they are able to remap modified keys and support other keys that Windows does not.  

I did chat with the team when they were first spinning up, mostly around asks I've gotten that couldn't be supported by SharpKeys as well a few things to "look out for" that I had tripped over the years.  It's one of the reasons why I actively recommend them for anything SharpKeys cannot do.

**Comment by tombohub** [comment]
Cool, thank you for the answer!
