### ISSUE TITLE
Can not unmap Win+arrow keys ?

### ISSUE THREAD

**Issue by softlion** [randyrants/sharpkeys#416]
Those keys manage the placement of windows. I hate them and there is no option to disable  while keeping the functionality with the mouse ...

**Comment by randyrants** [comment]
SharpKeys does not remap modified keys - only whole keys.

That said, I don't know exactly what you're specifically looking to disable - or what version of Windows you're on - but go search for Snap in the Settings app in Windows 10 or 11 because I'm pretty sure most of this is disableable.

**Comment by softlion** [comment]
I don't want to disable snap. I need it, but using the mouse only. I don't need it with the keybard as it always triggers when i don't want it.

**Comment by randyrants** [comment]
Oh - I read that as after you disable it with keyboard, you never wanted to see it again with mouse.

Either way, SharpKeys cannot help.  Given that you're trying to remap a combo, I don't know that PowerToys will help either - might have to go to the more flexible but complex of the three: AutoHotKeys.
