### ISSUE TITLE
Pause button on 104 ANSI

### ISSUE THREAD

**Issue by Jimbodiah** [randyrants/sharpkeys#418]
Hello, just FYI/feedback

Trying to remap the Pause and Scrolllock buttons as volume buttons I noticed the pause button is seen as the same code as the NumLock button. When using the "press key"function to see what key is being pressed, it will give the same code. When I remap the Pause key, it will actually remap the numlock key and keep the Pause key the way it was.

The code it returns for both Pause and NumLock is "Special: NumLock 00_45"

Keep on rocking

And i too hit that capslock button 50 times a day. I have even put in an 80g click switch so that I can't press it as easily and will hear it when I do. Even then.... grrrrrrr....

**Comment by randyrants** [comment]
Thanks!

Pause is weird in that it gets trapped by something in the keyboard stack: I think it's because it's a double scancode value or something that was odd.  It was either that or ScrollLock - it's been a while since I've looked those keys.
