### ISSUE TITLE
Mapping PrtSc key does not work 

### ISSUE THREAD

**Issue by pogosama** [randyrants/sharpkeys#419]
I tried to map a key as a `PrtSc` key, but it seems that the `PrtSc` key is not recognized by SharpKeys. I chose the target mapping manually.  but still the `PrtSc` key is not triggered.
![image](https://user-images.githubusercontent.com/6615177/147608513-6913d47f-1bf7-4c9e-9218-3f3350f82bc7.png)

__Issue 1:__ When I tried 'Type Key', pressing `PrtSc` key is not recognized. Tried this with laptop keyboard and USB keyboard, both keypresses were not registered.

__Issue 2:__ After manually assigning `PrtSc` as target key (see screenshot above) and logged out and in again, pressing the source key does not trigger anything. I can test this by opening On-Screen Keyboard. No button lights up when I press the `Ins` key.

I'm using a ThinkPad laptop and Windows 10 OS.

**Comment by Diego74965** [comment]
Hi, you can try using PowerToys (https://docs.microsoft.com/en-us/windows/powertoys/install). It's a great alternative and allowed me to reassign keys that SharpKeys failed to reassign (in my case, pause/break) hope this helps you.

**Comment by randyrants** [comment]
^ this.
