### ISSUE TITLE
Wrong key detection

### ISSUE THREAD

**Issue by kisscoool18** [randyrants/sharpkeys#42]
This is the best remaper I've tested, still there are some issues.
I've spent some time testing and I've finally got the mapping I wanted, but not easily at all !
I've got a HP Elitebook 1030 G2 with W10 x64 up-to-date.
The problem with that laptop is that they replaced the media keys to "skype" keys that I don't need at all.
So I just wanted to remap theses specials keys to media keys (play/pause, next, etc...)
But Sharpkey (and other software) doesn't detect the right keys and won't let me remap them.

[Here is an array resuming my testings](http://nicoool.free.fr/Autres/Key%20ScanCodes%20on%20Elitebook%201030%20G2.PNG)

For 3 keys, there is a pattern :
- The last 2 bits of SharpKey detected key
- The first 2 bits of CheckScanCode detected key
- The last 2 bits of Sharpkey working key

But the strange thing is that for one key this pattern doesn't work completly...

I don't know if this helps but as I spent a lot of time, I wanted to share.

Have a nice day.

**Comment by randyrants** [comment]
One of two things is happening here: either the keys you're attempt to remap are hardware based and not getting passed to Windows or they are triple scancodes which will throw off successful remapping.

HTH!

**Comment by kisscoool18** [comment]
I didn't was clear enough on the point that at the end I could remap the keys using SharpKey, but I had to manuel guests the unknown and incorrectly detected key codes (last column in my array), so from my point of view it's neither hardware keys nor triple scan codes... What do you think?
