### ISSUE TITLE
1 by one bluetooth keyboard - FN Lock not working

### ISSUE THREAD

**Issue by francwalter** [randyrants/sharpkeys#420]
Hallo
I have a Bluetooth "Multifunction Keyboard with Touchpad" from 1 by one and with Windows 10 the Function buttons are switched. ESC is only pressed, when I press FN+ESC and each time, I forget the FN to press, I get my default browser with a new Home site, as the buttons upper mapping is the home icon.
All buttons are mapped only with FN as Function buttons. That is weird, I cannot get used to it, always I forget to press FN with ESC, which I use very often :(

So I found this app and hoped that it could disable that home button (instead of ESC) at least, but when I press it (the ESC / Home-Icon without the FN) I only get opened another Firefox with my Start page. I get this Popup, that SharpKeys cannot remap the key, not recognizing it:

> SharpKeys
>
> You've entered a key that SharpKeys doesn't know about.
> 
> Please check the SharpKeys website for an updated release

![grafik](https://user-images.githubusercontent.com/927269/148122612-4bec9c9e-daee-4bfb-8614-fb82d59896c7.png)

Can I do something about it, with SharpKeys or do I have to live with it?
I guess "an updated release" is not the right answer.

Thank you.
frank

**Comment by francwalter** [comment]
OK, I found [Key Remapper](https://atnsoft.com/keyremapper/) and with that it works, I just set that unuseful Home Button to ESC as well. The rest of F-Keys are not so important for me, maybe I will remap others as well.

**Comment by francwalter** [comment]
Unfortunately Key Remapper is some shareware app, which stopped working after some weeks :(
I uninstalled it.
The issue is still present then. I would reopen it if I could.

**Comment by randyrants** [comment]
There's no reason to reopen it: there's no way for SharpKeys to help with something like this as it's a modifier key combo and Fn isn't something that Windows can usually remap on its own.  Give Microsoft PowerToys or AutoHotKeys a try: they are active remappers and may yield better results.
