### ISSUE TITLE
Total Win key function disabled by mapping fn+F1 (junk filler Help "?" key) [Windows 11 on HP Envy]

### ISSUE THREAD

**Issue by fiscalia8** [randyrants/sharpkeys#421]
First, a THANK YOU: I just got a new HP Envy and am very thankful for sharpkeys to map the right Alt back to a Ctrl... who needs two Alt keys? ;)

Next, I need to do away with default map of fn-locked F1 key (decorated with a "?"), which when pressed forces Edge to open and pull up a "How to get help" bing search. Obtuse, useless, and annoying to a Firefox user. 

Thinking I'd be clever and map F2 to this fn+F1, since I use F2 constantly in Excel and Windows Explorer. However, the expected key selection "F-Lock: Help (E0_3B) does not result in a change to the default map of this key. Using your Type Key tool, reveals it's coded as "Special: Left Windows (E0_5B)". Unfortunately, that's identical to the only Win key available on my HP keyboard... Indeed, Type Key tool confirms that the Win key is also, "Special: Left Windows (E0_5B)."

Probably important to know, I am running Windows 11 now. Issue may be related to some subtle OS changes?

Appreciate your help!

![image](https://user-images.githubusercontent.com/39802328/150471962-69c445c1-f14a-46f2-8925-d62c8d52f93a.png)

**Comment by randyrants** [comment]
Glad the tool is working for you, for the most part!

For something like this, it's likely that the driver HP is using for the keyboard is intercepting the command and doing something with it; that it gets passed into Windows as Left WIN key is odd, but there's not going to be anything SharpKeys can do with this.  Windows is told it's the Windows key and that's all it knows.
