### ISSUE TITLE
ALT+CTRL+[num] shortcuts

### ISSUE THREAD

**Issue by Merrickman2003** [randyrants/sharpkeys#422]
I got a macro keypad and it outputs ALT+CTRL+[num] depending on which key is pressed, I'd use it but the windows shortcut keys are messed up and wont let me use ALT+CTRL to start them, when I put in this keybind on sharpkeys it says the key isn't recongnized. Could those be added, or maybe some option to add my own keybind?

**Comment by randyrants** [comment]
Not with SharpKeys: per the FAQ, modifiers are not supported.  Please try Microsoft's PowerToys or AutoHotKeys.
