### ISSUE TITLE
Assigning the function key?

### ISSUE THREAD

**Issue by ClandestineClout** [randyrants/sharpkeys#423]
I don't see the option to assign the function key. That is, the one you hold to enable the fn1 through 12 keys.

**Comment by randyrants** [comment]
Indeed, this key is called out in the FAQ: it's sometimes sent to Windows but more often than not, it is handled at the hardware level and Windows just sees "F1" or "whatever key F1 is when Fn is not on".

If it's not being picked up by SharpKeys, it's not going to be able to map it.
