### ISSUE TITLE
Alt key not recognized

### ISSUE THREAD

**Issue by gp1983** [randyrants/sharpkeys#425]
I have Logitech MX Keys  and Sharpkeys does not recognize the cmd/alt key, 

is it fixable ?

Thank you

**Comment by randyrants** [comment]
Not without owning the keyboard or knowing what message you get.  Generally speaking, if it doesn't work with Type a Key, it's not fixable but if there's a scancode coming through (other than 00_100) I can investigate.

Best bet is to use the Logitech software and see if they have something to install to support it, in Windows.
