### ISSUE TITLE
Idea: using 2 keyboards at the same time (with different layouts)

### ISSUE THREAD

**Issue by Tilko** [randyrants/sharpkeys#427]
Idea: add the possibility of using a second keyboard with a different layout.

**Comment by randyrants** [comment]
Not sure what you're asking for, with this one.  You do have the ability to Load/Save a whole set of mappings (which you can change per keyboard layout) so I would think that would cover it?

**Comment by Tilko** [comment]
Yes, I was not very clear: I should say using two keyboard at the same time, with differents layouts

**Comment by randyrants** [comment]
Thanks for the clarification but as there's no way for Windows to support the two keyboards at the same time, there's no way to enable such a configuration.
