### ISSUE TITLE
Office key

### ISSUE THREAD

**Issue by dubhlaidh** [randyrants/sharpkeys#428]
The new kinda crappy MS Ergo keyboard has a useless Office key that'd be great to remap.  It's E0_205B

![image](https://user-images.githubusercontent.com/10093926/152703574-27c9d819-90ef-43a4-9b66-9d58d24d9d30.png)

**Comment by randyrants** [comment]
Per the FAQ:
**Q: Type a Key shows a code that is E0_nnnn - can I remap this key?**
A: If a scancode has 6 characters, then it is what is known as a triple byte scancode which is something that cannot be remapped by the Windows Registry. To remap a key like this, you'll need an active remapper like Microsoft PowerToys or AutoHotKeys or the app that came with the keyboard (e.g. Logitech's Options) if available.
