### ISSUE TITLE
Calc Key on Microsoft Ergonomic Keyboard not Recognised.

### ISSUE THREAD

**Issue by AutomationStaff** [randyrants/sharpkeys#429]
Not quite sure why Microsoft did this. But the Calculator Key on their Ergonimic Keyboard is key code 00_100, and is not known about with the latest version of SharpKeys.

**Comment by vpnbig** [comment]
I have same problem with "a4tech" keyboard.
i get "00_100" in some keys, that open browser and go to search , home , back , forward , .... .
can you fix this ?

**Comment by vpnbig** [comment]
Q: Type a Key shows 00_100 - can I remap this key?
A: 00_100 is a catch all code that Windows reports when a key is captured by hardware or some other driver so there's no way to successfully remap that key, especially since multiple keys can return the same 00_100 code.
