### ISSUE TITLE
I entered a key that sharp keys doesnt know about???   Key (00_100)

### ISSUE THREAD

**Issue by GarrettBolin** [randyrants/sharpkeys#43]
I'm trying to disable volume and mute controls on my keyboard, on a lenova B40-30 running Windows 10. But those keys are not known by sharpkeys...

Key (00_100)

**Comment by randyrants** [comment]
Per the FAQ, some media keys simply don't get sent to Windows.  If they don't get to Windows they cannot be remapped by Windows.

HTH!
