### ISSUE TITLE
I can't mapp windows key

### ISSUE THREAD

**Issue by pawel0207** [randyrants/sharpkeys#431]
I tried to mapp it to every single key and it's not working :(

**Comment by tbrodbeck** [comment]
![image](https://user-images.githubusercontent.com/24418160/156343053-58c7a5f2-4001-4040-b28f-e3abadfdde3d.png)

I have the same problem on 3.9.3 and Windows 11 21H2. And I did writing and rebooting 🤔

**Comment by randyrants** [comment]
Interesting: it works OK for me.  Is it active with every application and Windows desktop or just some games?

Also, have you tried turn both Windows keys off, in the off event that the Left Windows key is not sending Left Windows?

**Comment by tbrodbeck** [comment]
Hey. I have tried the Right Windows key and it does nothing as well. 

After some more investigation I realized that this issue only occures when accessing the machine through Microsoft Remote Desktop. I have a Mac that I use to access a windows server machine. 
I just tried it with the local keyboard and the remapping worked.

Is it technically feasible to support remote keyboards? If yes, we could close this and I can open a nother issue to suggest to build in the feature to support this kind of remote keyboards?

**Comment by useforgh** [comment]
**Is it a Windows Terminal Server ?**

https://docs.microsoft.com/en-us/troubleshoot/windows-server/performance/toggle-terminal-services-application-server-mode


cmd:
Change user /query
to get the status

Change user /install
to change the modus to install

Now try to change the settings

after this 
change user /execute

Now test it

**Comment by tbrodbeck** [comment]
Hi. No I do not think so.
I have a simple enabled remote desktop in the windows settings.

```cmd
C:\Users\tillb>change user /execute
Install mode does not apply to a Remote Desktop Session Host server configured for remote administration.
```

**Comment by tbrodbeck** [comment]
Hmm.. My idea was to use one super key only for the host OS and not for the remote OS. But that does not work.

**Comment by randyrants** [comment]
Right - that's not something that's going to be supported by the key remapping tech that Windows has made available.

**Comment by tbrodbeck** [comment]
Okay thanks for clarifiying :=
