### ISSUE TITLE
SharpKeys 3.9.3: window scaling issue

### ISSUE THREAD

**Issue by d0vgan** [randyrants/sharpkeys#432]
I seem to have a window scaling issue with SharpKeys 3.9.3 under Windows 8.1 on my laptop. It was OK with SharpKeys 3.9.2. Please see the screenshots below:

SharpKeys 3.9.2 (OK):
![SharpKeys-3 9 2](https://user-images.githubusercontent.com/2848457/154430774-9042056e-097f-491b-a354-f1f2a6b2d996.png)

SharpKeys 3.9.3 (scaling issue of the main window and the dialogs):
![SharpKeys-3 9 3](https://user-images.githubusercontent.com/2848457/154430904-b6126f5e-42e6-42d5-baca-c74a908a6010.png)

**Comment by randyrants** [comment]
I took a look at the differences between 3.9.2 and 3.9.3: there definitely were changes made to the UI layer, all of them made to support Windows' high contrast mode and system themes.  As nothing else in the product changed, I would recommend using 3.9.2 if you are required to stay on Windows 8.1 and at whatever DPI you are currently using.: you are not missing out on any new features in 3.9.3.  

To be clear, Windows 8.1 support ended in 2018 and there's a viable workaround without feature loss, so I think you're unblocked.  As to fixing it, having the HC support in the product is higher on my feature list than backcompat support.  Trying to sort that out would mean getting some new "old hardware" to test it with on various gfx cards - as I can't trust a VM to scale correctly - which is a pretty hefty time sync.

Thanks for reporting it though - I'd rather know than not know!
