### ISSUE TITLE
Remap special key

### ISSUE THREAD

**Issue by mathias22osterhagen22** [randyrants/sharpkeys#435]
Hello !

I have an HP Wired desktop 320K Keyboard and wish to remap the "calculator" key to "pause/play" of media.

**On keycode.info I get this result:** 
![image](https://user-images.githubusercontent.com/60438474/156558064-34951b66-de1c-493e-8a6e-3a0ea9074bd3.png)

**Pointing to this keycode:** 
https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes?redirectedfrom=MSDN#:~:text=Application%201%20key-,VK_LAUNCH_APP2,-0xB7

**The key is not recognized in SharpKey:**
![image](https://user-images.githubusercontent.com/60438474/156558358-ec773f71-0f64-4a4f-affb-401b0203c9d7.png)

I tried multiple keys in the list already but nothing is working.
Is there a way to enter the byte code of the key directly? 

**Edit:** I tried to map E0_B7 and 00_B7 nothing is working even after logout/login

**Edit:** (Value seems to be available in the WParam and not LParam)
![image](https://user-images.githubusercontent.com/60438474/156559917-24ff4cdb-12a6-4548-90e6-ee4093a72c58.png)

**Comment by randyrants** [comment]
OK, so several things: first thanks for sharing your research in this!

Beyond that, the 00_100 is what WIndows is getting when that key is pressed and there's not going to be much to be done with it.  For example, the list of values you were looking up - VK_LAUNCH_APP2 - is a list of virtual keycodes which is value for some input across Windows but it's not the scancode value needed to remap the key.  Consider the letter A on a US keyboard: the virtual key value is 0x41 but the actual scancode is 00_1E.

Take a look at this list: https://github.com/l5l/Table-of-vk-and-sc-codes-keyboard-keys-and-mouse-buttons - the values here are 0nn which is 00_nn or 1nn which is E0_nn according to what I see in the scan code tables.  Based off this, if the HP keyboard is sending VK_LAUNCH_APP2 as virtual code 0xB7, the scan code would be 16B or "App: My Computer (E0_68)" in SharpKeys.

My guess, however, is that the actual scancode being sent is not E0_68 - my guess is that there's a driver component somewhere that is capturing the key and converting it to VK_LAUNCH_APP2 which allows the Calculator to open.  In my experiences, there's 4 or 5 levels of keyboard interaction that can intercept or modify a keystroke, and the Windows remapping tech is often at the mercy of all of them.
