### ISSUE TITLE
Issues with keyboard addition

### ISSUE THREAD

**Issue by Blackkoi99** [randyrants/sharpkeys#437]
Hi All,

I have a full sized keyboard and ive decided to add a mini keyboard with 6 key caps and i am wanting to repurpose the keys to act as num pad. The issue i am having is that when trying to map a key on the mini keyboard it is mapping as 123456 on the top row instead of showing up as the numb pad numbers. Is there any way to change this, the manufacturer is a Chinese brand and they have suggested i download their software but i do not trust the source.

Any help will be appreciated.

Regards.

**Comment by randyrants** [comment]
No matter how many keyboards are attached, they are all going to act the same way on both keyboards, so I'm not entirely sure what the 6 key caps are form a HW perspective, but they shouldn't matter.  It's just that if you remap a key on one keyboard - e.g. you remap the A key to be TAB - it's going to be TAB everywhere.
