### ISSUE TITLE
Suddenly some buttons stop work at all

### ISSUE THREAD

**Issue by SirodgevAlex** [randyrants/sharpkeys#438]
Hello! Suddenly 4 my buttons stop working. If i delete all maps and app, mine CapsLock still wont work. What should i do?

**Comment by SirodgevAlex** [comment]
Update all 4 buttons stop working, there are no keys in SharpKeys, Buttons work 100%

**Comment by randyrants** [comment]
If you have deleted all of the mappings, wrote the changes to the Registry and rebooted, you will have cleared any of the scancode remappings that Windows was making for you.
