### ISSUE TITLE
I cannot remap right alt key(EO_2038)

### ISSUE THREAD

**Issue by thinnling** [randyrants/sharpkeys#44]
It says " You've entered a key that Sharpkey doesn't know about"
Is there an update? I am running win7.

**Comment by ruskotron** [comment]
I'm also seeing this issue on Windows 10

**Comment by thinnling** [comment]
I actually solved the issue. I have windows 7 so I don't know if it works for 10 but I downloaded a package from [https://www.microsoft.com/en-us/download/details.aspx?id=17657](url) and installed it. It's from 2003 and I didn't think it would work for me but it had a program, remapkey.exe,  to remap my keyboard that worked for me.

**Comment by ruskotron** [comment]
@thinnling thanks, that worked a treat!

Interesting, that when I open SharpKeys then it shows the "Right-Alt" (E0_38) value you would expect, mapping to "Left-Alt", and the registry entries in `[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Keyboard Layout]` are exactly as I would expect.

So, I guess what's happening is the the fault lies with the *"Type Key"* feature of Sharp-keys. It's detecting some extended key that's assigned to right-alt, but the old `E0_38` code is fine.

As a workaround for SharpKeys you should select "Right-Alt" manually.

The resource-kit keyboard mapping tool is very nice though!

**Comment by randyrants** [comment]
Sadly, Type Key can't intercept the Alt keys when attempting to set a key.  The Alt scancode gets intercepted by Windows (and triggers the system menu) before my little Windows knows about it.  For the Alt keys on a keyboard, they must be selected by hand in the list.  I do this on my Lenovo laptops, remapping Right-Alt to the Application key.
