### ISSUE TITLE
Add new key E0_205B

### ISSUE THREAD

**Issue by lholota** [randyrants/sharpkeys#441]
Feature request for a new Microsoft Curve keyboard which comes with an extremely useless key which starts the Office Hub by default and can't be changed using the official software. It would be really cool if this key could be mapped to something else and/or disabled. Right now SharpKeys reports it's not known and cannot map it.

The key code reported by SharpKeys is E0_205B.

**Comment by randyrants** [comment]
Per the [FAQ](https://github.com/randyrants/sharpkeys#additional-faq-and-answers):
**Q: Type a Key shows a code that is E0_nnnn - can I remap this key?**
A: If a scancode has 6 characters, then it is what is known as a triple byte scancode which is something that cannot be remapped by the Windows Registry. To remap a key like this, you'll need an active remapper like Microsoft PowerToys or AutoHotKeys or the app that came with the keyboard (e.g. Logitech's Options) if available.
