### ISSUE TITLE
add fn key not working

### ISSUE THREAD

**Issue by pablosguajardo** [randyrants/sharpkeys#442]
add "fn" key not working in Dell inspirion 5510

**Comment by randyrants** [comment]
Per the [FAQ](https://github.com/randyrants/sharpkeys#additional-faq-and-answers):
**Q: Why can't I remap my Fn key on my [notebook or Apple] keyboard?**
A: Some keys simply just never get to Windows. In the case of most Fn keys, they are interpretted by the hardware and never get passed onto the OS, no matter how they appear to work... if Windows doesn't see the key, there's no way for the key to be remapped by Windows.
