### ISSUE TITLE
Please read the FAQ before posting a request/problem/question!

### ISSUE THREAD

**Issue by randyrants** [randyrants/sharpkeys#443]
Sorry if this sounds cranky, but it's really for your benefit than mine: please read the [FAQ's](https://github.com/randyrants/sharpkeys#additional-faq-and-answers) before posting a new Issue here.

I don't mind the traffic or interest for new things - that's welcomed.

It's not that I mind the having to copy/paste the same content and link over and over, since the question is already answered on the main page.  It's a waste of time but I can get past that, but

I really feel bad for people that post the question and then have to wait for me to reply before they get an answer, when [the answer is already waiting for them](https://github.com/randyrants/sharpkeys#additional-faq-and-answers)!

**Comment by hwich** [comment]
Can't remap to F keys. Is it problem with my device only or...
