### ISSUE TITLE
"Delete Al" should be "Delete All"

### ISSUE THREAD

**Issue by wenfangdu** [randyrants/sharpkeys#444]
![image](https://user-images.githubusercontent.com/28700378/161018734-4a9623a3-c7eb-4536-a1c2-09598649fb30.png)

**Comment by randyrants** [comment]
There are several things clipping here - it looks like the window is being told to use a monospaced font while the window is sizing itself based off what Windows is telling it to do.

Not seeing it when using other system fonts or in high contrast mode, so I'm not likely to do anything with this one.
