### ISSUE TITLE
Keychron C2 Microphone Key Remapping

### ISSUE THREAD

**Issue by reonan404** [randyrants/sharpkeys#446]
Hello! I am using a Keychron C2 keyboard and there is a key I am trying to remap, but the program is saying that it is "Special: Left Windows (E0_5B)". 

By default, the key tries to open Microsoft Teams (it is right above the Home key between the print screen and lighting keys). Is this key remappable? 

Thank you very much in advance for your time!

**Comment by randyrants** [comment]
Not much SharpKeys is going to be able to do with this.  I can handily remap the left Windows key but if there's something other than Windows getting pressed... it's sounding like there's some driver trapping the key on the way through Windows to open Teams and it's letting a Left WIN come through.  Might want to see if there's an app from Keychron (as there is from Microsoft and Logitech for their HW) or give something like AutoHotKeys a shot.
