### ISSUE TITLE
Joystick support

### ISSUE THREAD

**Issue by rohitghali** [randyrants/sharpkeys#451]
I have a device which windows recognizes as a joystick. Tried a lot in sharpkeys. Didn't work. Always detects any key as 00_100(which is in your faq). Later I did a lot of investigating and found JoyToKey. Works like a charm. Why not integrate joystick keys also into sharpkeys? I'm sure most of the people's 00_100 errors are related to windows recognizing as joystick keys.

**Comment by randyrants** [comment]
Actually, no: 00_100's come from hardware keys more than anything else.  Like volume up/down or media keys (like picking or hanging up a phone).  It is true that Joystick input does not go through the keyboard stack - most go through XInput - which means that Windows isn't going to remap them for anyone.
