### ISSUE TITLE
Running Sharpkeys 3.9.4 does not display an active window

### ISSUE THREAD

**Issue by limqjoo** [randyrants/sharpkeys#452]
Running the application doesn't seem to throw any error, yet there is no active window displayed:

![image](https://user-images.githubusercontent.com/1697436/163666736-e85fc60e-703b-42d3-bb08-cab1beb62f80.png)

This is the window preview I get when hovering over the app in the taskbar:

![image](https://user-images.githubusercontent.com/1697436/163666764-292673c0-abe8-4e76-af19-6c03dcd4ac57.png)

I'm on Windows 11 Home (x64).
I tried both the msi and zip. This issue happened for both.

Would appreciate any troubleshooting advice. Thanks in advance!

**Comment by randyrants** [comment]
Basically, the "re-open the window in this location and this size" is unhappy.  If you are OK with working with the Registry, please open it up and go to this location:
`HKEY_CURRENT_USER\Software\RandyRants`
Delete the SharpKeys Key.

This will get you back up and running but curious as to how it got into a bad state.  Was this an upgrade?

**Comment by Antechamber** [comment]
@randyrants For more info on reproduction, this bug appeared on my system after I:
1. launched SharpKeys, on a multimonitor setup,
2. exited SharpKeys
3. disconnected from the external monitors without logging out
4. relaunched SharpKeys

The temporary fix for me was to hover over the app in the taskbar, right click on the preview that pops up, then click "Maximize"
