### ISSUE TITLE
Please add multimedia key keyboard fortrek k7 plus

### ISSUE THREAD

**Issue by lucastoledo95** [randyrants/sharpkeys#453]
Hello, I ask that you kindly add the key as shown in the image, this key does not exist because it is for multimedia keyboards

![image](https://user-images.githubusercontent.com/14190798/163736908-2762f063-a91d-4f8e-afa1-880cb5dcab91.png)

**Comment by randyrants** [comment]
Please read the FAQ, with regards to 00_100 scancodes: https://github.com/randyrants/sharpkeys#additional-faq-and-answers
