### ISSUE TITLE
Skipped keys in Win10/Win11

### ISSUE THREAD

**Issue by tharmstrong** [randyrants/sharpkeys#454]
I've installed this great tool in two Dell Inspiron notebooks, one using Win10 the other Win11. In both cases, after installing, configuring some keys and rebooting, the following phenomena happens:

1. While typing at normal/high speed, about 10% of keystrokes are skipped. 
2. If you write slowly, like 1 key per second, there are no writing issues
3. If I connect an external USB keyboard, it works fine - I mean the external keyboard does not skip keys, but the internal notebook keyboerd continues skipping keys. 

This is so annoying I had to uninstall Sharpkeys - very sad indeed.

**Comment by randyrants** [comment]
Um, uninstalling the app wouldn't matter.  SharpKeys has no service that stays active and if the app itself isn't open, it's completely and totally dormant.  The only thing it does do is expose a Registry value on a specific Key that Windows then uses to remap keys on a keyboard.  

No idea why missing keys would come into play, if Windows is actively remapping the keys, but it sounds like there's something weird in your laptops, possibly some Dell driver or app that is actively colliding with the Windows remapping tech.  Sorry it didn't work out better for you.

**Comment by tharmstrong** [comment]
Funny you don't even want to investigate the issue... 
Ok.

**Comment by randyrants** [comment]
I'm not you're asking me to investigate here.
- My app is only active when you run it; it does not have a background mode or service component.
- My app modifies two Registry keys: one that the app owns, to save Windows location/size, and one that Windows uses to remap scancodes.
- I do not own the source of the Windows tech that remaps the keys; I also have never heard of this problem before, going back to the first beta of this app in 2004.

Given the above, I still went on to offer some possibilities to explore, like trying to see if there's another app or driver running on the PC that is causing a conflict, but beyond that I have no idea what else I can offer.

**Comment by tharmstrong** [comment]
Oh, now I understand.  Sorry to bother.

**Comment by randyrants** [comment]
No worries!
