### ISSUE TITLE
Alt+Gr not working yet (key is recognized, but cannot be mapped)

### ISSUE THREAD

**Issue by mawg** [randyrants/sharpkeys#455]
As per your request "should enable the ability to remap Alt+Gr. What I don't know is if it works or not, so if you successfully or unsuccessfully remap the Alt+Gr key, please let people know in the Issues section" - I can confirm that it does not work on my laptop.

- launch Sharpkeys  
- click "Add"  
- click "Type key"  
- popup appears, "You pressed (E0_1F38)"  
- click "OK"  
- popup appears, "You've entered a key that Sharpkeys doesn't know about"  

If I can help, please let me know. If not, and you consider this important, you could probably pick up a keyboard with Alt-Gr cheaply in eBay or from AliExpress (from US $4)

**Comment by randyrants** [comment]
Thanks for replying - forgot I had this ask on the home page!

Sadly, since Alt+Gr is a triple-byte code, it cannot be remapped with this tech.  You can successfully remap the key with Microsoft Power Toys.
