### ISSUE TITLE
Map LWin to LCtrl/RCtrl side effects

### ISSUE THREAD

**Issue by wenfangdu** [randyrants/sharpkeys#457]
When mapping LWin to LCtrl/RCtrl, occasionally the LCtrl/RCtrl is never released.

Repro steps:

1. Swap LWin and RCtrl.
2. Lock the screen.
3. When typing the password on the login screen, use the physical LWin + Backspace to delete the password.
4. Login with the correct password.
5. Open a webpage in Chrome.
6. Use the mouse to scroll _without_ pressing Ctrl.
7. The webpage is zoomed in/out (100% reproducible on multiple Windows computers).
8. Result: RCtrl is never released.

Try the above steps with the native LCtrl/RCtrl (no SharpKeys mappings) will not have this issue.
N.B. I found mapping LWin to RCtrl is more reliable than to LCtrl, yet RCtrl has this issue too.

OS: Windows 10 
SharpKeys: v3.9.4

**Comment by randyrants** [comment]
I admit that I've seen this happen with Edge [Chromium based] and Outlook, where I am not holding the CTRL key but when I scroll with the wheel, it will zoom in/out until I click somewhere else which clears state.

I am not able to repro this on Windows 11 - I only tried twice but it seems like as straight forward bug - but it seems to be reproducible on Win10, but either way, I'm sorry to say there's nothing I can do with it.  I don't control the remapping or the state of the keys within Windows; I'm just exposing a Registry key that Windows then uses to remap keys.

Might want to give Microsoft PowerToys a try: their remapper is a standalone bit of code and stays acting throughout your session.  They may handle the remapped CTRL key better than the Windows one does.

**Comment by wenfangdu** [comment]
@randyrants Just found out that the result varies if using different keyboards with the same sharpkeys config. My laptop keyboard doesn't have this issue, but my external keyboards do. And there're issues that my external keyboards don't have but my laptop keyboard does XD.

**Comment by wenfangdu** [comment]
I've fixed this issue with the following AHK code, which won't block scrolling:

```
MButton::return
```
