### ISSUE TITLE
How do I  use "Ñ" key ?

### ISSUE THREAD

**Issue by barbozabarb** [randyrants/sharpkeys#458]
Hello I need to asign a Ñ to a regular key, but I couldn't find it in the list?

Is there something that I missing, or where should I add the line in the code to grant this feature?
Because I've watched some of the code but I am kinda lost 

In Dialog_Main.cs 
I've found this 

`  private void BuildParseTables()
        {
            if (m_hashKeys != null)
                return;

            // the hash table uses a string in the form of Hi_Lo scan code (in Hex values) 
            // that most sources say are scan codes.  The 00_00 will disable a key - everything else 
            // is pretty obvious.  There is a bit of a reverse lookup however, so labels changed here
            // need to be changed in a couple of other places
            m_hashKeys = new Hashtable();
            m_hashKeys.Add("00_00", "-- Turn Key Off");
            m_hashKeys.Add("00_01", "Special: Escape");
            m_hashKeys.Add("00_02", "Key: 1 !");
            m_hashKeys.Add("00_03", "Key: 2 @");
            m_hashKeys.Add("00_04", "Key: 3 #");
            m_hashKeys.Add("00_05", "Key: 4 $");
            m_hashKeys.Add("00_06", "Key: 5 %");
            m_hashKeys.Add("00_07", "Key: 6 ^");
            m_hashKeys.Add("00_08", "Key: 7 &");
            m_hashKeys.Add("00_09", "Key: 8 *");
            m_hashKeys.Add("00_0A", "Key: 9 (");
            m_hashKeys.Add("00_0B", "Key: 0 )");
            m_hashKeys.Add("00_0C", "Key: - _");
            m_hashKeys.Add("00_0D", "Key: = +");
            m_hashKeys.Add("00_0E", "Special: Backspace");
            m_hashKeys.Add("00_0F", "Special: Tab"); ...
etc`

I though that I could just add the line that I wanted to use that include the ñ key, but then I realize that this is just the messeges that pop up, whenever I imput a key isn't that right?

Then I went to this function 
`        private void btnFrom_Click(object sender, System.EventArgs e)
        {
            // Pop open the "typing" form to collect keyboard input to get a valid code
            Dialog_KeyPress dlg = new Dialog_KeyPress();
            dlg.m_hashKeys = m_hashKeys;
            if (dlg.ShowDialog() == DialogResult.OK)
            {
                if (lbFrom.Items.Contains(dlg.m_strSelected))
                    lbFrom.SelectedItem = dlg.m_strSelected;
                else
                {
                    // probably an international keyboard code
                    MessageBox.Show("You've entered a key that SharpKeys doesn't know about.\n\nPlease check the SharpKeys website for an updated release", "SharpKeys");
                }
            }
        }`

But also, then I realize that System.EventArgs just receivess the value, and I can't press "ñ" key because it does not recognize it.

Any advice ?
Thank you very much!

**Comment by randyrants** [comment]
For an Ñ key to be supported, it would need to be a standalone key and the scancode would have to be in the list.  If it's not in the list, it's an unknown key, but still should be reporting the scancode.

**Comment by barbozabarb** [comment]
Thank you for the reply, it does recognize it, but a different key 

I own a keyboard that includes the "ñ" key, so when I press at it, it receive it as ";"

I was hoping that the "tag" that is attach with the different keys such  "00_04", "00_0E", were some kind equivalent of an ASCII code, like, when you press ALT +165 you get "Ñ", 
It is possible to manage this problem with something like this?
