### ISSUE TITLE
Hi, my Alt Gr key that displays E0_2038 is not known about by Sharpkeys

### ISSUE THREAD

**Issue by Liberator00** [randyrants/sharpkeys#460]
Hi, 

Sharpkeys says this key is not known about. The number displayed is E0_2038. 

I did a windows reinstall. And before, I didn't have this problem. Only after reinstall. 

Any idea how to fix ? 

Thank you,

**Comment by randyrants** [comment]
There's not: Alt+Gr is a triple-byte scancode and the Windows tech that remaps the keys doesn't support them.  I had it in the list at some point but it only worked like 10% of the time.

Give Windows PowerToys a shot: their remapper is more active and should handle this easily.
