### ISSUE TITLE
(00_29) Spanish keyboard "You've entered a key that Sharpkeys doesn't know about"

### ISSUE THREAD

**Issue by bbdever** [randyrants/sharpkeys#463]
Hello,

I've read the FAQ and Googled but cannot find an answer to this.

I've used SharpKeys in Windows 10 and it worked great, but it stopped working after Windows 11 upgrade. 

So I installed the latest version and when I try to map a button on my Spanish keyboard, it says "You've entered a key that Sharpkeys doesn't know about". It didn't say this before in Windows 10.

I am trying to map the º button to <

![image](https://user-images.githubusercontent.com/29453934/168036872-ddb5a6df-de44-451a-83f9-ac3eafd47f25.png)

Thank you.

**Comment by randyrants** [comment]
Closing this as it's been over a month.
