### ISSUE TITLE
Your software is fantastic! Just a little bug

### ISSUE THREAD

**Issue by Deus-nsf** [randyrants/sharpkeys#467]
Honestly I just wanted to praise your soft because it is an absolute godsend for games that doesn't have rebind or only partial rebind.

I did find a little bug though, the F10 key (at least on my keyboard) is not being registered when I want to remap a key to F10, despite my F10 key working just fine, of course selecting the F10 key manually in the list works just fine, but at least it gives me a valid reason to praise the software in the github issues tab!

**Comment by randyrants** [comment]
Thanks!

Could be that F10 is not getting to Windows for some reason, if it's a "special" keyboard with dual-function F keys or a laptop keyboard or if there's some other driver installed.  If it's working after it's selected in the list, then that's great but no idea why Type Key wouldn't see it.

**Comment by Deus-nsf** [comment]
I have the Keychron K5 (last revision to this date) it's this keyboard: https://www.keychron.com/products/keychron-k5-ultra-slim-wireless-mechanical-keyboard?variant=39559178846297

It's a very good keyboard I like it a lot! F10 has a multimedia bind to "mute" if you press the fn key, maybe Keychron's driver has some special sauce to it.

**Comment by SHHSSH** [comment]
Have loved this software for years, I believe it has problems with keyboard languages/regions though.

Brilliant @randyrants \.

**Comment by randyrants** [comment]
Cheers!
