### ISSUE TITLE
Unknown scancodes within a Swiss German QWERTZ keyboard

### ISSUE THREAD

**Issue by 68cme** [randyrants/sharpkeys#470]
Hi,
I'm a French user of a Swiss German keybord, and want to remap the key ö to é. Unfortunately, I can't find the keycode used for this. Any idea? The initial key should be 00_27, also known as OEM_3. But how to specify the new target for é? Thanks.

**Comment by randyrants** [comment]
00_27 should be in the list already but no idea what the é is.  It would have to be a "full key" and not like a CTRL+ALT+E or something like that.  There should be some mappings of Swiss German keyboards that has a scancode to it (or its en-US scancode equivalent.
