### ISSUE TITLE
I accidently got rid of my key

### ISSUE THREAD

**Issue by Bannerlordz** [randyrants/sharpkeys#471]
i accidently deleted my key (o with dots) and i don't know the name of the key cause it doesn't show the actual key. can someone please send me the name of that key thanks

**Comment by Bannerlordz** [comment]
alt combinations doesnt work i tried it btw

**Comment by randyrants** [comment]
No idea which key you mean or if you deleted it from an existing mapping or you accidentally disabled it.

Alt combinations aren't supposed to work: only whole keys are enabled per the FAQ.
