### ISSUE TITLE
keyboard re-mapping not passing through from physical host to virtual machine connection using rdp store app

### ISSUE THREAD

**Issue by myusrn** [randyrants/sharpkeys#474]
The sharpkeys configured keyboard layout re-mapping works on my physical machine but not on my w365 cloud pc or other virtual machine setups when i connect to them using the remote desktop store app [ https://apps.microsoft.com/store/detail/microsoft-remote-desktop/9WZDNCRFJ3PS?hl=en-us&gl=US ].  

If i connect to them using the remote desktop client x86 64-bit desktop app installation [ https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windowsdesktop#install-the-client ] the sharpkeys configured keyboard layout re-mappings assigned to my physical host keyboard do work on those remote host sessions.

Ironically, and frustratingly, mouse button re-mapping does not pass through when using msft remote desktop x86 64bit client install and does pass through when using msft remote desktop store app install. 

Any thoughts on why that might be? Presumably the msft remote desktop store app needs to be fixed to allow keyboard layout re-mappings to pass through?  And likewise for the msft remote desktop x86 client install in case of mouse button re-mappings.

Fyi, I'm applying msft ergonomic keyboard right side context menu key to right side windows key mapping and lenovo enterprise laptop keyboard right side print screen key to right side windows key mapping.  For mouse buttons i'm have left and right mouse buttons swapped to cover left handed mouse use.

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Keyboard Layout]
"Scancode Map"=hex:00,00,00,00,00,00,00,00,03,00,00,00,5c,e0,5d,e0,5c,e0,37,e0,\
  00,00,00,00

**Comment by randyrants** [comment]
Not a clue. I've been using the Store based Remote Desktop for a long while now and my local remappings seem to pass through OK but since I often have the exact same keys remapped everywhere (especially Caps Lock) if something went wrong, it would take a while.  I did just try the Home key (which is remapped from F9 on a laptop) and that did get passed in externally so it should work, but of course, it's up to Windows, the remote client and/or the VM host.

**Comment by randyrants** [comment]
Yeah, that sounds very weird - I'm sorry I don't have anything else to offer on this one.
