### ISSUE TITLE
Keybindings not respected in VS Code editor

### ISSUE THREAD

**Issue by KatlehoJordan** [randyrants/sharpkeys#475]
Hi.

I used SharpKeys to remap `Esc` to `CapsLock` and vice versa.

The remapping works everywhere except in VS Code.

I found tips to add `"keyboard.dispatch": "keyCode"` to my `settings.json` file for VS Code, but with or without this setting seems to make no difference: the SharpKeys remapping is ignored within VS Code.

Tips?

**Comment by randyrants** [comment]
I just tried it with Caps Lock disabled, and VS Code was fine.  Is there some other mapper you have active at the same time or a change to shortcuts made in VS Code itself?

**Comment by KatlehoJordan** [comment]
Closing. I think this has to do with some VS Code extension conflicts. I can no longer reproduce the undesired behavior.
