### ISSUE TITLE
MSI Files Past 3.5 Don't Run on 32-bit Windows 10 (Intel Atom)

### ISSUE THREAD

**Issue by DerpyBubblez** [randyrants/sharpkeys#478]
I downloaded every MSI file, the only one that would run is the one for version 3.5.
Everything else opens a window that says "This installation package is not supported by this processor type. Contact your product vender."

**Comment by randyrants** [comment]
Odd.  In my testing, it worked on x86 or x64 in the past, but it has been a while.  Might be the MSI package in VS2022 doesn't respect the flag anymore.

Anyway, the ZIP file includes an EXE that runs on x86/x64/ARM/ARM64, if you want the most recent versions.
