### ISSUE TITLE
Can I know where this app write to regitry?

### ISSUE THREAD

**Issue by TriggerDude** [randyrants/sharpkeys#480]
I want to manual key cause I need to use Numpad, but numlock can switch numpad from number to some function, but this app only change the Key not the function

**Comment by randyrants** [comment]
I'm not sure I follow, since the Registry Key this uses will only ever remap the whole key anyway.  There is a whole write up on my blog: https://www.randyrants.com/2004/01/keyboard_remapp/

**Comment by randyrants** [comment]
Right.  So, knowing the Registry Key won't help because the app doesn't do the remapping - Windows does based off the Registry setting.  Either way, that post has all the information I gather before I put it into the app.
