### ISSUE TITLE
Unknown key on the Logitech MX Keys for business (E0_2038)

### ISSUE THREAD

**Issue by GarethBlain** [randyrants/sharpkeys#481]
I've just got the UK Logitech MX Keys (keyboard) and the right alt(/cmd on mac. Double labeled on keyboard) is being reported as an Unknown key. When I use the "Type Key" it comes up with (E0_2038). On the keyboard it's labeled as [CMD/alt(gr)]. The CMD is for Mac so the "alt" (and maybe (gr)?) must be for windows. :)

Here is the pic of the UK keyboard from Logitech's site. It's the key to the right of the space and left of the FN key. :)

![UK Logitech MX Keys](https://resource.logitech.com/w_692,c_limit,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/logitech/en/products/keyboards/mx-keys/gallery/deu-mx-keys-gallery-npr-graphite-front.png)

**Comment by randyrants** [comment]
It's a Mac keyboard.  Please see:
- https://github.com/randyrants/sharpkeys/issues/52
- https://github.com/randyrants/sharpkeys/issues/157
- https://github.com/randyrants/sharpkeys/wiki/Using-an-Apple-Magic-keyboard

**Comment by GarethBlain** [comment]
Not entirely true. This is a Windows AND Mac Keyboard (hence the windows "Start" key and "cmd" key). It's specifically designed for windows and mac. Unlike the Magic Keyboard (which I also have) which gives the same keys out for both Windows and Mac this one does give the correct key layout for both.
The issue is not that you can't map to it (as I have following the manual instruction it told me to do when it told me to report this to you!) the issue is that Sharpkeys doesn't have it as a known option for some reason.

Maybe a better fix in the app would be to tell people using these multi device keyboards that you don't intend to add this mapping's description and not to bother reporting it. To save all these tickets wasting time. 🙂 You don't want people assuming all missing keys you ask them to report are actually something like this that is a known issue and not bothering to inform you so you can better your amazing software!

Keep up the good work!😁
