### ISSUE TITLE
Mini KeyPad

### ISSUE THREAD

**Issue by Bumblebee001** [randyrants/sharpkeys#483]
Can SharpKeys be use to re-assign the keys of a USB Mini KeyPad? I have 2 identical 7-Key Mini Kepads and both register their keys as 1-7. So programming/ assigning one to a specific function in a software (eg jOrgan; Hauptwerk) will automatically assign the corresponding function to the other. I need one Mini KeyPad to register as, say, A-G. 

(I hope that the main keyboard used to type is not effected..... I suspect it will be if the task is possible).

**Comment by randyrants** [comment]
Windows can only remap keys based off their scancode values and if the mini-keypad is sending the same scancode as the main keyboard, nothing much to be done.  Might want to try AutoHotKeys or PowerToys for other options.
