### ISSUE TITLE
Request to add unlisted key mapping

### ISSUE THREAD

**Issue by mobeeniqbal** [randyrants/sharpkeys#484]
Hi.
I'm using a UK keyboard and it has a mute key which the app doesn't know about. 
Remapping the listed mute key doesn't seem to have an affect on the button. Could you please add it to a future release? The key code is 
(00_100)
Many thanks.

**Comment by randyrants** [comment]
00_100 is a catch all for keys that is not sending a unique scancode.  Please read the FAQ for more.
