### ISSUE TITLE
Having disabled backslash key the Left Shift +  no longer works

### ISSUE THREAD

**Issue by BritCard** [randyrants/sharpkeys#486]
Weird one.

Having disabled backslash (next to left shift) ISO extra key (00_56) the left shift +  no longer works. 

Left shift works with every other key, just not F.

**Comment by randyrants** [comment]
I don't follow what's mapped for this: what does Left Shift + mean?  Can you post a screenshot?

**Comment by BritCard** [comment]
Shit sorry. 

It's supposed to say left shift + F but obviously it's not working so it didn't type. 

I used the app to disable the backstroke key (ISO extra key 00_56) but for some reason at the same time Left shift + F stopped working. Left shift works with every other key, and the F key works fine on it's own. But if I try to do capital F with the left shift nothing happens, not even a lower case F.

**Comment by randyrants** [comment]
Odd.  I mean, people ask for this type of support all the time, but seeing as the Windows tech that is actually remapping the keys doesn't support combination keys, there's no way that SharpKeys could have set the Registry in a way that would block this.  It could have remapped Shift or F (or both) but not the combination for Shift+F.

You might want to remove all mapping from the SharpKeys windows, save it to the Registry and reboot.  That will have cleared anything that Windows was remapping for you.  If it's still happening, check for something that is trapping the key, like PowerToys' Remapping option or some other app running that is intercepting the keystroke.
