### ISSUE TITLE
Alt gr is not recognized 

### ISSUE THREAD

**Issue by xBLOCK-HEADx** [randyrants/sharpkeys#487]
Hi, this issue was brought up back in 2017. https://github.com/randyrants/sharpkeys/issues/1

the Alt gr key gives E0_2038 and is not recognized by Sharpkeys. It's not in the list either as far as i can see.

Special: Right Alt is E0_38, which I assume is for a "normal" right alt key. 

In fact, when Alt gr is pressed it sends both an alt and ctrl message and is in effect just a shortcut for those keys. In other words, pressing Left Control and Alt will do exactly the same thing.

Personally, what i'd like to be able to achieve is to remap alt gr to a normal right alt so that the additional Left ctrl is not sent.

If only Sharpkeys would recognize the Alt gr, there's a chance I might be able to do this.

**Comment by randyrants** [comment]
Triple-byte scancodes are not supported by the Window tech that is remapping the keys.  You'll need an active remapper like Microsoft PowerToys or AutoHotKeys.  The FAQ has more on this.

**Comment by xBLOCK-HEADx** [comment]
Thanks, I got around the problem by changing my keyboard layout to US QWERTY - Alt gr functions as a normal Right Alt.

**Comment by randyrants** [comment]
You could remap that key now too, since both Alt keys are double-byte :)
