### ISSUE TITLE
remap multiple keys via the Registry

### ISSUE THREAD

**Issue by nzb15555196162** [randyrants/sharpkeys#490]
1 I current have a file named 'Scancode Map' in Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Keyboard Layout
2 now that I want to remap another key, I am not sure how to do so is sharp key support it?

**Comment by randyrants** [comment]
SharpKeys allows you to remap as many keys as you want, without going into the Registry.  I recommend you stay out of there.

Per your other post, combinations of keys are not supported.  You can remap the Windows key or the Up-arrow key but not you cannot remap the combination of Win+Up to be a new key.
