### ISSUE TITLE
Backspace key remaping failed !

### ISSUE THREAD

**Issue by ManoMomen** [randyrants/sharpkeys#491]
### Is it supported to remap the backspace key?
I have 3 keys on my laptop keyboard that stopped working, so until i can change them i tried to use SharpKeys App to remap them, firstly the backspace key...
I'm trying to remap it to (_Application-Menu_) key or to (_Num/_) key but it doesn't work the remapped key still doing its original action 
any support?

**Thanks in advance**

**Comment by randyrants** [comment]
I have no idea what you're trying to do here.  If you want another key to be backspace, you remap from -> to.  For example, if you want the Application Key to be Backspace:
```
From: Application Key
To: Backspace.
```
Not sure why Num / is coming into play here.

**Comment by ManoMomen** [comment]
hi again, I'm not sure which part in my issue wasn't clear enough
but anyway ...
the issue that i already doing it right but it didn't work i don't know why, after many rebooting it worked !!
thank you
