### ISSUE TITLE
Reset key mappings (ctrl key)

### ISSUE THREAD

**Issue by FilipNajj** [randyrants/sharpkeys#494]
I have messed up by remapping both my ctrl keys. I usually need to press on ctrl alt del to unlock my computer, but now I can't. I still have access to the command prompt and I can open regedit.exe. But that's basically it. Is there anything that I can do to remap my ctrl keys to back to default?

**Comment by randyrants** [comment]
If the CMD window can run as admin, then you should be able to open Regedit: navigate to HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Keyboard Layout, delete the Scancode Map value, and reboot.

If you only have a CMD window you can try:
reg delete "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Keyboard Layout" /v "Scancode Map"
and then reboot.

**Comment by FilipNajj** [comment]
I found the solution by opening the on screen keyboard using windows key and U. There is no Scancode Map value.
