### ISSUE TITLE
Cannot type with the key I mapped anymore

### ISSUE THREAD

**Issue by cothyish** [randyrants/sharpkeys#495]
Hi

I used Sharpkeys to change my dot key on my num pad to a comma    which was working well until I discovered that my comma key is not working anymore. On any keyboard type   language   and even with Shift or Alt    there is nothing thats working   no apostrophe or anything (as you can see I replaced the comma in this message by spaces). I tried deleting the key mapping and rebooting but nothing worked. When I deleted the key mapping    the dot key on my num pad came back to a dot    but my comma key still does not work.

Is there something I can do?

Thank you very much in advance.

**Comment by vfede** [comment]
i have a similar problem, how to reset the registry to clean up everything? Sharpkeys shows no mapping.

**Comment by randyrants** [comment]
If SharpKeys isn't showing any mappings when it starts - and you've saved and rebooted after changes - then there is nothing stored in the Registry that Windows is using to remap things.  Might want to try the keyboard on another PC, just to confirm that the key itself is not broken.

Another thing to check is if you have any other keymapper installed and active, like PowerToys or AutoHotKeys.  Others have installed all three and while they play well with each other, it leads to unexpected or unpredictable results.
