### ISSUE TITLE
how to remap key  to FN+KEY 

### ISSUE THREAD

**Issue by ayman77s** [randyrants/sharpkeys#497]
how to remap the Key  to FN+KEY

**Comment by randyrants** [comment]
You can't directly remap modified keys.  However, you may be able to remap a key to whatever key the Fn+key may be, if the key gets passed to Windows.  For example, on my Surface I mapped:
- F2 to Mute
- Mute to F2

This effectively remaps key1 to Fn+key1 and Fn+key1 to key1.
