### ISSUE TITLE
Apple Keyboard

### ISSUE THREAD

**Issue by FredLackeyOfficial** [randyrants/sharpkeys#5]
I'm really anal about installing on my dev box.  So, I hope you don't mind a pre-install question.

Will this solve the issue of keys from the Apple keyboards not following the same 104 key layout?  For example, the Apple keyboard has the following keys above the arrow keys:
`**<FN>** <HOME> <PG UP>`
`<DEL> <END> <PG DOWN>`
... when they should be... 
`**<INSERT>**<HOME> <PG UP>`
`<DEL> <END> <PG DOWN>`
Thanks, in advance.

**Comment by randyrants** [comment]
Possibly but not likely.  Fn keys are the absolutely most unpredictable of all the keys on modern keyboards.  It's listed in the available keys, under Special, but there's no guarantee that will work.

The Fn key is often a hardware key, meaning that it impacts the key codes being sent from the hardware, sometime even before the driver gets a hold of it.  For example, Fn+Backspace on an Apple keyboard will actually send the ScanCode for Delete and the driver won't have a clue as to what the hardware did to create that keystroke.  Just means that in this case, Fn could never be remapped successfully.  

Still, in other cases, Fn can be remapped.  Kind of a try it and see.

**Comment by FredLackeyOfficial** [comment]
Used it to remap the F13 key immediately above it.   Not so bad.

Thanks!

**Comment by randyrants** [comment]
That would work 👍

**Comment by artyfarty** [comment]
I actually use this app for years just for that - to use apple keyboards properly. I also swap Cmd <=> Ctrl keys (despite readme saying that swapping is not possible).
