### ISSUE TITLE
Global vs per-user?

### ISSUE THREAD

**Issue by DreymaR** [randyrants/sharpkeys#500]
Hiya! Thanks so much for a wonderful tool that simplifies registry remapping greatly!

From my manual remapping days I remember that you could do remaps globally or per user, through these keys:
```
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Keyboard Layout] 
[HKEY_CURRENT_USER\Keyboard Layout]
```

The "Scancode Map" subkeys are the same format for both keys. According to my notes, any Current User mappings take precedence over the Local Machine mappings.

One handy thing about the Current User mappings is of course that you could have one user account with a remap and others without it, for instance if you need a specific remap but not always and it's a hassle to run SharpKeys to load/unload it. Or if your partner uses your computer and doesn't want any remaps.

Could you add this functionality to SharpKeys? A simple radio button would do the trick, I think.

**Comment by randyrants** [comment]
Nope.  Over the years, I've played with this root node, but it doesn't reliably work version to version, so I've kept it out of the project.
