### ISSUE TITLE
<lock computer> key

### ISSUE THREAD

**Issue by KamiyaMinoru** [randyrants/sharpkeys#503]
I have a keyboard with <lock computer> key
https://www.sanwa.com/cn/wp-content/download/guide/GSKBERG3_manual.pdf

Anyway if I try to have SharpKeys to recognize it will mis-judge that key as <Left Win>.
So I can not change the function of that key.

Thanks.

**Comment by DreymaR** [comment]
Sometimes, special keys on keyboards actually doesn't send one key code but a combination. Maybe yours sends `Win+L` for instance, which would lock the computer. But that key combination cannot be remapped by registry remapping which is what SharpKeys uses: SharpKeys can only map single key codes to other single key codes.

There is a `Special: Power (E0_5E)` key that may do something similar to what you want, but it isn't always respected in my experience. It seems your keyboard doesn't use that code?

**Comment by randyrants** [comment]
Lock key presses are not passed through to Windows as a normal key would - it is intercepted and the machine gets locked - so there's no way for Windows to remap it.

PowerToys may be able to do something with it, as it has an active remapper, or there might be software from the original keyboard company (as Microsoft offers a Keyboard and Mouse app.)
