### ISSUE TITLE
help with mapping windows emoji key on right side of msft compact designer keyboard

### ISSUE THREAD

**Issue by myusrn** [randyrants/sharpkeys#504]
The right side of the [microsoft compact designer keyboard](https://microsoft.com/en/accessories/products/keyboards/microsoft-designer-compact-keyboard) has a windows emoji key, i.e. alternative to winkey + '.' keyboard shortcut.  

I want to make it a right side winkey (E0_5C) instead.  In current microsoft store installed sharpkeys 3.9.4 the "Type Key" keyboard keycode capture functionality sees this key as (E0_205B) and then when you click OK presents dialog stating `You've entered a key that SharpKeys doesn't know about. Please check the SharpKeys website for an updated release. OK`.

Can we get a SharpKeys update that has microsoft designer compact keyboard `Special: Emoji (E0_205B)` support?

**Comment by randyrants** [comment]
Sorry, but triple-byte codes cannot be remapped, per the FAQ:
**Q: Type a Key shows a code that is E0_nnnn - can I remap this key?**
A: If a scancode has 6 characters, then it is what is known as a triple byte scancode which is something that cannot be remapped by the Windows Registry. To remap a key like this, you'll need an active remapper like Microsoft PowerToys or AutoHotKeys or the app that came with the keyboard (e.g. Logitech's Options) if available.

**Comment by myusrn** [comment]
Thanks for the response. The microsoft mouse and keyboard center software, offered when I pair that keyboard, supports key remapping. My hesitation to using that is if it operates by setting up yet another background service that can impact battery life on my 2in1 where i use this keyboard. I explore the other options you proposed, thanks.

**Comment by randyrants** [comment]
Sure, but aside from the built-in Windows remapping tech, everything else will have some code running.  PowerToys, AutoHotkeys, Microsoft's K/M SW - everything will include some bit of code to run.

**Comment by myusrn** [comment]
Sounds like hooking keyboard input is happening on so many fronts that it is most likely a very well optimized bit of system functionality.  One might expect the respective processes would [ / should ] be doing nothing unless and until a keyboard combination they registered to be notified about arises.
