### ISSUE TITLE
Remap a key to open a software

### ISSUE THREAD

**Issue by BeastCodZ** [randyrants/sharpkeys#508]
Is it possible to map the key to open a software/program

**Comment by randyrants** [comment]
Sorry, no - Windows doesn't support it, so SharpKeys cannot.  There are other tools you can use for this like AutoHotKey and PowerToys.

**Comment by DreymaR** [comment]
Actually, there may be but it may be I'm sitting on obsolete info? They aren't much used anymore I think, but the scan codes SC16B (e0 6b) and SC121 (e0 21) used to work. They're named Launch_app1 (My Computer) and Launch_app2 (Calculator).

Testing them now didn't work but they used to. And you could specify in the Registry which apps they launched.
