### ISSUE TITLE
Map E0_1F65

### ISSUE THREAD

**Issue by tank-au** [randyrants/sharpkeys#51]
Hi

Extremely impressed with Sharpkeys.

I have a new HP Elitebook 1030 G2 and have problems with the END key and its position.  Unfortunately, the HP needs a function key with right arrow to produce END  :-/

I have two keys on the function row I would like to map to replicate END key.  The icon displays a phone answer and phone hang-up.   When I map keys by pressing the key  (E0_1F65)  I receive a message "You've entered a key that SharpKeys dosn't know about."

Is there a way to map this code (E0_1F65) to END?

Thanks for your help.

Thomas

**Comment by randyrants** [comment]
Thanks!

Those are triple byte codes so are often extremely awkward to remap.  In fact, I think the only triple byte key that got successfully plugged through this process was Print Screen or Pause/Break - every other attempt to hook up other keys has gone sideways.

I'll leave this open in case any contributing engineers wants to pick up the work.
