### ISSUE TITLE
remapping non working spacebar

### ISSUE THREAD

**Issue by premorob** [randyrants/sharpkeys#511]
I attempted to remap the non-working spacebar on a Lenovo laptop to the right Alt key. It didn't work. Spacebar fail appears to be hardware as it works on screen or using a USB keyboard. 

Am I doing something wrong? I used Special Space (00-39) to Special Right Alt (E0-38).

**Comment by hedrickdocks** [comment]
try doing it in reverse, switch Special Right Alt (E0-38) to Special Space (00-39) instead

**Comment by premorob** [comment]
Awesome, thank you so much. Worked.
