### ISSUE TITLE
There's no tilde in us-keyboard 

### ISSUE THREAD

**Issue by gromeirocn** [randyrants/sharpkeys#512]
Hey,

First of all, very nice job on this software!

I'm trying to use sharpkey because in my keyboard layout there's no tilde (~) and I need to use an English keyboard, but with tilde on it. Could you add the symbol so I can remap a key?

**Comment by DreymaR** [comment]
That's not how SharpKeys works, if I understand you right. SharpKeys can send a key code. It's the OS (such as Windows) that translates key codes to symbols.

So unless your active OS layout has a tilde – or you happen to be running a special layout program like my EPKL – there is no way SharpKeys could produce a tilde for you.

Unless you meant the Tilde key itself? That's another name for the Grave key, which in SharpKeys is named `Key: `~ (00_29)`.

**Comment by randyrants** [comment]
Closing based off DreymaR's comments.  Will re-open if there's more information.
