### ISSUE TITLE
Can't change RWin to App (Context Menu)

### ISSUE THREAD

**Issue by mxk-ru** [randyrants/sharpkeys#518]
![image](https://user-images.githubusercontent.com/2724777/222508964-154218d2-ad8c-41a5-bad9-fb9b0406110e.png)
Does not work.

**Comment by randyrants** [comment]
Not sure what key that is but 00_5D is not the Application key.  Try selecting the key by hand, under "Special: Application (E0_5D)"

This will make the Right Windows key on your keyboard act like the Application key.

**Comment by mxk-ru** [comment]
Oh! Super! It works!
I found code 00_5D here https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
Issue is closed.

**Comment by randyrants** [comment]
Ah OK - that's a virtual key code that you can use to call the key through code.  Just an enum value :)
