### ISSUE TITLE
Can't map E0_2038

### ISSUE THREAD

**Issue by Bakipl** [randyrants/sharpkeys#52]
Hi 
i have Apple Keyboard connected to my Microsoft Surface Pro 3 , and there two issues:
- when I try to add new remap, and press LEFT ALT - on my oryginal surfce keyboard nothing shows up it dosen't recognise the event
- when I try to remap the mac keyboard, and change: right option (alt), it recognise it as: E0_2038  but I get info that sharpkeys, don't know that key, and can't remap to any other :/

**Comment by randyrants** [comment]
For the Alt keys, you'll have to select them by hand.

https://github.com/randyrants/sharpkeys#things-that-sharpkeys-will-do
