### ISSUE TITLE
hp envy bang & olufsen removed right control key and replaced with thumb print reader

### ISSUE THREAD

**Issue by brah-mcdude** [randyrants/sharpkeys#522]
can sharpkeys support a non-pressable key such as a thumb print key?
i really need my right side control key for all my shortcuts. 
i was hoping to replace this thumb print key with right control function. 
is that possible? 
is the thumb print key recognizable as a key at all?

**Comment by DreymaR** [comment]
Thumb print recognition is not handled by the keyboard DLL, so that's a no. It's not a key in this context.

**Comment by brah-mcdude** [comment]
then i'm going to return this laptop to the store ;(
closing...
