### ISSUE TITLE
not working on unofficial Windows 11 Ghost Spectre edition

### ISSUE THREAD

**Issue by ikaio** [randyrants/sharpkeys#523]
Hi, i recently installed a version of windows 11, called Ghost Spectre, and sharp keys just do nothing. I've already rebooted and my keys are still not remaped, can someone guide me?

**Comment by randyrants** [comment]
I am of no use on this: it's an organically slimmed down version of an official Windows build and I have no idea what they cut or should not have cut, to allow Windows to remap keys.  You can try something like PowerToys or AutoHotKeys.

**Comment by ikaio** [comment]
Hey @randyrants, I'm sorry, but can we debug this whenever you are free? I just tested it on the Win10 version of this edition and it worked fine. This is my last try, whatever you decide here i'll understand, but i need it so badly. Peace.

**Comment by ikaio** [comment]
Conclusion: There was nothing wrong with Sharp Keys, I was just being dumb and inverted the order of the keys when remaping.
