### ISSUE TITLE
Keyboard numpad and external numpad remap

### ISSUE THREAD

**Issue by nicofio** [randyrants/sharpkeys#524]
Sorry if my wording isn't corrrect, but i want to remap my external numpad and not the keyboard one, that impossible with sharpkeys because it uses the key signal sent by OS that interpretes both as the same, ¿Am I correct (or not at all but still cannot do it) or there is a way?

**Comment by DreymaR** [comment]
No, not that I know of, unless you write your own USB driver. The USB HID protocol as you have noted, simply transfers a scan code. The OS cannot distinguish scan codes by source, unfortunately.

**Comment by randyrants** [comment]
DreymaR has the right of it.  If it shows up as a Num Pad key, then you can remap both physical keys but there's no way that Windows will know it's a keyboard different from the built in one.
