### ISSUE TITLE
add E0_1F35 to key map

### ISSUE THREAD

**Issue by danielrdrigues** [randyrants/sharpkeys#525]
"You've entered a key that SharpKeys doesn't know about. 
Please check the SharpKeys website for an update release."

E0_1F35 =  ALTGR + /?

Error that I get trying to rebind the "/?" key on my keyboard. I want to be able to use ALTGR + /?  to use the \ character, because I use a keyboard with US layout and PT ABNT layout too.

**Comment by randyrants** [comment]
Sorry: triple-byte scancodes are not remappable by Windows.  Please give PowerToys or AutoHotKey a try.
