### ISSUE TITLE
Please add an unknown key i have

### ISSUE THREAD

**Issue by JaysonPhoenix** [randyrants/sharpkeys#527]
i just bought a keyoard and my left alt key is not properly recognized as alt, windows for example initiates the tab selection when holding alt+tab but when releasing it it doesnt switch to the selected tab but instead the selection screen stays open and i have to click a tab with the mouse. in games when chosing it as a new key for something it is recognized as left ctrl. in sharpkeys when adding a new key and using the type key function it is recognized as (E0_2038) and it says sharpkey doesnt know that key so i cant remap it to the proper left alt. so can somebody please add it to sharpkey or tell me how i could manually remap that key in the meantime?

**Comment by JaysonPhoenix** [comment]
after some research and stumbling upon old issues and requests i just realized that i guess the key in question is a "triple byte scancode" key, must have missed that in the faq section it says sharpkeys doesnt support these. and that from the keycode it seems to be a german alt gr which seems that this is a tricky one no matter what tool i try to use to remap. so i guess im screwed here and my request is obsolete. was looking for a quick simple solution not involving programming or something. if anyone found a not risky proper solution with not too much of programming involved let me know, otherwise i guess somebody can close this request.

**Comment by DreymaR** [comment]
Having AltGr on the left side is unconventional. Are there any images of your board you could link to?

Indeed, triple-byte scan codes are not supported. If you really want to do something with that key, you could use MS PowerTools or Autohotkey. But even with the latter I find it hard to work with AltGr. In Windows, this key sends a LCtrl+RAlt combo which is then turned into output according to the resulting shift states (6–7) in the system layout's mapping table.

Did you try treating it simply as a RAlt key?

I suppose you found this thread already:
https://github.com/randyrants/sharpkeys/issues/402

**Comment by JaysonPhoenix** [comment]
first off, the lower keys of most german keyboard look like this from left to right: Strg, Win-Key, Alt, Space, AltGr, Win-Key, Options-Key, Strg. so AltGr is not called Strg, Strg acutaly is the equivalent of Ctrl. Im not sure if theres a left strg and right strg version internally but the alt seems to be a left alt (at least games recognize it as such) and the options-key is like pressing the right mousebutton to show the cascade menu. so that being said, in the keyboard in question there is only a strg and a alt key on the left side and no 2nd versions of it on the right, and that alt key is not an alt key as it says but actually an AltGr so you can make @ signs and such with that keyboard because knowing the strg+alt combo to make @ signs is not common knowlage here, i just happen to know that and now through research because of that keyboard learned that internally pressing AltGr causes the system to act like i pressed ctrl+alt but is not recognized as such in every case since most games for example woult treat AltGr as right alt if not as AltGr but never as ctrl+alt, but in the case of this keyboard in games that alt key seems to be recognized as ctrl instead for whatever reason while windows still recognizes it as the common AltGr (for example in the tabbing behaviour where it would not open the selected tab when releasing the key but would keep the selection open and youd have to click on the tab or press enter to open it, which is pretty annoying). all pretty weird but that seems to be how it is. so since i know i can use strg+alt to make @ signs id say its not unconventional at all if theres only one alt key and its the AltGr version to rather have it a common alt key to have the ability to tab or to use an alt key in a game or to do the ctrl+alt+del combo for example and who ever made the keyboard just couldnt think of causing more problems with things that i cant do if that key is AltGr instead of alt just for the convenience of making at signs and such with a single key (which of course really is more convenient indeed and a good thing but only if you have 1 of 2 alt keys that way). heres a link of the keyboard in question: https://www.amazon.de/dp/B09WVR9VVP?psc=1&ref=ppx_yo2ov_dt_b_product_details

also i couldnt try if the treating it as right alt key would work like done in the thread you mentioned because for that i would have to first select the AltGr key from the left dropdown menu in sharpkeys and map it to left alt from the right dropdown to then after a reboot make it appear as a right alt on the left dropdown selection thing which somehow worked for that user. but i cant do that since after that thread AltGr got removed from the dropdown menus as it isnt supported anymore so i cant select it and the "press a key" option rather than selecting it from the menu recognizes it as (E0_2038) but then says that key is not known to sharpkeys so i cant select it that way either. seems like it was a bad decission to remove it from the dropdowns rather than just warning its unsupported and maybe link to an explaination mentioning that thread with that user that got it to work even tho its not supported, since now i cant even try workarounds and see if they happen to work in my case.

since its just a secondary keyboard to use from the couch while i still have my main keyboard in use most of the time i learned that its more complicated than i thought since it would be a better solution to only have the key changed on that specific keyboard while the keys on the main keyboard stay untouched, and that if id want it that way id have to use programms that keep running in the background rather than dealing with registry entries (which could be a good solution if sharpkeys wouldnt require me to reboot the pc to make the changes take effect but instead i could activate loaded presets on the fly with it so i could load a preset when i grab the couch keyboard and load the standard one when i grab my main keyboard again, which would other than autohotkey like solutions not cause any input delay because its changed on registry level), but then on the other hand could have latency issues in gaming for example and even other programs all have trouble with that specific key and it seems ro require more complicated stuff to deal with it which in turn have downsides too. i tried simple solutions like powertools but that didnt work at all (not for any key at all actually, couldnt find the reason) and i looked into AutoHotKey which is absolutely over my head but even that seems to have trouble with that key and id require combo solutions like AHI and such involving Interception drivers which in turn lock up the system if theres more than 10 HID devices connected which can easily happen with modern macro keyboards and such devices (i already have 6 right now), so even if i would understand the programming languages involved its not a good solution after all the work youd have to do for that. 


it just seems there is not really a good solution out there,.. but thx for looking into it and maybe this case shows that sharpkeys should put the AltGr key back in the dropdown menu list to atleast have a chance to make it work somehow for people how want a solution for their only keyboard in use or get the wanted advantage on the 2nd keyboard while sacrificing some advantage on the main keyboard.

**Comment by DreymaR** [comment]
I remembered incorrectly about Strg; it's the "Steuerung" key of course. Seems you have a oddish setup of (L?)Ctrl and (R?)Alt on the left side of Space, and no Ctrl nor Alt keys on the right side then?

But I thought that mapping the RAlt key to a LAlt would work? So, ignore the triple-byte scan code and just remap RAlt (E0_38) to LAlt (00_38). Did you try that?

**Comment by JaysonPhoenix** [comment]
yes on the new keyboard the lower keys are: fn, strg, AlrGr, Win-Key, space and some light settings keys and arrow keys. did the link to the keyboard with pics not work? should i down- and upload the pics?

so for that thread, if i understood it right then the user in the thread had to first set the AltGr key in the dropdown and then reboot to make the system recognize it as right alt to make it work, so no i didnt try when the thread said it is done that way and now not supported anymore. thought that would rule it out.

and to swap it the other way around on the main keyboard wouldnt work for that reason either i thought because i would have to select AltGr and even then i would have thought it wouldnt work. and of course because then id have the exact same problem on my main keyboard as i now have in the new keyboard, to have AltGr where i need a left alt for proper tabbing and games and key-combos. AltGr on the left side just is a no-go and id only need it for making @ signs and [ ] anyways which i could still do with alt+ctrl but for everything else its just in the way.

**Comment by randyrants** [comment]
Wow, busy thread.  And neat keyboard, based off the pictures.  I've read through it, but it's actually not clear to me what the ask is, so let me call out what I know:

- AltGr cannot be remapped with SharpKeys
- The light and color keys are very likely to be HW keys so they also likely won't remap because these keys aren't sent to Windows.
- More important than the language of the keyboard is the language of the keyboard, on the PC.  For example, the US and UK keyboard have a key in the upper left, next to the key for 1.  If it's a US keyboard it's ` ~ and if it's a UK keyboard it's ` ¬ but the can code is identical on both.  Meaning if you remap this key, you get ` ~ if the PC's keyboard layout is en-US you get ` ~ and if it's en-GB you get ` ¬.

**Comment by DreymaR** [comment]
>     * AltGr cannot be remapped with SharpKeys because,
>     * Windows doesn't support triple-byte codes, like E0_2038.

Indeed. But if you remap the RightAlt key, Windows should be able to work it out? Because that's what I do: I have a PrtSc key next to my AltGr, and I remap PrtSc (E0_37) → RAlt (E0_38) and vice versa to swap the two. If I try to "Type Key", the AltGr does indeed show up as E0_2038, so it is indeed a true AltGr.

It looks to me as if OP doesn't understand what I'm trying to say. To OP: No, you do _not_ have to first remap and then restart to remap again. I have no idea what gave you that impression. What you have to do is to select "Right Alt (E0_38)" from the "Map this key" selector box, instead of using "Type Key" which gives the useless result "E0_2038".

**Comment by JaysonPhoenix** [comment]
i see, thx DreymaR, i got that impression from the mentioned thread that made it sound to me like thats how it works, but if you say youre using it that way that explains it better and it should probably work for me that way too. i dont have much time at the moment and i dont have access to that new keyboard atm to try your trick, but i will try when i get time to and have the keyboad with me again. i guess that would fix that part of my problem, even tho as i said i learned that a better solution would be something to have that key changed on only the new keyboard with a program running in the background to manage that rather than changing it in the registry in general. sadly the tip to try powertools didnt work for some reason (it didnt change any key) so i could at least just open the program when using the new keyboard and close it when using the old one to quickly switch keys without rebooting. but yeah, your last comment helped a lot and thx for taking the time to try to help me out here, appreciate you ;)
