### ISSUE TITLE
Doesn't detect the alt gr key on my laptop keyboard

### ISSUE THREAD

**Issue by el4ctr0n** [randyrants/sharpkeys#528]
I'd like the alt gr key on my laptop keyboard to function as a ctrl key.
Sharpkeys doesn't detect the alt gr key when I press it.

Please fix it.
Thank you.

**Comment by randyrants** [comment]
From the FAQ:
**Q: Type a Key shows a code that is E0_nnnn - can I remap this key?
Q: Type a Key for AltGr shows a code that is E0_2038 - can I remap this key?**
A: If a scancode has 6 characters, then it is what is known as a triple-byte scancode which is something that cannot be remapped by the Windows Registry. To remap a key like this, you'll need an active remapper like Microsoft PowerToys or AutoHotKeys or the app that came with the keyboard (e.g. Logitech's Options) if available.

**Comment by DreymaR** [comment]
Try remapping the RAlt key (E0_38) from the choice box instead. That works for me.
