### ISSUE TITLE
Inconsisten FAQ

### ISSUE THREAD

**Issue by usernamefound** [randyrants/sharpkeys#529]
In the **Things that SharpKeys will do** section you claim that Sharp Keys can _Remap more than one key to one single key - e.g. you could remap every key on a keyboard to the letter Q_

When you scroll further down to read the FAQ, you say: 
_Q: Can I remap a combination of keys to one key?
A: Sadly, no. SharpKeys only remaps whole keys rather than a modified key. For example, you can remap Ctrl or C but you can't remap Ctrl+C to another key. That said, the [Microsoft PowerToys](https://github.com/microsoft/PowerToys/releases) tool does offer this functionality - you can learn more about their tool here: Microsoft PowerToys._

So which one?

**Comment by randyrants** [comment]
Um, both say the same things?

**Comment by DreymaR** [comment]
The first one says that you can remap several (single) keys to the same keys.

The second one says that you cannot remap a combination of several keys.

_Maybe_ the first one could've been a little clearer, by saying _Remap more than one (single) key to one (single) key_? Not sure that'd be neccessary though?
