### ISSUE TITLE
not able to swap " and ' 

### ISSUE THREAD

**Issue by liweys** [randyrants/sharpkeys#53]
I want to swap `"` with `'`,  `PtrSrc` with `(`, `Shift+PtrSrc` with `)`. 
Is that possible? Is it a limitation?

**Comment by randyrants** [comment]
That is not supported by the key remapping tech that Windows offers, since whole keys are remapped rather than modified keys.

**Comment by liweys** [comment]
Windows supports it, see ["Keyboard Layout Manager"](http://www.klm32.com/), but it is not able to swap `esc` and `capslock` (sharpkeys can) or `ptrsc` and `(` (neither can).
