### ISSUE TITLE
I tried remapping Right Ctrl to /? key but it remapped to ;:

### ISSUE THREAD

**Issue by gabsteinbachz** [randyrants/sharpkeys#531]
That is basically it, I remapped Right Ctrl (E0_1D) to /? (00_35) but when I press the key what the system gives me is ;:

**Comment by randyrants** [comment]
What language are you using for keyboard layout?

And I think the better question is, did the remapping work?  The physical keys don't move, but the value of the scancode may, similarly to how the en-US keyboard has 2 @ but the same key shows 2 £ on the en-UK keyboard layout is different.
