### ISSUE TITLE
Office 365 and Emoticon key

### ISSUE THREAD

**Issue by Hellgringo83** [randyrants/sharpkeys#532]
I use a Microsoft Ergonomic USB keyboard (Model 1878). There are two key driving me crazy. One is the office 365 key near AltGr and the Emoticon key between right ctrl and the office key. 
I always hit the office 365 key if I need AltGr which opens office 365 (I don't use and want).
Sharpkeys tells me for both keys the code E0_205B and that it doesn't know what to do. So can you please try to add this keys?

**Comment by randyrants** [comment]
Or you could download the software the Microsoft provides and do something else with the keys.  Likewise, AutoHotKeys or PowerToys can also help.

As DreymaR calls out, these are triple-byte scancodes that Windows does not support, when it comes to remapping with the built in technology.
