### ISSUE TITLE
Cannot map key to brace

### ISSUE THREAD

**Issue by developpeur-pro** [randyrants/sharpkeys#534]
Unable to map the Page Down key to generate an opening brace `{` (E0_1F0D). I get the following error message:
_You've entered a key that SharpKeys doesn't know about_.

No problem to do it with Power Toys Keyboard Manager.

**Comment by DreymaR** [comment]
Read the FAQ regarding three-byte scan codes, please.

**Comment by developpeur-pro** [comment]
Ok, sorry, I closed the issue

**Comment by DreymaR** [comment]
As the FAQ says and you also found out, PowerToys and other tools like AutoHotkey can do this. Registry remapping cannot.
