### ISSUE TITLE
Please help I can't type anymore, this segment is with voice to speech now I'll repeat with no voice to speech. <KpoLGeqase <KI cqant typoe qanympore. <KI cqant typoe po<Keqase

### ISSUE THREAD

**Issue by LeoIncognito** [randyrants/sharpkeys#535]
h9pow cpouLGD i fix th9is issue<K th9s h9qas reqaLGLGy impoqacted my expoerience with9 qanyth9inLG qand <KI cqant find qa spoLGutipon./fix pLGeqase h9eLGpo. Voice Speech, I also did everything like unmapping all the keys then write to registry I also troubleshooter, updated my driver, I went to registry and tried to solve it myself, and I really need help, Note, I didn't spill water on my keyboard. Thank you for your time. PS I think I'm screwed.

**Comment by DreymaR** [comment]
Did you do this:
* Run SharpKeys
* Press "Delete All"
* Press "Write to Registry"
* Press "Close"
* Restart your computer

**Comment by LeoIncognito** [comment]
yes

> Did you do this:
> 
> * Run SharpKeys
> * Press "Delete All"
> * Press "Write to Registry"
> * Press "Close"
> * Restart your computer

**Comment by JOJOyesyesyes** [comment]
oh no

**Comment by DreymaR** [comment]
I'm fairly suspicious of the "went to Registry and tried to solve it myself" bit. You did _of course_ back up your registry before tampering with it, _right_? Because then I'd try reinstating the backup, maybe. Then restarting. Then doing the above, again.

**Comment by LeoIncognito** [comment]
> I'm fairly suspicious of the "went to Registry and tried to solve it myself" bit. You did _of course_ back up your registry before tampering with it, _right_? Because then I'd try reinstating the backup, maybe. Then restarting. Then doing the above, again.

i was GoinG to but then the bacKup did not worK. As it was corrupted.

**Comment by LeoIncognito** [comment]
> 

I am wondering what you mean as I know what BIOS is but I don't know how to check it

**Comment by LeoIncognito** [comment]
Also I would like to add sometimes it gets better and gets worse. Like h = h9, g = G (right_shift), Right Arrow = *,  k = <K(left_shift), and all the other buttons included press the same thing like If I press 9 it outputs h9. As though my problem looks fairly weird because it changes severely, but ever since I used Sharpkeys I added Right Control = Q, because my Q key doesn't work and then I wanted to use that. But then I added something else and then tomorrow I come back and the problem came. I had ran SharpKeys Pressed; Delete All, Write to Registry, Close,
and restarted my computer. Still broken, I got a new Keyboard and it still is broken. Please Help, But I Don't think anyone is gonna read any of this, This is too long.

**Comment by DreymaR** [comment]
Oh, we read it. It's just very weird and I don't know what else to suggest at this point. Sorry.

**Comment by LeoIncognito** [comment]
I went through inside the keyboard and I fixed it myself with my friend
