### ISSUE TITLE
Assigning the W key to Q and E

### ISSUE THREAD

**Issue by Storymode19** [randyrants/sharpkeys#536]
Hi there,
It says in the FAQ that you can assign the whole keyboard to the letter Q if you wanted to. But how would you do that? 
I need to assign my Q, W, and E keys to all be W.  But when I make the first assignment the W key no longer is available to be assigned again.
How to get around this?
Thank you

**Comment by DreymaR** [comment]
You can assign multiple keys to be a key (in this case, W). It's still available after the first assignment, but you may have to select it manually in the `To this key` field if you have such a remapping already active.

**Comment by Storymode19** [comment]
> You can assign multiple keys to be a key (in this case, W). It's still available after the first assignment, but you may have to select it manually in the `To this key` field if you have such a remapping already active.
> 
> Just to be clear, have you tried to map
> 
> * Q to W
> * E to W
> * (W is already W)
> 
> Also, be advised that if you do this you should definitely assign some other keys to Q and E so as not to lose these letter keys. Otherwise you'll have no way to press Ctrl+Q for instance.

I was doing it the opposite from your example. Maybe that was the issue. I will post back if there's still a problem.
Thank you
