### ISSUE TITLE
Can't rekey F3 to ~/`

### ISSUE THREAD

**Issue by cuddlymudpuppy** [randyrants/sharpkeys#539]
I love SharpKeys and I previously used it because my Fn key is broken on my Windows Lenovo. Since I only use F3 for Minecraft, I've used SharpKeys in the past to remap F3 to the ~/` key. I read in the FAQ that Fn itself won't always rekey, which is why I only have done F3 and it's worked in the past.

My computer had to be reset and everything in my AppData folder was lost, so now I need to remap F3 to ~. However, it won't rekey no matter what I've tried. 

I set up the rekey in SharpKeys, save the key, and write it to the registry. I will get a message that the key mappings have be successfully stored to the registry. I have tried soft and hard restarts, logging out and back in, and a combination of it all. No matter what, ~/` won't function as F3. I've wiped the registry, deleted SharpKeys, redownloaded it again, all to no avail. I tried keying F3 to other keys on my keyboard, which also didn't work.

Can this be a problem with F3 itself? What else can I try?

**Comment by DreymaR** [comment]
Are you sure you did it the right way around this time?

> No matter what, ~/` won't function as F3.
This suggests that you want to map ~/ to F3, not the other way around. But above, you say the opposite. Is it just the description, or did something get swapped around for real?

**Comment by cuddlymudpuppy** [comment]
You are correct, I had the keys entered the wrong way around. Can't believe it was such a simple mistake! Thank you for your help!
