### ISSUE TITLE
Maping  E0_40xx and E0_39xx 

### ISSUE THREAD

**Issue by igieon** [randyrants/sharpkeys#54]
Hi all. I have hp x360 and volume up button stuck it i disable volume up button 
which is code E0_30, because i can't map E0_4030. After disabling E0_30 now code in type is E0_3F00.

I just want to get explain but i found it based on https://msdn.microsoft.com/en-us/library/windows/desktop/ms646280%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396

Because key is stucked in windows message is set bit 30 that key was pressed previously.

So probably it will be good put it note that if its message code E0_40xx    you need to disable E0_xx key.
Or if its code E0_39xx   that you need to disable 00_xx. Probably this explain issue #39

**Comment by randyrants** [comment]
Merged; I'll build an update to the EXE/MSI at some point.
