### ISSUE TITLE
Remapped key goes off at random times while using non-rebound keys inside Firefox.

### ISSUE THREAD

**Issue by SoggyBurritoVR** [randyrants/sharpkeys#541]
The key I remapped to trigger off randomly when using non rebound keys.
Seems to only happen inside the Firefox browser, tried this different browsers such as "Brave" but the issue does not trigger.

This really hinders the use of this software and the use of Firefox.

My Setting:
![image](https://github.com/randyrants/sharpkeys/assets/69495940/b293de04-1011-48ad-a889-b3a4356db5a0)

P.S. This happens with any "Map this key:" key I set.

**Comment by randyrants** [comment]
Sorry but my app doesn't do the remapping: it exposes a Registry Key that Windows uses to remap keys and even then, Windows remaps the key system-wide.  If your re-mappings are not working in FireFox and only FireFox, I think the problem is with FireFox.

**Comment by SoggyBurritoVR** [comment]
It must be a Firefox based issue, which is unfortunate.  

Unsure how I would go by figuring out what specifically about Firefox messes with the registry key override.  

Looking at it now, Firefox seems to also ignore the override when pressing the specified key.

I'll try to take a look if Firefox has it's own registry key that overrides whatever registry key your software modifies.

**Comment by MtnDewritos** [comment]
If you use a keyboard checker website in Firefox you can see that certain keys are reported incorrectly, this is not an issue in google chrome. 
Using this simple script you can see exactly which scan codes are reported in Firefox/Chrome:
<html>

<script>
document.onkeydown = function(e) {
    if (!e) var e = window.event;
    if (e.keyCode) keycode = e.keyCode;
    else if (e.which) keycode = e.which;
    alert(keycode);
}
</script>

<body>
</body>
</html>

**Comment by SoggyBurritoVR** [comment]
I used your suggestion MtnDewritos, and it shows the rebound key going off at random times when typing/using any key.

This only happens in Firefox.  

Really unsure what I can do to fix this issue locally, if you have any idea, please let me know.
