### ISSUE TITLE
Mapping HPs "Command Key" on HP Victus

### ISSUE THREAD

**Issue by JoeWiseman** [randyrants/sharpkeys#543]
Hi there,
I'm struggeling with the command key (looks like this ◊ but filled up). 
The key is not recognized when pressing the key on the remapping window.
Is there any way to get the "original keycode" for that key, so I'm able to remap it?

Would be very glad to be able to use this wonderful unused key ;-)

Regards
Joe

**Comment by DreymaR** [comment]
Not sure, but it seems to be a Fn key? Those don't give a scan code by themselves, but modify other keys.

In other words, there is no way to remap it by registry as it does not produce a key press event on its own. It's a hardware thing.

**Comment by randyrants** [comment]
Been asked several times before: they keys are not passed to Windows as something that is remappable so SharpKeys can't tell Windows to remap them.
