### ISSUE TITLE
Cannot disable function (f3) key!

### ISSUE THREAD

**Issue by pawan-poudel-github** [randyrants/sharpkeys#544]
I want to disable f3 key on my laptop but is not working, even after restarting at opening app as administrator.

**Comment by DreymaR** [comment]
The F3 key is remappable, its name is "Function: F3 (00_3D). You can map it to "Turn key off (00_00)" to disable it.

If your laptop has a hardware Fn key, your F3 key may be sending two different scan codes depending on the Fn state. If this is the case, you must figure out both scan codes to completely disable your key.
