### ISSUE TITLE
Right Alt + U is not working

### ISSUE THREAD

**Issue by OsmanBubba** [randyrants/sharpkeys#545]
Right Alt + U is not working as an input, it warned me about it doesn't exist on the app and asks me to check updates of the app, but I just downloaded the latest version, just few minutes ago... I think you should add these shortcuts and give ability of setting layouts by shortcuts like using Alt + any letter
![image](https://github.com/randyrants/sharpkeys/assets/144002639/2050c053-bfcc-4961-9e1b-99536565d71d)

**Comment by DreymaR** [comment]
You seem to be misunderstanding what registry remapping (and hence, SharpKeys) actually does.

A key sends a scan code when you press it. The Windows registry has a key that can turn that scan code into another; this is registry remapping.

It does not at all concern itself with combinations of keys, nor what output or effects a scan code leads to. It's stated clearly in the SharpKeys documentation that you cannot remap from a combination of keys, for this reason.

So no, not only cannot SharpKeys map RAlt+<key> to anything, the registry remap method that SharpKeys uses is completely unable to do such a thing.

You may use Windows PowerKeys, or a program based on AutoHotKey (such as the EPKL program) to achieve lots of more complex effects. That may be what you're looking for.
