### ISSUE TITLE
Shift+RightAlt+Delete stopped working after right side modifier swaps

### ISSUE THREAD

**Issue by eugenesvk** [randyrants/sharpkeys#546]
I have right modifier keys as: alt, appskey, control
I've swapped them to : control, alt, appskey

And it's mostly working just fine, (new)RightAlt+Delete works, but then
 - (any side)Shift+(new)RightAlt+Delete
 
 doesn't work, and I've checked via AutoHotkey or online keyboard tools that show key events that this key combo isn't even being recognized
Other keys continue to work fine: RightAlt+Shift+Insert/Home/End/PageUp
Also a the other combos with Delete also work fine, just the RightAlt+Shift

And before remapping, this Shift+RightAlt+Delete combo worked fine

Do you have any idea why that might be the case? (closed all keyboard/mouse related apps before checking)

Thanks!

[right.skl.csv](https://github.com/randyrants/sharpkeys/files/12512771/right.skl.csv)

**Comment by randyrants** [comment]
Can you add a screenshot of the setup you have?  SKL uploaded is fine, but bluntly, I'm not adding it to a PC's keyboard layout :)

**Comment by eugenesvk** [comment]
sure thing, here it is (added right Win as part of testing, but it has no effect as I don't have a physical right Win)


<img width="343" alt="sharex" src="https://github.com/randyrants/sharpkeys/assets/12956286/78933305-a79c-4195-b7a8-46a264f35cca">

**Comment by randyrants** [comment]
Could be the ordering: you map Application to Right Alt and the Right Alt to Right Ctrl and then Right Ctrl to Application.  Near as I can tell, it's circular based off the order.

Unless you explicitly need the Right Alt, try mapping:
- Application to Left Alt
- Right Alt to Left Ctrl
- Right Ctrl to Application

Alternatively, you can try moving the order of the re-mappings around: I actively remap one key to the other and it works OK but it's not circularly across three:
![image](https://github.com/randyrants/sharpkeys/assets/18704482/dae7dad3-1c44-4304-9f21-5c31c3878ebb)

**Comment by eugenesvk** [comment]
Thanks for the tips

I do need right alt as it's a symbols key different from left alt regular function (same with control, it'd be a waste to have it the same), so will check if a different order helps

**Comment by eugenesvk** [comment]
I've changed only 1 apps key to alt to try to avoid any ordering issues

<img width="320" alt="share" src="https://github.com/randyrants/sharpkeys/assets/12956286/f6719963-b69f-4ca8-811f-0d2d3e060781">

but the issue is the same - RAlt+RShift+Del doesn't register Del while it does work with Insert
