### ISSUE TITLE
backtick on French keyboard

### ISSUE THREAD

**Issue by chaperot-perso** [randyrants/sharpkeys#552]
Hi to all !
I am coding with French keyboard (sorry, I am French :p)
When coding, I need to use backtick ( ` )  or "accent grave".
This backtick is not easy to make on keyboard, It needs to press "alt gr" + "7" twice !
I would like to map an unused key to produce backtick.
A do not succeed with SharpKeys :(
Any idea ?

**Comment by randyrants** [comment]
PowerToys has a more active remapper: I'd give them or AutoHotKeys a look.

**Comment by DreymaR** [comment]
If you're interested in using AutoHotKey (AHK), you could also check out the EPKL program which has a lot of features you can use without trying to code them yourself.
