### ISSUE TITLE
Can't change mapping

### ISSUE THREAD

**Issue by iKowa1** [randyrants/sharpkeys#553]
I have a huge problem.

I was trying to change the mapping of my keyboard, but i ended up messing up. i had already restarted my computer and i wanted to change it back. but there was a problem, i never ended up instaling sharpkeys, so i had to do the admin password, but my admin password requires a letter that i dont have on the mapping.

if someone could help me open the program without the admin password that would mean the world.

**Comment by randyrants** [comment]
Except that the administrative rights are required to change the Registry key that Windows looks at for remapping the keys.  This is the case if you change the Registry setting by hand or use SharpKeys or another tool to change the value.

Sorry but there's nothing to be done here.

**Comment by DreymaR** [comment]
There should be a way to reset your admin password I think. Search for it.

https://support.microsoft.com/en-us/windows/change-or-reset-your-windows-password-8271d17c-9f9e-443f-835a-8318c8f68b9c
