### ISSUE TITLE
Can't map some keys

### ISSUE THREAD

**Issue by PlanetGizmo** [randyrants/sharpkeys#554]
I have four keys above the number pad that I can't map. When I try to map it a window pops up and says, "You've entered a key that SharpKeys doesn't know about. Please check the SharpKeys website for an updated release." I installed the latest version and still have this problem. What should I do about it?

**Comment by DreymaR** [comment]
Three-byte scan codes aren't mappable. It isn't SharpKeys that decides this, it's Windows itself.

This is clearly stated in the docs, iirc?

**Comment by randyrants** [comment]
> This is clearly stated in the docs, iirc?

It is, but there's a lot in the docs, I guess.
