### ISSUE TITLE
Can't make additional shift

### ISSUE THREAD

**Issue by Beepen** [randyrants/sharpkeys#555]
I have this compact keyboard and the page-up key is where the shift key should be. I want to turn page-up into a shift key because I don't need page-up. I want the right shift to keep it's right-shift function, so I'll have two right-shift keys. The following doesn't seem to work.

![remap keys](https://github.com/randyrants/sharpkeys/assets/155485191/dde0a426-870f-41f3-b438-1fca17ab998f)

**Comment by DreymaR** [comment]
The mapping itself looks workable. Have you tried other mappings and they work for you, so you know you're doing it right?

Maybe try it with 00_49 instead. Not saying it'll work but try it.

**Comment by DreymaR** [comment]
No, you're quite right. PageUp does have the scan code E0_49, and I've remapped it myself which worked just fine.

Sorry then, I'm out of ideas for now. Hope you find it out!
