### ISSUE TITLE
howto remap keys on steelseries apex 3

### ISSUE THREAD

**Issue by jasonx-dk** [randyrants/sharpkeys#556]
1 pt
its the funktion key next too r-ctrl.

for 20 years i used that button to RELOAD my rifle in all fps-games

and have now steelseries apex 3 installed.

now nomore reload,byebye apex if i dont find fix the 48 hours

i vould loove too change that funktionkey too > that < on left side at Z

but cant find any software there can doit .

anyone have a idea about my problem,there could help me

**Comment by randyrants** [comment]
Sorry but I'm not following the above request, but games don't always send their key presses through to Windows, so there's likely nothing much this app can do to help.  Maybe AutoHotKeys or PowerToys can help.
