### ISSUE TITLE
Win10 22h2. The Home, End, PgUp and PgDn keys cannot be reassigned.

### ISSUE THREAD

**Issue by orange11orange** [randyrants/sharpkeys#557]
After clicking Write to Registry and rebooting, there are no changes. Please help.

![001](https://github.com/randyrants/sharpkeys/assets/38175100/56aabd0a-7c20-4797-99a8-5106638eb1c0)

I'm trying to make a black keyboard work like a white one.

![b1](https://github.com/randyrants/sharpkeys/assets/38175100/366917cd-1718-4744-bd50-3947a17763a8)
![w2](https://github.com/randyrants/sharpkeys/assets/38175100/22fb1b0a-c10d-4d7c-b94c-3272cf22b4b5)

**Comment by DreymaR** [comment]
I can confirm that your key codes look right, and the Win version is okay afaik.

Can you confirm that these are the codes you get if you use the "Type Key" functionality when adding a mapping?

**Comment by orange11orange** [comment]
> Can you confirm that these are the codes you get if you use the "Type Key" functionality when adding a mapping?

Hello! Thanks for the answer. If I press the keys rather than select them, it turns out the same as above - after saving the changes to the registry and rebooting, the scheme does not change.

![001](https://github.com/randyrants/sharpkeys/assets/38175100/a3b120ef-95f9-4d6b-a852-ad60658b0885)

**Comment by randyrants** [comment]
Nothing much can be done with this one as it's all set up right.  Likely the non-working keyboard is doing something under the covers that is changing the scancodes.
