### ISSUE TITLE
map mouse key

### ISSUE THREAD

**Issue by MusashiLun** [randyrants/sharpkeys#558]
I want to map left key into left click of mouse and map right key into right click of mouse to play game, because my mouse glitch. Can you please add this feature?

**Comment by DreymaR** [comment]
No, he cannot (unless I'm mistaken). SharpKeys uses Registry remapping, and Microsoft hasn't included mouse buttons as remappable keys to my knowledge.

**Comment by randyrants** [comment]
Indeed, mouse keys are way outside the scope of what this tool can do with Windows remapping technology.  Please give PowerToys a look.
