### ISSUE TITLE
Missing key

### ISSUE THREAD

**Issue by buttrash** [randyrants/sharpkeys#559]
There is no Option for airplane key or the wifi key, please add them thanks.

**Comment by randyrants** [comment]
There is no such key in Windows, so it more than likely cannot be mapped.

What is the scancode when you type this key in Type Key?

**Comment by buttrash** [comment]
im not sure

**Comment by buttrash** [comment]
i dont have the key on my pc

**Comment by buttrash** [comment]
my goal is to turn off wifi with a single click from my keyboard

**Comment by randyrants** [comment]
Nothing this app can help you with: this is about leveraging Windows ability to remap one key to another - you'll want to find something that can have a single key fire a macro in Windows, like AutoHotKeys or maybe PowerToys.

**Comment by buttrash** [comment]
can u please help me find a way im sorry i know it isnt ur job but im desparate

**Comment by DreymaR** [comment]
You're right: It really isn't their job!

Try this though:
https://learn.microsoft.com/en-us/windows/powertoys/
