### ISSUE TITLE
buttons have the same code

### ISSUE THREAD

**Issue by muhammed12314** [randyrants/sharpkeys#56]
n when i press a key it give me that code (00_100) then when i press ok it tell me that sharpkeys doesnt know anything about it

**Comment by randyrants** [comment]
Which keys are these?  If they are special keys - like Web, Search, Back, etc - then Windows cannot remap them.  They are getting intercepted by a driver and telling windows 00_100.

**Comment by muhammed12314** [comment]
The keys are (O,L,f5,left Ctrl, left win., right alt)

**Comment by randyrants** [comment]
Definitely nothing SharpKeys can do for that.  I've seen this happen with specialized keyboards, but overall if SharpKeys is getting nothing but 00_100 for all keys, there's no way for Windows to remap them.
