### ISSUE TITLE
On remapping super key, copilot key stop working

### ISSUE THREAD

**Issue by rverma-dev** [randyrants/sharpkeys#562]
On my Lenovo IdeaPad 5, if I map to replace super key with left ctrl, my copilot key stop working.
It works till I create: `Special Left Ctrl(00_1D) -> Special left windows (E0_5B)`
but as soon as I create reverse entry i.e. `Special left windows (E0_5B) -> Special Left Ctrl(00_1D)`, the copliot key stops working.

**Comment by randyrants** [comment]
They Copilot key cannot be remapped by SharpKeys which should mean that no amount of remapping can impact the function of the Copilot key.

Sorry but there's nothing much I can say for this one.
