### ISSUE TITLE
Bottom of UI windows are cut off, can't press ok button to remap keys

### ISSUE THREAD

**Issue by thehikaniko** [randyrants/sharpkeys#563]
![Screenshot 2024-05-23 193309](https://github.com/randyrants/sharpkeys/assets/170608003/a5663d8c-1e0d-4909-a8b6-c6547e49b9f2)

I tried changing my display sizing from1218x684 to 1280x720 to see if that was causing any problems but still had the same issue.

**Comment by randyrants** [comment]
Can you confirm what build you're running?  It looks like an older one compared to what I'm seeing on Windows 11:
![image](https://github.com/randyrants/sharpkeys/assets/18704482/8b83d826-d184-4cd7-a35a-c4b2af609a17)

**Comment by thehikaniko** [comment]
double checked and It's definitely the latest version

**Comment by randyrants** [comment]
What is your current DPI setting for display?
