### ISSUE TITLE
`LWin` to `F13` isn't recognize by other software.

### ISSUE THREAD

**Issue by xmaxrayx** [randyrants/sharpkeys#564]
Hi thanks for the software <3.
remap my `Lwin` to 'F13' but software can't see it.

software test it  :
- blender
- flowlouncher

please note software above support F13.

my small Fix was using AHK with this wired logic

```
#Requires AutoHotkey v2.0
#SingleInstance Force

F13::F13
````

and everything all software now detected the F13 normally, is it possible to fix this issue without AHK?

I remapped my `Capslook` -> `f14` and software recognize it without AHk.

![image](https://github.com/randyrants/sharpkeys/assets/101531362/95a038a9-e624-4f86-9a1e-1990053ff211)

**Comment by DreymaR** [comment]
Now, that _is_ strange.

What does the AHK Key History reveal about the difference, if any, between pressing your F13 and F14 keys?

**Comment by randyrants** [comment]
> And what happens if you do it the other way around (Caps -> F13, LWin -> F14)?

This is the very question I'd have.  I haven't remapped the left Windows key very often, but I have remapped right Windows for years and haven't had to do anything else.  Of course, I also don't remap anything to F13 or F14 either, so not entirely sure.

**Comment by xmaxrayx** [comment]
@DreymaR 
@randyrants 

Hi thanks for replay <3, yeah it's strang emy laptop did hard start (Real shutdown + Start) due to my laptop battery go 0% and after that everything work flawlessly and the listed software recognize it well without AHK , maybe I was should restart my pc before posting but I did log-out.

this current AHK logs : (not when the problem was found) 


````
VK  SC	Type	Up/Dn	Elapsed	Key		Window
-------------------------------------------------------------------------------------------------------------
28  150	 	d	0.11	Down           	
28  150	 	u	0.09	Down           	
28  150	 	d	0.09	Down           	
28  150	 	u	0.09	Down           	
26  148	 	d	0.47	Up             	
26  148	 	u	0.11	Up             	
26  148	 	d	0.08	Up             	
26  148	 	u	0.11	Up             	
26  148	 	d	0.08	Up             	
26  148	 	u	0.09	Up             	
26  148	 	d	0.09	Up             	
26  148	 	u	0.11	Up             	
26  148	 	d	0.11	Up             	
26  148	 	u	0.09	Up             	
26  148	 	d	0.11	Up             	
26  148	 	u	0.11	Up             	
26  148	 	d	0.09	Up             	
26  148	 	u	0.16	Up             	
26  148	 	d	0.11	Up             	
26  148	 	u	0.14	Up             	
28  150	 	d	0.22	Down           	
28  150	 	u	0.12	Down           	
A4  038	 	d	0.28	LAlt           	
09  00F	 	d	0.03	Tab            	
A4  038	 	u	0.17	LAlt           	Task Switching
09  00F	 	u	0.02	Tab            	basic.ahk - MaxWorkstaion-Rev1 - Visual Studio Code
72  03D	 	d	2.02	F3             	
72  03D	 	u	0.16	F3             	
72  03D	 	d	0.12	F3             	
72  03D	 	u	0.16	F3             	
72  03D	 	d	0.16	F3             	
72  03D	 	u	0.12	F3             	
72  03D	 	d	0.16	F3             	
72  03D	 	u	0.17	F3             	
72  03D	 	d	0.22	F3             	
72  03D	 	u	0.20	F3             	
72  03D	 	d	0.09	F3             	
72  03D	 	u	0.19	F3             	
72  03D	 	d	0.12	F3             	
72  03D	 	u	0.17	F3         
````
