### ISSUE TITLE
Unable to clear key mapping win 11

### ISSUE THREAD

**Issue by Captainslarty** [randyrants/sharpkeys#566]
Dear sir,
I have a problem with several mapped keys on my laptop. I remapped 3 keys, then accidentally deleted the program thinking it would delete the mappings, it did not.  I have deleted the keyboard layout registry entry to no avail (Windows 11), the issue still persists. I am at a loss. The mappings I made are still there (not listed, but the keys remain still remapped) and I want to return the keyboard to as it was. I tried reinstalling the program and doing a delete all and writing to registry (although it didn't show any mappings on re-intall) again, to no avail.
I don't know if this is a win 11 issue or not ? - please advise anytest you may wish me to do or any action to take.
Thank you and keep up the great work.

**Comment by randyrants** [comment]
Not sure what's going on with this, so I'll repost what I know:
- The app exposes a Registry key that Windows then uses to remap the keys.
- Once the Registry value is set, the app can be uninstalled.

To clear an existing set of remapped keys:
- Either with the app install, delete all the entries in the UI, and save the changes, or
- Using regedit, update or remove the Scancode Map value under HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Keyboard Layout
- Reboot

Having the app installed or not will have no impact.  If the reboot doesn't happen the re-mappings will hold.

**Comment by Captainslarty** [comment]
Hi Sir, I have done both of those items listed, on their own, and together. The mappings still persist unfortunately.
I am at a loss.
Kindest regards, Joe

**Comment by Captainslarty** [comment]
Hi further info, still the same on safe boot which still tends to indicate a registry issue.
Kind regards,
Joe

**Comment by randyrants** [comment]
Can you take a screenshot of the Registry and post it here?

Do you have any other remapping software running?

Sorry if this sounds curt but this would be the first Windows machines I've seen to "refuse" to accept Registry changes since first disabling Caps Lock in 2002.

**Comment by Captainslarty** [comment]
![registry](https://github.com/randyrants/sharpkeys/assets/34556125/1c24d06c-0c4f-4d35-9c0a-8e98bcef81a9)
There you go sir, the whole section was deleted.
No other remapping running. 
Kind regards,
Joe

**Comment by randyrants** [comment]
That's the Control level, which isn't of any help.

Please select Keyboard Layouts and grab the capture again?  Should look like this:
![image](https://github.com/randyrants/sharpkeys/assets/18704482/3c779c0f-2a3f-4003-a650-d1aa377b02a2)

**Comment by Captainslarty** [comment]
Hi Randy, Just to clarify, what I posted actually shows that I removed the complete entry for 'keyboard layout'
Can we clarify between 'keyboard layout' and keyboard layouts' as I believe you refer to 'layout, not layouts.
If that is the case then I have nothing to post as, as I said, and was shown in the higher level overview of the registry the 'keyboard LAYOUT' doesn't exist now on my system. 
I apologise for any confusion.
If you want 'keyboard LAYOUTS' to be shown I can but this is not, I believe, what you are looking for.
Kindest regards,
Joe

**Comment by randyrants** [comment]
Sorry but I have no idea what is going on with your PC.

SharpKeys only edits one value for remapping keys in the Registry because Windows only looks in one place that I know of.
**Key**: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Keyboard Layout
**Value**: Scancode Map

That you have Keyboard Layout**s** likely means that you have multiple keyboard layouts installed, which could explain why keys are moving, but it would have nothing to do with SharpKeys: it has no code that reads from or writes to that key.

**Comment by Captainslarty** [comment]
Thank you Randy. I appreciate all your efforts. I will look elsewhere for a possible solution. Joe
