### ISSUE TITLE
The key is also disabled in my USB keyboard

### ISSUE THREAD

**Issue by valentina-zarate** [randyrants/sharpkeys#567]
Hi, I tried to use the program on my laptop cause the issue that i have is that the right arrow key press itself constantly on my laptop's keyboard. I use an USB keyboard because most of the keys from the laptop's just doesn't work.
When I disabled that key that was causing trouble it also did in my USB keyboard. I wonder if there's a way to disable the key only in the laptop's keyboard and make it work in the USB one cause I really need to use that key but I can't handle its constantly press.

**Comment by DreymaR** [comment]
No, there isn't an easy way to distinguish between keyboards on Windows. SharpKeys uses Registry remapping which works by scan codes, and those don't have a source tag on them.

To do what you want, you'd have to write some sort of driver I think.

**Comment by FaroJoaoFaro** [comment]
> Hi, I tried to use the program on my laptop cause the issue that i have is that the right arrow key press itself constantly on my laptop's keyboard. I use an USB keyboard because most of the keys from the laptop's just doesn't work. When I disabled that key that was causing trouble it also did in my USB keyboard. I wonder if there's a way to disable the key only in the laptop's keyboard and make it work in the USB one cause I really need to use that key but I can't handle its constantly press.

I think you have 2 options:
-Either you disable your laptop keyboard physically, disconnecting it, if you feel confortable doing that, which isn't very hard if you see some youtube video of disassembly of your laptop model.

-Or you can try to use AutoHotkey. I dont promise it works but I think its possible to disable a key for just one keyboard. You'll need to find your keyboard hardware id (on Device Manager or DevManView) and then you make a script for that id, to disable just the right arrow. Im sure chat-gpt can help you with this but feel free to message me on discord if you need support on this (@joaofaro)

**Comment by randyrants** [comment]
DreymaR and FaroJoaoFaro have the right of it, with both explanations.
