### ISSUE TITLE
Confused about installation process

### ISSUE THREAD

**Issue by aarontheman** [randyrants/sharpkeys#569]
Would like to try it under Win 11 on UTM virtual machine. With 'sharpkeys-master' folder open in Win, what do I do to actually install it?

**Comment by DreymaR** [comment]
You don't need to install this program, as it has no registry dependencies. Just run Sharpkeys.exe, that'll do it.

**Comment by aarontheman** [comment]
Okay, thanks for the clarification. I got my IT guy to install it on my
virtual machine, UTM. I don't suppose you have any experience with NVDA not
responding to remapped CAPS->Insert ?

**Comment by randyrants** [comment]
> You don't need to install this program, as it has no registry dependencies. Just run Sharpkeys.exe, that'll do it.

It does save windows position and size to the Registry as part of its function, but true: the app will run on any machine without an install.  Also, any keys that are remapped will stay remapped even if the application is uninstalled.  It's just a front end to the Registry; Windows does the actual remapping.

**Comment by randyrants** [comment]
> Okay, thanks for the clarification. I got my IT guy to install it on my virtual machine, UTM. I don't suppose you have any experience with NVDA not responding to remapped CAPS->Insert ?

Not sure what you mean here.  I mean, if it's installed to a VM, it will change the remapping for the VM's OS but not the host machine?

**Comment by aarontheman** [comment]
Sorry for the confusion. I'm on a Mac running UTM (free VM software), which is running Win11, and an app within Win is called [NVDA](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://www.nvaccess.org/download/&ved=2ahUKEwiMiZqi3PKHAxUHMzQIHWPHFDUQFnoECBcQAQ&usg=AOvVaw3AAc5nrFrg0lylpULGjjxr) -- screen reader software for sight-challenged people. I'm hoping to remap a key from Mac keyboard to one that works properly with NVDA. So far no luck.
