### ISSUE TITLE
00_100 Key unknown

### ISSUE THREAD

**Issue by JDMordi** [randyrants/sharpkeys#57]
Hi All,

Using your great tool to try and set a desktop into kiosk mode so just one website is displayed. Everything works great except hitting the FN key and the search button brings up the start bar and a search box in win 10. This would allow someone to get at windows.

I'm not worried that they can get at windows it doesn't have to be secure or anything, just this last key binding is annoying.

I saw on another issue that triple digit bindings were an issue so if it's not possible then no worries, thought I would ask though.

Thanks for any assistance you can provide.

JDM

**Comment by randyrants** [comment]
If you're shooting for a kiosk style lock down I would recommend a few other tools that Windows makes, like the Keyboard Layout editor.  Fn is often unknown by Windows so Windows doesn't have a chance to remap the key.

**Comment by JDMordi** [comment]
Thanks for the response Randy,

Strange though that windows will bring up the search box, so I would assume this is being passed to windows?

I'll take a look at the KLE you mentioned. Thank you.
