### ISSUE TITLE
Hi, am I able to change the press function of the Windows Key but maintain its functionality as a shortcut modifier?

### ISSUE THREAD

**Issue by Lexiconmancer** [randyrants/sharpkeys#571]
Hi, I read the FAQs and stuff but couldn't figure out if this is supported:

I'd like to rebind the actual Windows Key function, but maintain its use as a modifier for standard windows shortcuts aside from *just* the press function. I'm not seeing a clear way to do this, but I hope you don't mind me asking anyway. Would really appreciate your help!

**Comment by randyrants** [comment]
Hi - sorry this cannot be done with SharpKeys, as this is more of a macro function.  Please give AutoHotKeys or PowerToys a look.

**Comment by Lexiconmancer** [comment]
Thank you for the response.
