### ISSUE TITLE
Remap doesn't work

### ISSUE THREAD

**Issue by brian2lee** [randyrants/sharpkeys#572]
I installed sharpkeys though msi in the release, was trying to remap l-tab to r-alt and l-win to r-ctrl. Added the remap setting, write to registery, and rebooted my system. The remap turns out not working, keys still output the same input. Down below is my setups and the remap file.

[My Keys.zip](https://github.com/user-attachments/files/17088811/My.Keys.zip)

device specifications
> Device Name: LAPTOP-PHNQKA0S
> Processor: 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz 2.50 GHz
> Installed Memory (RAM): 32.0 GB (31.7 GB usable)
> Device ID: 2991DE01-54D3-4C02-A58D-161E402ABDEA
> Product ID: 00325-82185-87765-AAOEM
> System Type: 64-bit Operating System, x64-based Processor
> Pen and Touch: Pen support

Windows specifications:
> Version: Windows 10 Home
> Version: 22H2
> Installed on: ‎2021/‎8/‎24
> Installed on: ‎2021/‎8/‎24
> Experience: Windows Feature Experience Pack 1000.19041.1000.0

**Comment by brian2lee** [comment]
Welp I messed up. Instead of remaping A to B, I remap B to A.

**Comment by DreymaR** [comment]
Uncannily common beginner mistake, that. You're in good company it seems!
