### ISSUE TITLE
E0_52 Key (Insert) can't be remapped

### ISSUE THREAD

**Issue by jamesdehart** [randyrants/sharpkeys#573]
I'm using version 3.9.4 on Win 11 Pro with Akko 5075B Plus Mechanical Keyboard 75%  [keyboard](https://www.amazon.com/Akko-Mechanical-Keyboard-Percent-Hot-swappable/dp/B0CF1Q4WHT). No plugs for the keyboard but only to provide details on what I'm using.

![image](https://github.com/user-attachments/assets/5115be48-6153-4bf0-8499-c3904fb53171)

![image](https://github.com/user-attachments/assets/dbde5a66-52f4-4dc1-a80b-3301e1305a76)

Thanks!

**Comment by makathome** [comment]
(00_100) me too, a button for home web page

**Comment by DreymaR** [comment]
Just find those keys in the list instead. If they do provide single scan codes (like the Home key actually producing the Multimedia Home key and not some compound-key magic), they should be fine.

**Comment by randyrants** [comment]
And if it's 00_100, it won't be remappable, as is called out in the FAQ.
