### ISSUE TITLE
MX Keys S - remapping left CTRL/Win/ALT

### ISSUE THREAD

**Issue by Alinoe1** [randyrants/sharpkeys#574]
Hi i have problem with remapping these tree keys. 
Program not recognise Left ALT - when pressed, but have good reaction for Left CTRL (00_1D) and Left Windows (E0_5B).
Where is the problem? I must remapp LeftAlt to LeftCtrl, LeftWin to LeftAlt, LeftCtrl to LeftWin.
Help ;)

**Comment by randyrants** [comment]
Hi - this is covered in the docs:

## Things that SharpKeys _will_ do:
* Force you to look for the Left or Right ALT key in the list of available keys because Type Key cannot scan for ALT

**Comment by DreymaR** [comment]
It's not the program's fault. Windows will do some low-level stuff to sided mod key presses, to ensure that stuff like "any Alt key" works.
