### ISSUE TITLE
Question about the app.

### ISSUE THREAD

**Issue by Spontini** [randyrants/sharpkeys#575]
I have a keyboard with a numpad and I am thinking about buying a numpad only keyboard and hoping to use it as a button box. Would it break my main keyboards numpad or this software can recognize two different hardwares and only remap the other one?

**Comment by randyrants** [comment]
Windows doesn't have a way to tell the difference between the two bits of HW, when remapping.  You'd likely have to have a special driver to treat the extra keypad differently, sort of what Elgato's Stream Deck products do.
