### ISSUE TITLE
New key Sharpkeys doesn't know about (E0_1F2E)

### ISSUE THREAD

**Issue by lucassouce** [randyrants/sharpkeys#581]
I use a Compaq CPQ135KB keyboard and wanted to map it to the calculator like it should be, but Sharpkeys donesn't know about it.
same with (E0_1F20) which should open Word, (E0_1F12) which should open Excel, (E0_1F12) should open Powerpoint, and (E0_1F18) should open the Calendar. I mainly care about (E0_1F2E)  but i figured that the goal is to find and add as many buttons as possible right?

**Comment by randyrants** [comment]
Sorry - this is a triple-byte code and outside of what Windows can remap.

Might want to check out PowerToys or AutoHotKey.
