### ISSUE TITLE
Unknown keys

### ISSUE THREAD

**Issue by rik-no** [randyrants/sharpkeys#6]
Hi Randy,

anything you can do about key combinations with AltGr or ALT+CTRL? I use an english international keyboard on Win10 and want to have umlauts on AltGR+{a,o,u,e,i,A,O,U,E,I,s,e,E}.

TIA
Rik

**Comment by randyrants** [comment]
@rik-no - Sorry, but no key combinations are supported by the bit of Windows tech that is mapping the keys.  It's only ever a whole key.

**Comment by randyrants** [comment]
For additional information, please check the [readme.md](https://github.com/randyrants/sharpkeys/blob/master/README.md)
