### ISSUE TITLE
E0_2038 (Dell Precision m4800 laptop right alt key)

### ISSUE THREAD

**Issue by digitalsmear** [randyrants/sharpkeys#61]
In earlier versions of SharpKeys I was able to remap this key (which is only sort of recognized by windows as an alt key) to match the left-alt key, to fix some odd problems that pop up in software that does it's own keyboard management, like video games and photoshop.

I forget which version it last worked in, but the current version and 3.5 both tell me that they don't recognize the key code and won't allow me to remap it, even though it clearly recognizes the key.

Is there a workaround for this, or can it somehow otherwise be addressed?

Thanks.

**Comment by randyrants** [comment]
Honestly, the code hasn't changed from 2.0 or so through 3.x - the UX has been updated but the remapping tech has not.  If anything, it sounds like the Dell drivers may have changed over time, preventing this key to be remappable.  You might want to try a more active remapper like AutoHotKeys.
