### ISSUE TITLE
Keys on HP Elitebook x360 that cannot be mapped

### ISSUE THREAD

**Issue by Wautean** [randyrants/sharpkeys#63]
Hi,
I use a HP Elitebook x360, with Win 10 Fall Creators update and Sharpkeys 3.6
The PC has 2 keys to use for internet calls:
- phone pick up. In Sharpkeys in the dialogue box of 'Type key' it doesn't get a code. However when I use it in combination with CTRL it gets code E0_205B.  
- phone hang up. In Sharpkeys in the dialogue box of 'Type key' it gets code E0_1F65.
Both cannot be mapped, because they both give 'You've entered a key that Sharpkeys doesn't know about'. Please check the Sharpkeys website for an updated release.

Can you indicate whether you plan a release with this issue solved and if yes, when

Thanks
Anne-Mie Wauters

**Comment by randyrants** [comment]
Hi Anne-Mie,

These are both triple byte keys and nearly impossible to map through SharpKeys - I'll leave this comment open, if another coder at github wants to take a crack at it, but I've had absolutely no luck in getting a triple byte code remapped.

Thanks!
