### ISSUE TITLE
Using an Apple Magic keyboard

### ISSUE THREAD

**Issue by RobThree** [randyrants/sharpkeys#64]
Leaving this here as documentation (since I couldn't edit the/a Wiki): I'm using an [Apple Magic Keyboard (with numpad)](https://www.apple.com/shop/product/MQ052LL/A/magic-keyboard-with-numeric-keypad-us-english?fnode=56) and these are my mappings:

![Screenshot](https://user-images.githubusercontent.com/607888/34587789-156f0370-f1aa-11e7-82db-7dd3ed239cc4.png)

And this is the registry data:

    Windows Registry Editor Version 5.00

    [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Keyboard Layout]
    "Scancode Map"=hex:00,00,00,00,00,00,00,00,0c,00,00,00,37,e0,64,00,46,00,65,00,\
      20,e0,67,00,6a,e0,68,00,2e,e0,69,00,30,e0,6a,00,45,00,45,e0,5b,e0,38,00,38,\
      00,5b,e0,5c,e0,38,e0,38,e0,5c,e0,00,00,00,00

Save the above in a `.reg` file (e.g. "apple_keyboard.reg" for example), double-click the file, allow it to be imported. Log off and back on (works on my Win10 machine, you _may_ need to reboot) and you're set!

This maps:

<kbd>F13</kbd> -> <kbd>PrtScr</kbd>
<kbd>F14</kbd> -> <kbd>Scroll Lock</kbd>
<kbd>F15</kbd> -> [Sorry, can't map to <kbd>break</kbd>](https://stackoverflow.com/a/38850436/215042)
<kbd>F16</kbd> -> <kbd>(Un)Mute</kbd>
<kbd>F17</kbd> -> <kbd>Web: Back</kbd>
<kbd>F18</kbd> -> <kbd>Volume Down</kbd>
<kbd>F19</kbd> -> <kbd>Volume Up</kbd>
<kbd>Clear</kbd> -> <kbd>NumLock</kbd>
<kbd>Left Option</kbd> -> <kbd>Left Windows</kbd>
<kbd>Left Command</kbd> -> <kbd>Left Alt</kbd>
<kbd>Right Option</kbd> -> <kbd>Right Windows</kbd>
<kbd>Right Command</kbd> -> <kbd>Right Alt</kbd>

Unfortunately the <kbd>⏏</kbd> key (between <kbd>F12</kbd> and <kbd>F13</kbd>) and the <kbd>fn</kbd> button cannot be mapped (the latter I'd love to map to <kbd>insert</kbd>.

I use the above settings with [Tray Status Pro](https://www.traystatus.com/) to show the numlock and caps-lock states (can also do scroll-lock but I don't use it anyway) and only seldomly miss my [HP Keyboard](https://user-images.githubusercontent.com/607888/34588307-8faaa854-f1ac-11e7-892b-13e8e026ee94.png) that I've used for over two decades. I use(d) <kbd>shift</kbd> + <kbd>delete</kbd> and <kbd>shift</kbd> + <kbd>insert</kbd> as <kbd>ctrl</kbd> + <kbd>c</kbd> / <kbd>ctrl</kbd> + <kbd>v</kbd> (copy/paste) alternative a lot since I can more easily find those keys blindly. Also being a programmer I miss the (<kbd>ctrl</kbd> + ) <kbd>break</kbd> key combo. Also the [menu key](https://user-images.githubusercontent.com/607888/34588637-54b4a9dc-f1ae-11e7-9726-48812fcfbe70.png) is missing on the Apple Magic Keyboard so I didn't map it (maybe possible to use <kbd>F17</kbd> for; but haven't figured out the codes (yet)). But that's about it. The rest works as expected.

I hope this information is useful to anyone. @randyrants : Thanks for the great tool 👍 Please consider opening the Wiki? 😘

**Comment by randyrants** [comment]
Just flipped it on, I think - plz let me know if it's not active.

**Comment by RobThree** [comment]
I see a wiki but no way to edit / add.

**Comment by randyrants** [comment]
Should be enabled now!

**Comment by RobThree** [comment]
[Using an Apple Magic keyboard](https://github.com/randyrants/sharpkeys/wiki/Using-an-Apple-Magic-keyboard)

**Comment by psyanite** [comment]
@RobThree, thank you so much 🙏

**Comment by nwittwer** [comment]
If anyone's using the Magic Keyboard without the numpad, this combo works quite nicely:

![image](https://user-images.githubusercontent.com/6360459/73005198-d7d5e080-3e08-11ea-83b1-c2c1bd4d612d.png)

_NOTE: I personally don't use the right `command` or `option` keys, so I haven't mapped them here._

**Comment by kevinjohncutler** [comment]
> 
> 
> @RobThree, thank you so much 🙏
> I'd really like to be able to map the eject key to delete, it can be done in https://github.com/samartzidis/WinAppleKey, perhaps it could be done in SharpKeys?

Did you figure out how to do that? I don't even know what code the eject key has. It does not come up with "type key" dialogue.

**Comment by verityj** [comment]
@kevinjohncutler 
> I don't even know what code the eject key has.

https://verityj.github.io/2023/06/17/eject.html HID key is 0xC000000b8. References included. I don't know how to create a proper scancode map for Windows for it, though.

**Comment by RobThree** [comment]
For future reference: since I got myself a [macropad](https://aliexpress.com/item/1005006353186903.html) (which... isn't bad), the swapped win/alt keys in SharpKeys which were then swapped back by MagicKeyboard (don't know or remember why I did that in the first place...) caused some confusion when configuring key combo's that used ALT in the (very spartan) macropad config utility.

So the registry key is now:

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Keyboard Layout]
"Scancode Map"=hex:00,00,00,00,00,00,00,00,05,00,00,00,20,e0,67,00,6a,e0,68,00,\
  2e,e0,69,00,30,e0,6a,00,00,00,00,00
```

And the settings are now as follows:

![image](https://github.com/randyrants/sharpkeys/assets/607888/6c87ea9c-cc8b-4758-b48a-13cf40d534ee)

I know, I'm quite sure this is not very interesting for anyone, but still... you never know.
