### ISSUE TITLE
Cannot recover tab key

### ISSUE THREAD

**Issue by ether23** [randyrants/sharpkeys#65]
Attempted to map the tab key to another key. I believe it worked but only temporarily. Now for months I've had the tab key doing the function of the key I tried to move it to. Whatever I do I can't get the tab key function back to the original key (tab key). It seems like the tab key basic function is lost. Do I need to download something etc. Thanks

**Comment by ether23** [comment]
Anyone???

**Comment by glittle** [comment]
Have you re-run the SharpKey program? You should see the mapping there and can remove it, then reboot.

**Comment by ether23** [comment]
I repaired the program, wasn't sure how to re-run, than selected the tab key in the "From" selection and changed the "To" selection from (Turn Key Off) to the tab key and it worked. I don't recall the "To" selection being (Turn Key Off) originally. Thanks

**Comment by ether23** [comment]
It worked upon rebooting.

**Comment by ether23** [comment]
It worked upon rebooting. Thanks again
