### ISSUE TITLE
Avoid chain of remapped keys

### ISSUE THREAD

**Issue by glittle** [randyrants/sharpkeys#66]
I have remapped the Caps Lock key to be an Enter key. I love it and have used it for years!  When using the mouse in the right hand, I can press Enter (via Caps Lock) easily.

However, I occasionally need the Caps Lock key. I had a situation where a help desk person remotely controlled my PC and they must have had Caps Lock on. That turned it on for me. There was no way to turn it off! Even when they pressed their Caps Lock key, it became Enter on mine.

So, I tried to remap a different key to be Caps Lock, like the ScrLk key.  That almost worked, but now ScrLk also invokes the Enter function.  It seems that the mapping from Caps Lock to Enter gets invoked when the ScrLk presses Caps Lock for me.

Is there any way to assign the Caps Lock function to another key when the Caps Lock key is assigned to be Enter?

**Comment by randyrants** [comment]
Not that I know of: this is how Windows is remapping the key, which I think was done on purpose. Since you've told Caps Lock to be Enter, any other key that tries to be Caps Lock becomes Enter.

Sort of like A points to B; if C points to A, it's the same as pointing to B.

**Comment by glittle** [comment]
That's what I was afraid of.  :(

Anyways, great tool! Thanks.
