### ISSUE TITLE
Odd UX

### ISSUE THREAD

**Issue by cnote678** [randyrants/sharpkeys#70]
Upon first try, the way to remap keys seems counter-intuitive. Example: 

My intention was to duplicate my left Ctrl key to my right Alt key. Using your software, it made sense to put the Ctrl key in the "From" space, i.e. "Take function from X key" and then put the Alt in the "To" space, i.e. "Take function from X key and map it to Y key". Perhaps this was a glitch (running Windows 10 on a Surface Laptop), but when I wrote to registry, it did exactly the opposite of what I intended: it took the function FROM the Alt key and applied it TO the Ctrl key, thus duplicating my Alt key.

Entering the opposite, i.e. "From" Alt key "To" Ctrl key worked, but this seems highly illogical. If I want my P key to type Qs, it's much clearer to say: "Assign function Q to key P" rather than "Take key P and assign it to function as Q".

Maybe it's just me; either way once I figured this out, mission accomplished. Just thought it might make for an easier UX. Thanks!

**Comment by randyrants** [comment]
Thanks for the feedback, but I think you're reading in to the UX deeper than it was mean to.  The from/to is remap CapsLock to Shift - I think expecting someone to see it as "take the functionality from this key and put it on that key" is pretty hard, even with more text.

**Comment by cnote678** [comment]
You may be right. Either way, thank you for the awesome product-you rock!
