### ISSUE TITLE
Missing keys

### ISSUE THREAD

**Issue by MidoSpace** [randyrants/sharpkeys#71]
Hi there, 
I just got a Lenovo IdeaPad 310 and it comes with this terrible keyboard, so I needed a remapping app so bad, and SharpKeys was the best solution so far.
I just couldn't remap some keys such as F1, F4, F7, F11 and F12 those come as Mute, Mic Off, Airplane Mode, Brightness Down and Brightness Up respectively. When I hit those keys SharpKeys does not show any response like if they were not pressed!

Thank you!
Ahmed

**Comment by randyrants** [comment]
Knowing Lenovo, these are all hardware buttons and cannot be mapped through directly.

You might want to turn on F-Lock instead of trying to remap all of the Fn keys.  HTH!
