### ISSUE TITLE
Missing code for "Alt Gr" (German keyboard)

### ISSUE THREAD

**Issue by otmarlendl** [randyrants/sharpkeys#72]
Hi,

As you're asking for Input on "A more complete list to support more international keyboards":

On German keyboards, the "Alt Gr" key is used to reach symbols that had to make room for the umlauts. See also https://en.wikipedia.org/wiki/AltGr_key

SharpKeys' "Type Key" feature gives a value of "E0_2038" for the "Alt Gr" key. 

Please add support for this key to Sharpkeys.

Thanks.

**Comment by randyrants** [comment]
I'll leave this open for other contributors I don't have access to international hardware but as this is a triple byte scan code, I'm not expecting it to be easy to remap it.

**Comment by BCool13** [comment]
+1

This should be nice as this is very anoying behavior

**Comment by johannesleander** [comment]
I'm using a Swedish keyboard in Windows 10 and had the same issues as OP.

As per the answer of Tomas Sedovic in [this Stackoverflow thread](https://stackoverflow.com/questions/229633/how-to-globally-map-altgr-key-to-alt-key), "Right Alt" works flawlessly as a substitute for Alt Gr.

I'll try to fix this issue by creating a special case for the Alt Gr key.

**Comment by randyrants** [comment]
This is now in 3.7.
