### ISSUE TITLE
Headless run?

### ISSUE THREAD

**Issue by avishnyakov** [randyrants/sharpkeys#73]
Hey guys, 

Thanks for this tool, works incredibly well. I wonder if there is a way to run sharpkeys in automated, headless way? We are looking into some automation so that it can be pre-installed and pre-run with specific keymap settings.

Say, we have a config file somewhere, and then run something like
```bash
sharpkeys -config "my-keys-config.xml"
```

**Comment by randyrants** [comment]
There's source code here, so I'm sure someone could do this, but I think it would be easier to use SharpKeys to set your keys, save out the remapping to the Registry, and then export a .reg file that you can then apply to other machines.  Should be easy enough of a workaround until someone wants to code the feature.

**Comment by avishnyakov** [comment]
Fair enough,  I see this working.
