### ISSUE TITLE
Can't select ALT key from typing

### ISSUE THREAD

**Issue by kopeboy** [randyrants/sharpkeys#75]
Which is the most important key to change if you want to have a mac-like experience (Cmd key).

In the Add new key mapping window, select Type Key, type ALT, nothing appears.

Do you know the key code please? Thank you

**Comment by randyrants** [comment]
Known limitation of Type Key: the ALT press goes to the windows itself and toggles the system menu.

You can still select ALT keys in the list of keys though.  I do this on my own laptop.

**Comment by NA-Dev** [comment]
When I select ALT from the list and save the registry edit, it did not work. The keys I was trying to swap both no longer work.

**Comment by mohamed0242** [comment]
it called alt gr in the program

**Comment by randyrants** [comment]
...and ALT+GR is not supported, per the FAQ.

Not sure what ALT+GR has to do with this point, which is specifically about ALT, and has been closed for 4 years but eh.
