### ISSUE TITLE
No 32 bit version?

### ISSUE THREAD

**Issue by ooker777** [randyrants/sharpkeys#76]
![](https://i.imgur.com/cAGAIYq.png)

**Comment by randyrants** [comment]
Pretty much.  Since most machines have support x64 for the last 8 or 9 years, I've stopped building installs for x86,  That said, you can still compile the source for x86 - I think you might even be able to compile for ARM - and run that or you can check my blog for an older versions of the app for an x86 version.

**Comment by ooker777** [comment]
Not forcing you to do anything, but why can't x86 installer be compiled
easily? --

Ooker. (📱)

**Comment by randyrants** [comment]
Because it’s extra work to maintain two installs in a world where 95% of machines are x64 based.  Since I pushed the source code out to GitHub for collaboration, it’s open to anyone to compile for x64 or x86 - even ARM or ARM64.

**Comment by olegstepura** [comment]
It makes sense to use x86 virtual machines because such VMs take disk space and sharpkeys inside such VM is a saver, so I would say x86 builds are way more valuable than you think.

**Comment by randyrants** [comment]
Then I would go with the standalone ZIP file: the EXE is compiled for “Any CPU” so it should work just fine on an x86 VM.

**Comment by olegstepura** [comment]
Thanks, this works nicely!

**Comment by randyrants** [comment]
It was never about supporting x86 as a platform decision - it was about having to support two versions of the MSI (or three if SharpKeys ever goes to ARM).  Installation scripts historically suck - badly - which is why I wanted to avoid the extra overhead.

 

But the app should work fine 😊

**Comment by olegstepura** [comment]
Since it's written in .Net i think there is actually out of the box support for both x86 and x64, no?

**Comment by randyrants** [comment]
If you compile it that way, yes but if you use external libraries you may not be able to go for both.

**Comment by olegstepura** [comment]
Ok, anyways I suggest to mention it somewhere (releases page is the best place) that zip can be easily used on 32bit. So people who want to use it on 32bit would know how.
