### ISSUE TITLE
xbox360 xbox button (00_00) missing

### ISSUE THREAD

**Issue by kubbur** [randyrants/sharpkeys#77]
is it possible to add it to the list, would love to use the button as ptt button

**Comment by randyrants** [comment]
00_00 is not a valid scancode so it cannot be added to the lists.  In so far as I know the Xbox button is a special key that doesn't go through to Windows because there is no keyboard equivalent.

**Comment by kubbur** [comment]
I managed to remap it through joytokey, so there is probably some way to listen to it, if you want i can test for you 😉
I had to disable the gamebar in windows to get it to work

www.kristofersmari.com

Frá: Randy
Sent: fimmtudagur, 22. febrúar 2018 18:08
Til: randyrants/sharpkeys
Afrit: kubbur; Author
Efni: Re: [randyrants/sharpkeys] xbox360 xbox button (00_00) missing (#77)

00_00 is not a valid scancode so it cannot be added to the lists. In so far as I know the Xbox button is a special key that doesn't go through to Windows because there is no keyboard equivalent.

**Comment by randyrants** [comment]
Kind of my point: SharpKeys doesn’t do any of the remapping - it isn’t a driver or a TSR app.  It simply exposes a Registry key that Windows uses to remap scancodes.  If it doesn’t get a scancode for the Xbox button, there’s nothing that it can do for it.
