### ISSUE TITLE
question regarding remapping

### ISSUE THREAD

**Issue by InvisibleRasta** [randyrants/sharpkeys#78]
hello, i am in the need to have they keys remapped sometimes and sometimes not. i cant find a way in the app to remove the remapping without deleting every time the configurations.
since i use about 15 remaps, it takes me a long time to remap everything every time

**Comment by randyrants** [comment]
You can always set up the mappings and then generate an export of the Registry key that gets updated.  Still have to reboot between changes though.  You also might want to consider a more active remapper like AutoHotKeys.
