### ISSUE TITLE
key 00_100 is unknown.

### ISSUE THREAD

**Issue by lopy67** [randyrants/sharpkeys#79]
for me 00_100 is the calculator, I don't really need the calculator so I was trying to rebind it but I couldn't.

**Comment by lopy67** [comment]
oh just realized the calculator, and all the volume keys are 00_100 might not be possible

**Comment by randyrants** [comment]
Just means that there's a driver intercepting the scancode and passing a 00_100 to Windows.  Nothing much can be done for this.

**Comment by shezdogga** [comment]
Is it by chance a Ducky keyboard? I have a Ducky keyboard and found that all the volume+calculator keys have the same BIOS keycode, but have a different Windows keycode. This probably won't help but is just something I realised in case it may help
