### ISSUE TITLE
key maps reversed with Win10 Creators Edition

### ISSUE THREAD

**Issue by jrwhite59** [randyrants/sharpkeys#8]
After I upgraded to Win10 Creators edition my keymap was wiped out.  I remapped the 3 keys again, and rebooted.  The mapped keys were reversed.  For example, when I selected the [enter] key as the 'from' key ( by using the type key method .. key was correctly identified ) and the [backslash] key as the 'to' key, after the reboot, pressing the [enter] key resulted in a [backslash] being typed.

I cleared the maps, rebooted, then started again.  This time I transposed 'from' and 'to', rebooted, and all is working as expected.

Wonderful little sanity saving utility, btw, so thank you!

**Comment by randyrants** [comment]
I know the upgrade would have reset all the key remapping entries - I noticed that across all three releases of Windows 10.  Odd that they had to be flipped.  Do you know if they were entered in the same order the first time around?  I know that if you are doing a chain across the same keys it could end up weird depending on the order the keys are entered...

**Comment by jrwhite59** [comment]
Hi Randy,

 

Yes, I believe I entered them the same way as I did the first time.  I only started using your utility a few weeks ago, as an emergency replacement laptop ended up having a Canadian bilingual keyboard with odd key positions.  I didn’t see any documentation specifically, so I was careful not to use a key that had a destination remap as a source for another key.

 

This is what I did and in this order:

 

FROM [left shift] TO [non-standard backslash between [Z] and [left shift]

 

FROM [backslash] TO [num pad forward slash]

 

FROM [standard enter] to [backslash]

 

This worked fine originally, and then as I reported, this time everything was backwards.  The non standard backslash key remained a backslash and the left shift behaved as a backslash, etc.

 

When I mapped again using the same order as above, but reversing the TO and FROM keys, everything is working as expected.

 

In between each remap session I deleted the maps, wrote to the registry, and rebooted before making another remap attempt.

 

Hope this helps, and thanks again for this great utility.

 

Jonathan

**Comment by supersonicsixteen** [comment]
Oh heavens! This worked for me too! This is really strange. :/ 

I'll take it though! Thanks for figuring this out.

**Comment by statoj** [comment]
Me too! I had the same problems and after reading the above, I transposed the "To" with the "From" and remapped the Right Shift to the Page Up key and now it works!
THANK YOU SO MUCH! I am a professional transcriptionist and this weird keyboard configuation of the Lenovo  laptop was driving me completely buggy.

**Comment by statoj** [comment]
p.s. JR WHITE 59 you are brilliant!

**Comment by jrwhite59** [comment]
Thanks, statoj.  I've been running the development arm of a software company for 35 years now and still do a bunch of SQA, so I always look for patterns.  Not brilliant, just experienced.

**Comment by jrwhite59** [comment]
I'd venture that Randy's code was resilient to the changes that MS made.

**Comment by statoj** [comment]
Resilient or resistant?

That to/from switch was so odd.


On May 20, 2017 10:21 PM, "jrwhite59" <notifications@github.com> wrote:

I'd venture that Randy's code was resilient to the changes that MS made.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/randyrants/sharpkeys/issues/8#issuecomment-302910631>,
or mute the thread

**Comment by apraetor** [comment]
So Creator's Update plays nice with SharpKeys now? 

When it first deployed to my PC (deferred upgrades) a month ago it totally killed SharpKeys. The settings were wiped out as expected, but once I wrote new ones to the registry and rebooted my keyboard stopped working entirely; had to use the on-screen kb to log in and reinstall the HID keyboard driver; then everything was fine until I re-applied the SharpKeys registry changes. Same HID keyboard driver problem. Even plugging in a different USB keyboard didn't help.

So I reverted the upgrade and all is well. Maybe it was just bad luck.

**Comment by statoj** [comment]
Well, that's a a cautionary tale.

I just used SharpKeys on both of my Windows 10 laptops yesterday (with the
reversal of "to" and "from" ) and both are working great.

I will bear what you said in mind the next time Windows 10 sends future
updgrades.

**Comment by randyrants** [comment]
This is odd.  I've been running Creator Editor from the very first release (long before it hit the public) and I haven't see this behavior at all.  I've still got Caps Lock to Disabled and it's correctly turned off.

It feels odd that from Windows NT 4.0 through Windows 10 Anniversary Editor that it worked fine but Creator is somehow mixing things up and at the UX level.  The registry appears to be the same across the board.

Maybe there needs to be a 3.6 release that's particular to 10CE or a fork in the UX code or maybe the Registry _did_ change in the latest update so it needs to write out a different Scancode map for 10.0.15063 or higher?
