### ISSUE TITLE
Doesn't find Fn key on Type Key

### ISSUE THREAD

**Issue by rhazor** [randyrants/sharpkeys#80]
I got a function key in the location of left windows key, and only windows key on right, so I need to remap function key to windows right.

Clicking the Fn key on Type key nothing happens.

I did manual setting, but not working.

![sharpkeys_2018-02-26_12-08-37](https://user-images.githubusercontent.com/22996586/36664687-1b3157c8-1aee-11e8-8ad1-ee1f47ee039f.png)

**Comment by rhazor** [comment]
update: it also doesn't find left alt key on Type Key.

Keyboard model MSI Gaming Keyboard DS4100 on Windows 10.

**Comment by randyrants** [comment]
Fn is a hardware key and is different from computer to computer.  When the hardware passes along the scancode it's as E0_63 but there are other keyboards that do not pass it along, which means Windows is oblivious to it so it cannot be remapped.

Alt keys are trapped by the UX and cannot be seen by Type Key, which should have been called out in the FAQ.  You can find these keys in the list under Special and select it by hand.
