### ISSUE TITLE
Shift/pg up swap doesn't take

### ISSUE THREAD

**Issue by GoFastChickenWing** [randyrants/sharpkeys#81]
I am trying to switch the horrible Lenovo 910 keyboard (with Windows 10) shift key to the adjacent Page Up key.  I have it set as 

From: Special Right Shift (00_36) 
To: Arrow Up (E0_48)

The shift is disappearing altogether. Page up in in the shift spot now but shift is non-existent.  I figured I did it backwards and so swapped the code to be From (E0_48) To (00_36) and it still did not work. 

I did reboot between each registry edit, including between deleting code. Help?

**Comment by randyrants** [comment]
You've told Windows to fire Arrow Up whenever your press Right Shift key: when you remap a key, this is what's supposed to happen.  What were you expecting to happen in this situation?
