### ISSUE TITLE
App window is off desktop can't access it

### ISSUE THREAD

**Issue by JhonnyTerminus** [randyrants/sharpkeys#86]
The app window is shown off desktop

**Comment by randyrants** [comment]
Uh, this doesn't sound like a SharpKey issue.  I guess you can try to uninstall/re-install?

**Comment by JhonnyTerminus** [comment]
Workaround: You need to change resolution to bring the app on screen again

**Comment by 3ICE** [comment]
Alternatively, win+arrow keys will move the off-screen window back on your monitor as long as it has focus.
* Open sharp keys
* Hold down Windows key
* Press left/right until it becomes visible.
* release Windows key
* use mouse to fix window position / size as you usually would
