### ISSUE TITLE
Key is disabled

### ISSUE THREAD

**Issue by hezahonker** [randyrants/sharpkeys#89]
I am trying to remap the social networking app key on a gateway laptop. When I select it to map, it says disabled. Will this mean I cannot remap or are there additional steps that must be taken?

**Comment by randyrants** [comment]
If Type Key is reporting "disabled" then Windows itself sees the key as disabled.  I'm not sure there's much that can work here.

**Comment by hezahonker** [comment]
Thanks for your reply. I appreciate it.
