### ISSUE TITLE
Keys not recognized

### ISSUE THREAD

**Issue by arebelspy** [randyrants/sharpkeys#9]
On my Windows Surface Book, the Play/Pause, Mute, Volume Up, and Volume Down are all unrecognized (00_100).

Is there a way to add compatibility for these?

**Comment by randyrants** [comment]
Some hardware keys are not sent to the Windows subsystem; sounds like Surface media keys are part of that group.

[FAQ](https://github.com/randyrants/sharpkeys#things-that-sharpkeys-will-not-do)

**Comment by arebelspy** [comment]
Oh, that's too bad. Thanks for the response!

I know the keyboard brightness and function key aren't sent, they don't even register a keypress. But the media keys are sending something, just not the right code.
