### ISSUE TITLE
Unknown Key

### ISSUE THREAD

**Issue by ambs** [randyrants/sharpkeys#90]
I have a stupid bluetooth keyboard that, when using the Esc key, issues some other command (on Windows it opens a Browser). I really need the Esc key (no idea why somebody design a keyboard without it).

When trying to use sharpkeys, the identified code is `00_100`, that seems not to be supported. I think that, for "source key", there is not really the need to be a known key, as far as you know the code, and are able to intercept it (but I may be wrong).

But either going that way (allow unknown keys to be mapped) or adding that specific code to the app, would make me very happy.

**Comment by randyrants** [comment]
00_100 is a pretty much a "Windows saw a keypress but doesn't know what the key is" which happens a lot with media keys or special app keys.  Could be there's a driver that's expecting to intercept the key or something else funky with the keyboard.  Not too much Windows can do for this, I'm afraid.

**Comment by ambs** [comment]
Argh. Those are bad news. Yeah, the keyboard was cheap, and probably without support. Thank you anyway. It was a good attempt :)
