### ISSUE TITLE
Missing code for "Home" key (Cherry MX-Board 3.0).

### ISSUE THREAD

**Issue by Vattbleidd** [randyrants/sharpkeys#92]
As above, please add support for this key if possible.
![1](https://user-images.githubusercontent.com/23154102/37876350-65a0bd4a-304b-11e8-8bbe-956f0eefce6c.jpg)
![2](https://user-images.githubusercontent.com/23154102/37876351-65bdcc8c-304b-11e8-8659-5638c323822e.jpg)
![3](https://user-images.githubusercontent.com/23154102/37876352-65d7e75c-304b-11e8-8658-bc32a97c3866.jpg)

**Comment by randyrants** [comment]
00_100 is a pretty much a "Windows saw a keypress but doesn't know what the key is" which happens a lot with media keys or special app keys. Could be there's a driver that's expecting to intercept the key or something else funky with the keyboard. Not too much Windows can do for this, I'm afraid.

**Comment by philippbeckmann** [comment]
I remapped the key by using [this](https://superuser.com/a/1083375) method and Nir Sofer's [NirCmd](http://nircmd.nirsoft.net).

This is my registry change:
`[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\AppKey\7]
"ShellExecute"="\"c:\\Tools\\nircmdc.exe\" sendkeypress 0xB3"`

Maybe these AppKeys can be added to SharpKeys.

**Comment by randyrants** [comment]
If NirCmd works, I wouldn’t mess with it.
