### ISSUE TITLE
Undoing keymappings

### ISSUE THREAD

**Issue by hXtreme** [randyrants/sharpkeys#93]
I noticed (the hard-way) that deleting a key-mapping from the list does not restore the original mapping. So maybe something that resets (a set/all) keys to their default binding should be helpful.

This reminds me that adding a checkbox to (de)activate mappings will be nice addition.

In the meantime can you please tell me what registry entries should I inspect to undo this manually.

Thanks,
Harsh

**Comment by hXtreme** [comment]
Sorry, my bad.
Once I went through the code base and found the registry entry to edit, I didn't find the problematic mapping. So I thought, "Maybe, if I disconect my keyboard, restart and connect it again, it may work." And it worked!

But still, having a checkbox would be really amazing addition.

**Comment by randyrants** [comment]
This is not possible.  Windows only enforces the key mappings on reboot.
