### ISSUE TITLE
Feature for combined key presses?

### ISSUE THREAD

**Issue by benz145** [randyrants/sharpkeys#94]
Thanks for Sharpkeys, I love how simple it is! 

I would really love to be able to bind a button on my keyboard to open Explorer instead of using ctrl+e. Is it possible to bind from a key to an arbitrary combination of keys?

**Comment by randyrants** [comment]
Nope: single keys only.

**Comment by benz145** [comment]
Any chance you'd consider adding this feature or does it not fall without the scope of SharpKeys? I would hate to have to run another app just for multi key support : (

**Comment by randyrants** [comment]
There's no feature for me to add.  SharpKeys exposes a registry key that Windows uses to remap keys and it only remaps whole keys.  There's no way to remap CTRL+C to Z or Z to CTRL+C - the whole key goes.

**Comment by xan2622** [comment]
I understand this is out of the scope of SharpKeys, but it's sad that it can't map multiple key presses to one key. I guess this is one of the most requested features that Sharpkeys users want.

On a side note, it seems that it can be done with AutoHotkey (https://www.autohotkey.com) : 
https://superuser.com/questions/212175/mapping-multiple-keys-strokes-to-one-key

**Comment by randyrants** [comment]
This is exactly why I recommend AutoHotkeys for anyone looking for more of a macro manager or keyboard modifier app that stays active and running.
