### ISSUE TITLE
[Feature request] Option to disable mappings temporarily

### ISSUE THREAD

**Issue by haydenholligan** [randyrants/sharpkeys#96]
It's well known that some laptop keyboards have terrible layouts, so it might make sense to map `Up Arrow` to `Right Shift`. However, many users still use external keyboards, of which the layouts do make sense. 

Currently, in order to disable the mappings, you have to either remap them to themselves or something else or delete them. It would be very nice to temporarily disable the key mappings without having to specifically modify them.

**Comment by randyrants** [comment]
Since you'd have to reboot (or sign out/in) for the changes to take effect, there's no "quick" or "temporarily" disabling that can happen to the mappings.  That said, you can import/export the Key/Values from the Registry if you want to toggle between the remapping states.

**Comment by elmorekevin** [comment]
Could there be a way to map keys only on certain keyboards? Like have it match on the hardware vendor and device ID so you could have mapping that affects only input from one device?

**Comment by randyrants** [comment]
SharpKeys points to a Registry key - it has no idea what machine it's on or what keyboard is being used.  To do something more involved than that, you'll want to grab the source and work on it or find a more active remapper like AutoHotKeys.
